### ISSUE TITLE
Druid query optimization for Time series Line chart

### ISSUE THREAD

**Issue by kkalyan** [airbnb/caravel#1002]
Currently for time series druid query is generated with 

`"queryType": "groupBy"`

If we replace this with 

`"queryType": "timeseries"`

query returns much faster.

**Comment by xrmx** [comment]
@kkalyan interesting! is the query result the very same? Can we make the choice programmatically? If yes to both questions care to make a pull request?

**Comment by kkalyan** [comment]
Remaining query is exactly the same. Query result is also same.
But if there is groupBy field requested, we need to send groupBy, but if there is no fields in the groupBy Clause, timeseries will work fast. 

Please give me some idea about where this change should go, I'll send PR.

**Comment by the-dcruz** [comment]
@kkalyan You'll probably want to look at this function: https://github.com/airbnb/caravel/blob/master/caravel/models.py#L1232

**Comment by mistercrunch** [comment]
I always thought that druid should handle that on the query side, but in the meantime I'm not against handling that logic on our side if you want to send a PR
