### ISSUE TITLE
Add an option in line chart to show circle markers

### ISSUE THREAD

**Issue by dugjason** [airbnb/caravel#1004]
I've included a stacked bar chart, which does render correctly (based on the same query & data), to compare to the stacked time series, which is not rendering correctly;

![screen shot 2016-08-24 at 12 11 50](https://cloud.githubusercontent.com/assets/273718/17928815/93031df6-69f4-11e6-918c-7804a874bb3d.png)

![screen shot 2016-08-24 at 12 12 52](https://cloud.githubusercontent.com/assets/273718/17928819/9622bb5e-69f4-11e6-8135-8d06d01c43ba.png)

You can see the "like_count" and "comment_count" series are not being rendered.

The query run, and data available was as follows;

```
mysql> SELECT subtype AS subtype,
    ->        DATE_ADD(DATE(created_at), INTERVAL HOUR(created_at) HOUR) AS timestamp,
    ->        COUNT(*) AS count
    -> FROM table_name
    -> INNER JOIN
    ->   (SELECT subtype AS subtype__
    ->    FROM table_name
    ->    WHERE source_id IN ('cdd9172ccfff485084926cf7d9d2cd8d')
    ->      AND created_at >= '2016-08-23 23:12:52.000000'
    ->      AND created_at <= '2016-08-24 11:12:52.000000'
    ->    GROUP BY subtype
    ->    ORDER BY COUNT(*) DESC LIMIT 50) AS anon_1 ON subtype = subtype__
    -> WHERE created_at >= '2016-08-23 23:12:52.000000'
    ->   AND created_at <= '2016-08-24 11:12:52.000000'
    ->   AND source_id IN ('cdd9172ccfff485084926cf7d9d2cd8d')
    -> GROUP BY subtype,
    ->          DATE_ADD(DATE(created_at), INTERVAL HOUR(created_at) HOUR)
    -> ORDER BY count DESC LIMIT 50000;
+---------------+---------------------+-------+
| subtype       | timestamp           | count |
+---------------+---------------------+-------+
| like_count    | 2016-08-24 11:00:00 |   684 |
| comment_count | 2016-08-24 11:00:00 |    83 |
| comment       | 2016-08-24 01:00:00 |    24 |
| comment       | 2016-08-24 02:00:00 |    21 |
| comment       | 2016-08-24 06:00:00 |    16 |
| comment       | 2016-08-24 08:00:00 |    15 |
| comment       | 2016-08-24 03:00:00 |    13 |
| comment       | 2016-08-24 07:00:00 |    12 |
| comment       | 2016-08-24 05:00:00 |    11 |
| comment       | 2016-08-24 04:00:00 |    10 |
| comment       | 2016-08-24 10:00:00 |     9 |
| comment       | 2016-08-24 00:00:00 |     9 |
| comment       | 2016-08-23 23:00:00 |     7 |
| comment       | 2016-08-24 09:00:00 |     5 |
| comment       | 2016-08-24 11:00:00 |     4 |
+---------------+---------------------+-------+
15 rows in set (0.09 sec)
```

My setup is:
* MySQL 5.6.31
* Ubuntu 14.04.5
* Hosted on EC2
* Caravel from Master branch; latest commit 30ef8eb

**Comment by dugjason** [comment]
Interestingly nothing renders when I filter out the "comment" subtype. Could this have anything to do with the values containing an underscore character?

**Comment by mistercrunch** [comment]
A line chart requires 2 data points within a series to draw a line doesn't it? Maybe the solution here is to allow user to "Show Markers" as circles?

**Comment by mistercrunch** [comment]
Markers would also bring clarity around missing data points

**Comment by dugjason** [comment]
Yes, this seems to happen only when there is a data point missing. Showing the series including zero-values could really be helpful

**Comment by mistercrunch** [comment]
for Caravel to fill in your missing data check out the "Resample" option  in the "Advanced Analytics" sectoin
