### ISSUE TITLE
Is it possible to add unix timestamp support for time column

### ISSUE THREAD

**Issue by sanpingz** [airbnb/caravel#1036]
It looks Caravel heavily relies on time column for query. For my case, the existing tables are using unix timestamp as time column. Unfortunately, Caravel can't recognize unix timestamp, is it possible to support that?

In my mysql table, the time column is a double type, the value looks like `1472526903.358829`.

**Comment by dugjason** [comment]
Possibly linked to issue #998

**Comment by xrmx** [comment]
@sanpingz have you marked your column as dttm and it doesn't work?

**Comment by xrmx** [comment]
@dugjason looks unrelated to me :)

**Comment by sanpingz** [comment]
@xrmx Yes, I marked unix timestamp column to temporal, it doesn't work.
I noticed the generated query is:
```sql
SELECT COUNT(*) AS count
FROM `G_HT_UUT`
WHERE `UPDATE_TIME` >= '2015-08-31 06:41:28.000000'
  AND `UPDATE_TIME` <= '2016-08-31 06:41:28.000000' LIMIT 5000
```
The **UPDATE_TIME** column is double type as unix timestamp. It would work if the query is:
```sql
SELECT COUNT(*) AS count
FROM `G_HT_UUT`
WHERE from_unixtime(UPDATE_TIME) >= '2015-08-31 06:41:28.000000'
  AND from_unixtime(UPDATE_TIME) <= '2016-08-31 06:41:28.000000' LIMIT 5000
```

**Comment by xrmx** [comment]
@dugjason now it indeed looks like yours :)
@sanpingz can you try to do a custom field with an expression as Dug is doing in #998?

**Comment by sanpingz** [comment]
@xrmx @dugjason well, that's a workaround, need disable temporal column, and use custom query, definitely works.

Unfortunately, our users may know nothing about SQL, they are nontechnical guys.

**Comment by xrmx** [comment]
@sanpingz from the end user perspective it's matter of using field B instead of field A, no?. If by end user you mean admins that can setup the tables they should have a clue about these kind of issues.

**Comment by sanpingz** [comment]
@xrmx I meant end users, not admins, they need know something like what happened in the past 1 day, 1 week, etc. No way for them to use custom query. Even though admins help to create slices based on custom query, the datetime is hardcoded if I'm not wrong?

**Comment by xrmx** [comment]
@sanpingz Dug is using a custom field where the value of the field is casted to another type not a custom query

**Comment by sanpingz** [comment]
@xrmx Sorry I missed, custom field works for me, thanks a lot.
