### ISSUE TITLE
Caravel uninstall 

### ISSUE THREAD

**Issue by hugocar** [airbnb/caravel#1039]
Hi,
I tested caravel for a while. I would now like to remove it from the test server.

how can i shut down caravel properly?
how can i uninstall caravel properly?

**Comment by xrmx** [comment]
You uninstall like any other python application, you stop it depending on how you started it...

**Comment by hugocar** [comment]
I started it following the "Caravel installation and initialization" guide on caravel.io

I am not familiar with python, does `pip uninstall caravel` will remove all component of caravel, including the database caravel uses internally ?

**Comment by xrmx** [comment]
@hugocar pip uninstall will remove whatever pip installed, so no, you have to take care of everything else yourself.

**Comment by hugocar** [comment]
Just to be sure, by "database caravel uses internally" i meant the database (if any) that caravel uses to manage users, roles, slices, dashboards etc... not my own stuff.

I will spend to time to identify whatever services and files are left after the pip uninstall
but it would be a nice addition to the "installation guide"

Thank you for Caravel and your help today
