### ISSUE TITLE
Error on Starting Web Server

### ISSUE THREAD

**Issue by JoeBrody** [airbnb/caravel#1041]
I am running Windows 7

Currently installing caravel (http://airbnb.io/caravel/installation.html[])

On this step:
# Start the web server on port 8088
python caravel runserver -p 8088

Error Message: 
C:\Users\Me\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask_cache\__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.                                          warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "                      C:\Users\Me\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.                                               .format(x=modname), ExtDeprecationWarning                                     2016-08-30 12:39:14,607:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (sqlite3.OperationalError) unable to open database file    

Any help would be much appreciated :)

**Comment by aljones** [comment]
The default SQLALCHEMY_DATABASE_URI of the release version doesn't work on windows unless you happen to have a preexisting c:\tmp folder.

**Comment by xrmx** [comment]
Closing then. Friendly reminder that for support questions better use the mailing list, thanks.
