### ISSUE TITLE
Issues using Filter Box when a comma is in the value

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#1045]

**Comment by yzliao** [comment]
The same error also happens in `flt_eq_1:` field

**Comment by vera-liu** [comment]
[https://github.com/airbnb/caravel/blob/master/caravel/models.py#L837](url)

**Comment by yzliao** [comment]
@vera-liu Is this a new patch or some existing codes?

cc: @Patrick1860

**Comment by vera-liu** [comment]
Sorry for the spam before, I proposed a solution by requiring values with comma to be wrapped in single quote. For instance, values of "A, B, 'Tahoe, CA', D" will be treated as ['A', 'B', 'Tahoe, CA', 'D'] after this fix
PR here: 
[https://github.com/airbnb/caravel/pull/1084](url)

**Comment by yzliao** [comment]
Thank you! This PR LGTM.

**Comment by xrmx** [comment]
Closing as fixed in #1084
