### ISSUE TITLE
Is there any documentation or tutorial on how to use SQL lab?

### ISSUE THREAD

**Issue by yejianye** [airbnb/caravel#1047]
Hi, 

SQL lab looks like a cool feature, but I could definitely use some tutorials or documentations. Currently, I'm a bit lost when trying to visualize my queries.

**Comment by mistercrunch** [comment]
It's not officially released yet, the big red `Alpha` tag on the navbar should highlight that.

**Comment by tiwansh** [comment]
Any updates on the documentation ?
