### ISSUE TITLE
Support more dashboard semantics around how filters affect slices

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#1057]
Currently:
* Widgets can emit filters
* The "dashboard controller" applies this filter by refreshing slices with an extra filter parameter
* Slices (in the context of a dashboard) can be made immune to filtering by editing the json configuration behind the dashboard (no ui controls are exposed to set this up)

Needed:
* Allow specifying which slices are immune to which fields.

Currently, the json_metadata for the dashboard has a `filter_immune_slices` key, which receives an array of slice ids. This should still be supported.

On top of that we need a new key `filter_immune_slice_fields` that is an object where the key is a slice_id, and the value an array of fields that it disregards. Or something equivalent.

**Comment by vera-liu** [comment]
Sorry didn't started looking into this until today, already done in: https://github.com/airbnb/caravel/pull/1179
