### ISSUE TITLE
Feature request: sorting in bar charts please

### ISSUE THREAD

**Issue by breakphreak** [airbnb/caravel#107]
I'm an excited Product Manager :) our Data Architect had just shown Panoramix to me and it looks very promising. What is missing so far is the sorting in Bar Charts.

**Comment by mistercrunch** [comment]
I'm assuming you're referencing the "Time Series - Bar Chart"?

**Comment by breakphreak** [comment]
Precisely! :) what a rapid response

**Comment by mistercrunch** [comment]
Should be done now. That was a one line change:
https://github.com/mistercrunch/panoramix/commit/4c8b275f8837b23dd1a606fac9d959addb458165#diff-51d3cdca5cf712763ee54c72935678c1R752

**Comment by breakphreak** [comment]
Thanks! That came in a blast! My favourit developer said he's waiting for the version to come as the nightly builds might be even less stable... any advices please? :)

**Comment by breakphreak** [comment]
ah, we've installed straight from the repository now, so we'll enjoy all the new features right away
the problem is that lots of views (except the table) seem to be broken now (separate issue opened)
