### ISSUE TITLE
Where can I find favorite dashboard or slices?

### ISSUE THREAD

**Issue by yejianye** [airbnb/caravel#1071]
Hi,

I found we can favor dashboards or slices. But after I favor those items, how do I find the items I favored in UI?

**Comment by xrmx** [comment]
Since you grok the code better grep than open issues :)

**Comment by yejianye** [comment]
Actually I did some grep in the code base, but haven't found how favorite is used.

**Comment by xrmx** [comment]
So it looks like favorites are written in the FavStar model but never read.

**Comment by xrmx** [comment]
I think #1169 will answer the question, closing.
