### ISSUE TITLE
Caravel Web UI not responding after adding a user and restart

### ISSUE THREAD

**Issue by vsreddy1602** [airbnb/caravel#1080]
2016-09-08 21:16:23,496:WARNING:flask_appbuilder.security.decorators:Access is Denied for: can_welcome on: Caravel

HI,

I get the above error after I added a user to Caravel.
The new user is unable to access the page.

So was I when I tried restarting the server and accessing it myself.

Was working fine till I was the only user.

Thanks,
Vidya

**Comment by xrmx** [comment]
Are you really sure you are accessing with the old user and not your new one?

**Comment by vsreddy1602** [comment]
Yes. I tried accessing with old user itself.

**Comment by mistercrunch** [comment]
@vsreddy1602 did you assign a role to that user and made him active by clicking the `Is active` checkbox ?

**Comment by xrmx** [comment]
One month without feedback,closing.
