### ISSUE TITLE
cant use from_unixtime

### ISSUE THREAD

**Issue by lifeinearth** [airbnb/caravel#1083]
Edit Sqla Table> Expression > i add from_unixtime(mtime, '%Y-%m-%d %H:%i:%S'),
when Query  the table, the sql change the next:

SELECT COUNT(*) AS count
FROM tp_pagesou
WHERE from_unixtime(mtime, '%%Y-%%m-%%d %%H:%%i:%%S') >= '2016-09-02 10:30:09.000000'
  AND from_unixtime(mtime, '%%Y-%%m-%%d %%H:%%i:%%S') <= '2016-09-09 10:30:09.000000' LIMIT 50000

how to delete the %

**Comment by xrmx** [comment]
Looks like a dup of #274. Closing.
