### ISSUE TITLE
Assigning users' permission to a particular filter value

### ISSUE THREAD

**Issue by neeagl** [airbnb/caravel#1089]
To make caravel support multi-tenancy, our data has a unique user id (as a dimension).. we want to be able to give out access to a common database to differnet users. one of the column refers to the user id and only those particular users should be able to access that data in their dashboard.

2. also is there a way to include a date range filter in the dashboard? right now we have to go to the slice explore view and change it there but its not convenient.

**Comment by xrmx** [comment]
The caravel way would be to split your data into multiple tables, one for each user / role. If you use the very same ids as caravel user you may hack something into viz.py `query_obj` to add a where clause.

**Comment by neeagl** [comment]
Thanks xrmx 

Also, is there a way we can add time range filter on the dashboard? Currently it looks like we can do that in explorer only,  but it's cumbersome to go there every time to change. 

If it's not provided today, can you please a way to do that?

**Comment by xrmx** [comment]
@neeagl there is already a bug about that. You know, the idea about open source projects is that everyone contribute a bit not that some people work for free for others :)

**Comment by neeagl** [comment]
I agree :) Just wanted to make sure if there's already a hack around since it's a common use case for several people 

Anyway, thanks a lot for your help.

**Comment by mistercrunch** [comment]
We may do this at some point

**Comment by xrmx** [comment]
@mistercrunch isn't #660 the same?

**Comment by bkyryliuk** [comment]
dup of the https://github.com/airbnb/caravel/issues/665

**Comment by ryanblacksa** [comment]
> The caravel way would be to split your data into multiple tables, one for each user / role. If you use the very same ids as caravel user you may hack something into viz.py `query_obj` to add a where clause.

Is there a more concrete solution to this? We need this functionality as well. I see its also requested [https://github.com/apache/incubator-superset/issues/660](url)
