### ISSUE TITLE
[table setup] Make SUM/MIN/MAX/... checkbox create the metric instantenously 

### ISSUE THREAD

**Issue by EstebanMonge** [airbnb/caravel#1091]
I am using sqlite to extract information with caravel.

The database have two columns time_estimated and time_spent with numeric types, in List Table Column I checked Sum, Min and Max.

When I want make a bar chart, I want to sum the time of columns, but in Metrics only appears COUNT(*) and INTEGER columns, time_spent and time_estimated are lost.

I made a trick with date columns, because are stored as integer with timestamp format, a datetime(date_create,'unixepoch') it works, I tried to make the same with NUMERIC, I used CAST(time_spent as integer) but in caravel in List Table Column the column type is UNKNOWN and in Metrics stills lost.

How can I sum NUMERIC columns?

**Comment by xrmx** [comment]
Which version of caravel?

**Comment by mistercrunch** [comment]
I know it's not intuitive, but after checking the sum checkbox you need to hit save for the related metrics to be created.

**Comment by EstebanMonge** [comment]
Hello we are using Caravel 0.9.0

**Comment by EstebanMonge** [comment]
I will check the save button.

**Comment by EstebanMonge** [comment]
It works!

May be can be usefull to put the Save button in all Tab.

Thanks a lot!
