### ISSUE TITLE
order_by_cols: '[' is not a valid choice for this field 

### ISSUE THREAD

**Issue by lihemin** [airbnb/caravel#1100]
add  order_by_cols  to  0.9.1  from master   cause  error  ：order_by_cols: '[' is not a valid choice for this field

**Comment by xrmx** [comment]
@lihemin Could you please update the report citing:
- which version of caravel you are using
- what you are doing and what you get, if it's an error please post the backtrace from the log

**Comment by xrmx** [comment]
One week without feedback, closing.

**Comment by jasonshah** [comment]
@xrmx I see this issue as well.
I have created a slice that is a table view with 3 "non-grouped-by" columns and 1 ordered column ("collectionid [desc]").
The slice itself executes correctly when viewing it in isolation.
However, when I add it to a Dashboard and open the Dashboard, I see the same error message in red:

> order_by_cols: '[' is not a valid choice for this field

The only thing that looks like an error in the webserver output appears when I refresh the slice:

```
/dev/temp/caravel/venv/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py:575: SAWarning: Can't resolve label reference u'collectionid'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))

```

I see no errors when I refresh the Dashboard.
(Is there another location to find error logs, other than the Terminal window in which I ran ```caravel runserver```?)

I'm running Caravel 0.10.0, installed via pip on OS X.

**Comment by xrmx** [comment]
@jasonshah could you please retry with latest git master?

**Comment by jasonshah** [comment]
I'm unable to follow the "Making your own build" section from http://airbnb.io/caravel/installation.html, because I get a dependency error on npm install. Right now I have to stick to the prepackaged versions distributed through pip...

**Comment by xrmx** [comment]
@jasonshah 0.11 is more or less what was master at the time :)

**Comment by jasonshah** [comment]
While I wasn't able to test it on the exact same test case (changes in the datasource and what not), I attempted to replicate this in a slightly different manner in 0.11, and it seems to work there with no errors.

**Comment by mistercrunch** [comment]
Closing for now, reopen if you see this on 0.12.0
