### ISSUE TITLE
Getting distinct values for filter fields

### ISSUE THREAD

**Issue by ShengyaoQian** [airbnb/caravel#1111]
Is there a way in caravel to get all distinct values for a field that I want to filter on? Like in the filter form it would display all the values that are filterable, and as I type in the value, it only display the ones that match.

**Comment by xrmx** [comment]
Something like this? https://github.com/airbnb/caravel/pull/1061

**Comment by ShengyaoQian** [comment]
yes, thanks @xrmx !
