### ISSUE TITLE
time series bar chart broken

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#1114]
On e895807158f754bc83a77b581949eb2499390019 firefox spit this but quite not useful with packed libs:
```
value not expected NaN during interpreration of attribute y2. explore.entry.js:7:7367
value not expected NaN during interpreration of attribute y. explore.entry.js:7:7367
value not expected NaN during interpreration of attribute height.  explore.entry.js:11:16027
```
The legend and the x axis label are displayed but nothing else.

All other time series visualization works fine with the same data.

**Comment by xrmx** [comment]
So this is a regression from 9ae231aeb8e826deee964e56df2732c81842336c since if i change the bottom margin to everything but "auto" it works fine. cc @vera-liu

**Comment by xrmx** [comment]
2132f6715e6e528a44a1a6387bcd9899063fbc7b does not help with the issue

**Comment by vera-liu** [comment]
Sorry going back and forth, this should fix it now: https://github.com/airbnb/caravel/pull/1124

**Comment by xrmx** [comment]
@vera-liu thank you very much! Will test on monday but it looks like it will fix it.
