### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by gurinderiitr** [airbnb/caravel#1117]
Hi ..
I am trying to build the source code.
Following the instructions I have installed the front end dependencies using npm.

on python setup.py I am getting error:

warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
numpy/core/src/npymath/ieee754.c.src:7:29: fatal error: npy_math_common.h: No such file or directory
 #include "npy_math_common.h"

I tried running with python3.

I am running this on ubuntu 14.04.4 LTS
Any help is appreciated.
Thanks

**Comment by xrmx** [comment]
Looks like numpy is not finding numpy headers. Maybe you are missing some numpy dependencies and have some earlier errors? Anyway closing as we cannot do anything about that.

**Comment by gzponline** [comment]
please
I can't find the setup.py in my superset home folder so I want to consult where location I should run "python 
 setup.py install "
