### ISSUE TITLE
Flask-Cache: CACHE_TYPE is set to null

### ISSUE THREAD

**Issue by ThomasEvansNZ** [airbnb/caravel#1133]
Hi there,

I have been attempting to install Caravel for the last 4 hours with miserable results - my Linux is rather rusty so perhaps the issue is user orientated...

The issue I am facing is around the creation of a admin user, I keep being returned the following error:

`/usr/lib/python2.6/site-packages/flask_cache/__init__.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
Was unable to import caravel Error: invalid syntax (views.py, line 880)`

Now I know that python2.6 is not supported, however I installed 2.7:

`[oracle@bigdatalite ~]$ python
Python 2.7.3 (default, Sep 18 2016, 21:11:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
`

So it seems odd to me that the packages are being installed under the /usr/bin/python2.6/site-packages directory in python? 

I have attempted to pip uninstall the various flask packages and retrieve previous versions which didn't help either. 

Any help would be much appreciated.

T.

**Comment by xrmx** [comment]
Better install caravel inside a virtualenv created with python3.4+ . If you can't do that python2.7 should be fine. Don't mess install python libraries in system python.
