### ISSUE TITLE
Grant permission to enable refresh widget on dashboard

### ISSUE THREAD

**Issue by amancevice** [airbnb/caravel#1136]
I would like help enabling what I'm calling the "refresh widget" (see below) for users. It appears this widget is only available for admin users using default roles (Admin, Alpha, Gamma), but it's not obvious to me which permission(s) the Admin role has that is enabling this widget. Any help or insight would be appreciated!

<img width="185" alt="screen shot 2016-09-19 at 12 43 42 pm" src="https://cloud.githubusercontent.com/assets/157711/18640593/ce70cc9a-7e66-11e6-8a72-1debb8273412.png">

**Comment by xrmx** [comment]
which version of caravel are you using? If not master please test master before any issue.

**Comment by amancevice** [comment]
I'm using `0.10.0`. Apologies for any confusion: are you saying users should clone the repo and install from source before opening an issue?

**Comment by xrmx** [comment]
@amancevice yes, please! that would help a lot.

**Comment by amancevice** [comment]
Are there instructions for doing this? 

When I follow the directions [here](http://airbnb.io/caravel/installation.html), substituting `pip install caravel` with `pip install -e <path/to/repo>` I get all sorts of CSS issues. I'm sure I'm just missing some step.

**Comment by xrmx** [comment]
https://github.com/airbnb/caravel/blob/master/docs/installation.rst#making-your-own-build

**Comment by amancevice** [comment]
Thanks!

**Comment by amancevice** [comment]
It looks like this is indeed fixed in master -- I wait with bated breath for `pip install 'caravel>0.10.0'` to succeed :)
