### ISSUE TITLE
Make autorun respect the async/sync flags

### ISSUE THREAD

**Issue by maver1ck** [airbnb/caravel#1140]
Hi,
I've got following issue: I can't edit queries in SQL Lab.
Is this feature working ?

Caravel version: master commit `afa1f0916b061d86afc2898515463876be5fa011`

**Comment by maver1ck** [comment]
OK. I moved to last commit `e8088d5c9a522db5e0e165988fba47893337fd5b`

I can edit query but there is no execute query button :)

**Comment by mistercrunch** [comment]
Oh, go to the database edit page and check "enable in SQL Lab" and "Allow Run Sync"
<img width="1065" alt="screen shot 2016-09-19 at 11 37 34 pm" src="https://cloud.githubusercontent.com/assets/487433/18659865/2137de68-7ec2-11e6-8faf-4f84c57ca390.png">

**Comment by maver1ck** [comment]
OK. Working :)

But could you try this scenario:

1. Add Database
2. Check only 'Expose in SQL Lab'
3. Go to SQL Lab
4. From dropdown select any table from this database 
5. Click on table 'Run query in new tab' (blue sign on top with '+')

The query is executed. Should it be this way ?

**Comment by bkyryliuk** [comment]
@maver1ck - yep that is expected.

**Comment by maver1ck** [comment]
@bkyryliuk 
So could you tell me what exactly those options mean ?
1) "Expose in SQL Lab"
2) "Allow Run Sync"
?

**Comment by bkyryliuk** [comment]
1) "Expose in SQL Lab" - makes the database available in the SQL Lab to query agaist
2) "Allow Run Sync" - there are 2 modes for running queries - sync and async. Async uses the celery backend and sync is executed within the request scope.
Async mode supports running long lasting queries, for instance hive.

To enable a database for sql lab both options have to be set.
