### ISSUE TITLE
seems dependency problems in js building

### ISSUE THREAD

**Issue by sbookworm** [airbnb/caravel#1142]
when installing caravel, execute "npm install" in "asset" folder, there was the problem below, which seems dependency problems

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-ace@3.5.0 wants react@^0.13.0 || ^0.14.0 || ^15.0.1
npm ERR! peerinvalid Peer react-bootstrap@0.30.3 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-bootstrap-table@2.5.3 wants react@^0.14.3 || ^15.0.0
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-grid-layout@0.13.5 wants react@^0.14.3 || ^15.0.0
npm ERR! peerinvalid Peer react-map-gl@1.5.0 wants react@0.14.x - 15.x
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-resizable@1.4.2 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-select@1.0.0-rc.1 wants react@^0.14 || ^15.0.0-rc || ^15.0
npm ERR! peerinvalid Peer react-syntax-highlighter@2.6.0 wants react@>= 0.14.0
npm ERR! peerinvalid Peer reactable@0.13.2 wants react@* || ^0.14.0
npm ERR! peerinvalid Peer enzyme@2.4.1 wants react@0.13.x || 0.14.x || ^15.0.0-0
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8

**Comment by mistercrunch** [comment]
what's your npm version?

**Comment by sbookworm** [comment]
oh, it's too low than you, I will try your version, thanks
