### ISSUE TITLE
Clicking on a user's role who is not active and making them active fires an error

### ISSUE THREAD

**Issue by jefffeng** [airbnb/caravel#1144]
If you click on a user's role who is not active and try to make them active outside of the "edit a role" flow, it fires the error in turquoise in the image below.

![unnamed](https://cloud.githubusercontent.com/assets/18297825/18659106/475e5d24-7ebd-11e6-896d-a628b282cdf7.png)

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/1138 fixed this
