### ISSUE TITLE
How to disable convert local-time to utc timezone in time-series bar chart

### ISSUE THREAD

**Issue by lxneng** [airbnb/caravel#1149]
![image](https://cloud.githubusercontent.com/assets/112606/18667844/c697c3d0-7f64-11e6-803e-072f1e514e0d.png)

that csv data is like

![image](https://cloud.githubusercontent.com/assets/112606/18667879/f814912c-7f64-11e6-9747-0d9a1e7d0bba.png)

**Comment by xrmx** [comment]
Are you sure this depends on timezone conversion? Anyway looks like a dup of https://github.com/airbnb/caravel/issues/763

**Comment by bkyryliuk** [comment]
we do not have any logic of handling the local time and the timezones. 
yeah, it looks like dup of the #763.

**Comment by mlieqo** [comment]
this can be solved with settings offset value in the datasource settings
