### ISSUE TITLE
Install Alpha Version of Caravel

### ISSUE THREAD

**Issue by marzoli93** [airbnb/caravel#1162]
Hello, How can I install Alpha Version of Caravel on Ubuntu and enable SQL Lab?

I follow this guide to install Caravel: http://airbnb.io/caravel/installation.html

Someone can help me?

Thanks

**Comment by xrmx** [comment]
Github is for reporting issue not for support please. The documentation is in this very same repository:
https://github.com/airbnb/caravel/blob/master/docs/installation.rst

**Comment by mistercrunch** [comment]
@xrmx I'm not against using GH issues for Q/A
@marzoli93  To build your own version from master check out the CONTRIBUTING.md in the root of the repo

**Comment by xrmx** [comment]
@mistercrunch the problem i have with GH issues for this kind of generic questions is that only a handful of people get notifications and will then answer. A lot more people may have been answered on gitter / mailing list / whatever.

**Comment by mistercrunch** [comment]
@xrmx you're right. We can put in an issue template with guidelines around that and other things.
