### ISSUE TITLE
Slides from Strata in pdf or other generic format

### ISSUE THREAD

**Issue by cuph62** [airbnb/caravel#1185]
Is it possible to have a pdf-version instead of iwa of the 

Slides from Strata (March 2016)

I can't read the file at 
https://drive.google.com/open?id=0B5PVE0gzO81oOVJkdF9aNkJMSmM

Thx,
Herman

**Comment by ascott** [comment]
i exported to pdf. enjoy!

[Caravel - Strata 2016.pdf](https://github.com/airbnb/caravel/files/490643/Caravel.-.Strata.2016.pdf)

**Comment by github35** [comment]
Thanks a lot
