### ISSUE TITLE
updating extras in databaseview/edit changes the sqlalchemy_uri

### ISSUE THREAD

**Issue by dennisobrien** [airbnb/caravel#1199]
If you edit a databaseview that uses a username and password but change only the extras field then click save, the value for sqlalchemy_uri_decrypted now is password-masked.

1. Add a database uri that uses a username and password.
2. Save, then return to this view.
3. Note that the SQLAlchemy URI is password masked in the UI.
4. Now change something in the extras field.
5. Save, then return to this view.
6. Note that the SQLAlchemy URI still is password masked in the UI.  But if you query the database for `database.sqlalchemy_uri_decrypted` it is now also password masked.

I think the simplest fix here is to add a check in `DatabaseView.pre_add` to check if `db.sqlalchemy_uri` (the value entered in the textfield) is different from `db.safe_sqlalchemy_uri()` and only call `db.set_sqlalchemy_uri(db.sqlalchemy_uri)` in that case.

There may be better user experiences to solve this so I'm open to suggestions.

**Comment by xrmx** [comment]
Given the amount of issues around that code we could use some more tests i suppose.

**Comment by dennisobrien** [comment]
I'm putting together a PR and will be sure to add tests.
