### ISSUE TITLE
IE 11 issues with Caravel

### ISSUE THREAD

**Issue by gurdeep18** [airbnb/caravel#1201]
I have a Caravel application which runs fine on Chrome and Safari, but I get issues when trying to access via IE 11.

Anyone else facing this issue?

**Comment by xrmx** [comment]
If you actually describe your issue it may be easier to help you. Anyway i don't think IE is a priority for the frontend people so if you care about that invest some resources on fixing any eventual issue.

**Comment by xrmx** [comment]
Closing as dup of #1302
