### ISSUE TITLE
must there be "AUTH_LDAP_BIND_USER" in caravel_config.py when i use LDAP mode?

### ISSUE THREAD

**Issue by conway-z** [airbnb/caravel#1210]
i use LDAP mode,then is give that caravel_config.py AUTH_LDAP_BIND_USER my own name:
AUTH_TYPE = 2
AUTH_LDAP_SERVER = "ldap://10.*.*.*:389"
AUTH_LDAP_SEARCH = 'OU=oname,OU=oname2,DC=ucarinc,DC=com'
AUTH_LDAP_BIND_USER = 'myname@mail.com'
AUTH_LDAP_BIND_PASSWORD = '***'
AUTH_LDAP_UID_FIELD = 'sAMAccountName'

problem:then, only my fellow they are in same department can access caravel. if i didnt set bind user, nobody can access.
how to solve that?
and must there be AUT_LDAP_BIND_USER? why?

**Comment by xrmx** [comment]
Auth is handled by flask-app-builder so i'd advise to ask there. Or maybe you are lucky and someone who uses ldap with caravel has anwer read this issue :)

**Comment by conway-z** [comment]
@xrmx i find in flask-app-builder doc, and solve the problem
i use MSFT AD.
config like that and caravel ldap user access:
AUTH_LDAP_SERVER = "ldap://10.*.*.*:389"
AUTH_LDAP_UID_FIELD = 'sAMAccountName'
AUTH_LDAP_APPEND_DOMAIN = 'ourDomail1.ourDomail2'
