### ISSUE TITLE
new database

### ISSUE THREAD

**Issue by attahkhan016** [airbnb/caravel#1211]
can you tell me know to use my local database , as I have tried all the methods to make it work . 
i have a database a MYsql database on my local machine . can you walk me through. 
2) should we need to create caravel_config.py , to connect my local mysql database. if yes  can you guide me where and how to create this caravel_config.py file .

**Comment by xrmx** [comment]
Could you please stop to open a new bug every day, sending me emails and poking me on linkedin? That's annoying to say the least. There's documentation, give it a read before pestering people.
