### ISSUE TITLE
Getting below error when running npm install

### ISSUE THREAD

**Issue by malleshm** [airbnb/caravel#1212]
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.36.1.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/Desktop/caravel-master/caravel/assets
npm ERR! node -v v0.10.46
npm ERR! npm -v 1.3.6
npm ERR! type called_on_non_object

Because of this not able to load all css files.

**Comment by malleshm** [comment]
Not able to load home screen with themes and other css's files.

**Comment by xrmx** [comment]
Which version of caravel is this? Pretty sure you need a newer npm (>3 IIRC ) to build the react stuff.
Also running stuff from root is not a great idea.

**Comment by malleshm** [comment]
thanks for quick help,

**Comment by malleshm** [comment]
I have update the npm verion to 3.0.8. After starting the caravel server.
I can see below error in the server log.

2016-09-28 20:40:28,316:INFO:werkzeug:127.0.0.1 - - [28/Sep/2016 20:40:28] "GET /static/assets/dist/css-theme.0.10.0.entry.js HTTP/1.1" 404 -
2016-09-28 20:40:28,376:INFO:werkzeug:127.0.0.1 - - [28/Sep/2016 20:40:28] "GET /static/assets/dist/dashboard.0.10.0.entry.js HTTP/1.1" 404 -

Due to this now able to open dash board.

**Comment by xrmx** [comment]
Please double check the build instructions. Seen at least a half dozen caravel build from master yesterday working fine.

**Comment by mistercrunch** [comment]
it's all in the CONTRIBUTING.md file, reopen if  things dno't work while following the instructions
