### ISSUE TITLE
How to set a begin time and a end time in a slice?

### ISSUE THREAD

**Issue by conway-z** [airbnb/caravel#1215]
a want set begin time and a end time, that i can report data between 2016-09-27 and 2016-09-28.
how can i implement that?

**Comment by xrmx** [comment]
C'mon there's a tutorial, videos, animated gifs that show how to filter by dates . This kind of questions better asked on gitter or the mailing list please.

**Comment by conway-z** [comment]
i had asked on gitter this question for 3 times, i didnt receive any answer...and i dont want to filter dates, i need sum data between date i input.

**Comment by xrmx** [comment]
@conway-z I can't see how filtering by date and then SUM a field is different than what you want to do.
