### ISSUE TITLE
Stale run_sync cache in the SQL Lab

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/caravel#1220]
Once I enable the DB that was disables to run the sync queries - the run button doesn't appear:
<img width="1238" alt="screen shot 2016-09-29 at 10 15 47 am" src="https://cloud.githubusercontent.com/assets/5727938/18964489/f4c0e6e0-862d-11e6-9f26-1204927b6587.png">

<img width="1404" alt="screen shot 2016-09-29 at 10 16 13 am" src="https://cloud.githubusercontent.com/assets/5727938/18964484/ee749f5c-862d-11e6-980c-63c78b7d7cb1.png">

**Comment by ascott** [comment]
i ran into this yesterday too. thanks for filing the bug.
