### ISSUE TITLE
JS error when loading SQL Labs

### ISSUE THREAD

**Issue by yejianye** [airbnb/caravel#1223]
Caravel version: master (96844c5c12c22e03bdbee61634c5b7dc138d19c5)
Browser version: Chrome 53.0.2785.143 (64-bit)

When loading SQL labs, I got the following error
```
Uncaught TypeError: 
Cannot read property 'apply' of undefined(anonymous function) @ compose.js:36
createStore @ createStore.js:65
(anonymous function) @ index.jsx:17
__webpack_require__ @ bootstrap 09560df…?abe2***:19
(anonymous function) @ bootstrap 09560df…?abe2***:39
(anonymous function) @ bootstrap 09560df…?abe2***:39
```

Any ideas what's going on?

**Comment by ascott** [comment]
thanks for the report @yejianye. i can repro on master too. i'll take a look.

**Comment by ascott** [comment]
i cleared my local storage and session cookie and I can no longer repro the JS error. @yejianye can you try that and see if it works for you?

**Comment by yejianye** [comment]
@ascott unfortunately, it's still not working for me. I tried 1) clear my local storage and cookies 2) create a new private browsing window. And I still got the same error in both cases.

**Comment by niconoe** [comment]
Same issue here, and clearing local storage/session cookie doesn't work for me neither. I also encounter the issue with Safari.

**Comment by ascott** [comment]
@vera-liu could you take a look into this bug? may be related to this PR: https://github.com/airbnb/caravel/commit/96844c5c12c22e03bdbee61634c5b7dc138d19c5

@niconoe if you can debug in your local environment and find a solution, plz feel free to submit a PR!

**Comment by vera-liu** [comment]
@niconoe @yejianye could you confirm if the errors are in dev environment? Thanks!

**Comment by vera-liu** [comment]
@niconoe @yejianye I was able to reproduce this after uninstalling Redux Devtool Extension. As we use Redux in Sqllab, we encourage all dev users to install Redux devtool in dev. I'll also add a warning for installing in another PR :) Thanks for the bug report!

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1228
