### ISSUE TITLE
ImportError: No module named fcntl

### ISSUE THREAD

**Issue by attibalazs** [airbnb/caravel#1235]
Hi,

I`m using windows 7 64bit, and following the instructions from your install guide: http://airbnb.io/caravel/installation.html

I run into an error when i try to start the server 
python caravel runserver -p 8088

Any help is much appreciated, thank you.

**Comment by xrmx** [comment]
As written in the documentation windows is not a supported platform. As you have found out gunicorn does not work on windows. My advice would be to install it on a linux machine. Or you can use the development web server which of course is not advised to run in production.

**Comment by attibalazs** [comment]
ok, thanks

**Comment by nekia** [comment]
I could avoid this error on windos env by using debug mode options.

`superset runserver -d`

**Comment by naveenjafer** [comment]
@nekia How exactly did you get it running??

**Comment by nekia** [comment]
@naveenjafer As far as my quick check, every example dashboard (Misc Charts/Births/World's Bank Data) seems to be running properly.

**Comment by naveenjafer** [comment]
@nekia what I meant is, where do I set these debug mode options? I am new to gunicorn. Thanks

**Comment by nekia** [comment]
@naveenjafer I just put '-d' option with runserver command for using development web server ( starting web server in debug mode) as I mentioned https://github.com/apache/incubator-superset/issues/1235#issuecomment-342367627 .

```
$ superset runserver -?
usage: superset runserver [-?] [-s SOCKET] [-t TIMEOUT] [-w WORKERS] [-p PORT]
                          [-a ADDRESS] [-n] [-d]

Starts a Superset web server.

optional arguments:
  -?, --help            show this help message and exit
  -s SOCKET, --socket SOCKET
                        Path to a UNIX socket as an alternative to
                        address:port, e.g. /var/run/superset.sock. Will
                        override the address and port values.
  -t TIMEOUT, --timeout TIMEOUT
                        Specify the timeout (seconds) for the gunicorn web
                        server
  -w WORKERS, --workers WORKERS
                        Number of gunicorn web server workers to fire up
  -p PORT, --port PORT  Specify the port on which to run the web server
  -a ADDRESS, --address ADDRESS
                        Specify the address to which to bind the web server
  -n, --no-reload       Don't use the reloader in debug mode
  -d, --debug           Start the web server in debug mode

$ superset runserver -d -p 9099
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Starting Superset server in DEBUG mode
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

2017-11-07 19:49:57,031:INFO:werkzeug: * Running on http://0.0.0.0:9099/ (Press CTRL+C to quit)
2017-11-07 19:49:57,032:INFO:werkzeug: * Restarting with stat
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Starting Superset server in DEBUG mode
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

2017-11-07 19:49:59,518:WARNING:werkzeug: * Debugger is active!
2017-11-07 19:49:59,538:INFO:werkzeug: * Debugger PIN: 423-263-045
```

And please check the following note about using development web server.
http://superset.apache.org/installation.html#a-proper-wsgi-http-server
