### ISSUE TITLE
Show preview of data upon selecting a table. SQL Lab.

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/caravel#1244]

**Comment by woel0007** [comment]
Is the intention of this issue meant to be a feature limited only to SQL Lab?  

I've got a working version of a data preview for Druid Datasources - would this be of interested to the product?  The code needs a little polish, but I'd be happy to push it back if there's interest.

**Comment by bkyryliuk** [comment]
@woel0007 - yep this FR is for SQL Lab.
Sounds like an interesting feature, could you please share a screenshot ?

**Comment by bkyryliuk** [comment]
@mistercrunch implemented it.
