### ISSUE TITLE
0.11.0 extra dependency for ubuntu 15

### ISSUE THREAD

**Issue by samempson** [airbnb/caravel#1271]
Following the standard installation instructions, I get the fatal error below when running ```pip install caravel``` for version 0.11.0. The solution was to run the below, so may need adding to the list of dependencies in the docs ```sudo apt-get install libsasl2-dev libldap2-dev``` (suspect it was the libsasl2-dev one that fixed it)

Cheers,
Sam

---

In file included from sasl/saslwrapper.cpp:254:0:

sasl/saslwrapper.h:22:23: fatal error: sasl/sasl.h: No such file or directory

 #include <sasl/sasl.h>

compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by xrmx** [comment]
Fixed in a8a16900e7497083f14de3b6dc50063f845401b7, dup of #1250
