### ISSUE TITLE
Loaded examples don't have permissions 

### ISSUE THREAD

**Issue by samempson** [airbnb/caravel#1272]
When following the [standard install instructions](http://airbnb.io/caravel/installation.html), example datasets are installed. If a new user is assigned the role 'Alpha', they are able to view the database, tables, slices and dashboards. If a new role is created by duplicating the Alpha role (e.g. 'Alpha_copy'), and the new user assigned this role instead, then the slices and dashboards are no longer visible, despite having an identical permission set. Is this expected?

A related issue is that if the 'Public' role is assigned the 'all datasource access on all_datasource_access' permission, and a user assigned both Gamma and Public roles, they also cannot see the slices and dashboards, as may be expected - as they can't seem to see the tables. The [security](http://airbnb.io/caravel/security.html) page has permissions such as 'datasource access on [main].[birth_names](id:3)', which aren't available to me in the permissions auto-complete box after a clean install. Is this a bug or are the permission sets created before the tables in the install routine? If so how do you create permission properties for tables?

Thanks,
Sam

**Comment by xrmx** [comment]
Alpha and Admin are special roles, some code rely on the exact names.

Permissions for tables iirc are created when you save the table, database, whatever. Also it does not make any sense to give a user more than one the default roles as Public and Gamma together. Usually you create other roles with specific permissions and compose what you need.

**Comment by samempson** [comment]
OK. Having recreated the sankey table from the example dataset, a new permission has appeared, so I can grant access to it via the public role. Might be worth stating this in the docs, as out of the box, you cannot assign permissions to the tables from the example data.

Re multiple roles, [the security docs](http://airbnb.io/caravel/security.html) give an example of using a 'finance' role to give access to a specific dataset/table to some users. This makes a lot of sense to me, so admin/alpha/gamma roles are used to say what a user can do, and custom roles can be used to allow access to specific datasets.

**Comment by xrmx** [comment]
PR clarifying the docs much appreciated! :)

Re multiple roles, what i was trying to say is choose one of the default caravel roles and add your specific roles on top of them.

**Comment by mistercrunch** [comment]
I changed the installation instructions to do `caravel init` after `caravel load_examples` and that takes care of it
