### ISSUE TITLE
Version of node/npm/...?

### ISSUE THREAD

**Issue by ecesena** [airbnb/caravel#1293]
Hi, could anyone share a working config version of node/npm and possibly other related tools?
I think having it in CONTRIBUTING.md would be a good idea (like a suggestion, not mandatory).

I'm trying to upgrade from 0.10 to 0.11 and now `npm run prod` gets stuck at "80% additional chunk assets"... it's not a Caravel issue, I'm sure, but finding the right intersection of tools is a bit frustrating.

For the record, I have node v4.4.5, npm v3.9.3, and I've removed node_modules and re-run "npm install".

Thank you!

**Comment by prokh** [comment]
It works with 6.6.0 and npm v3.10.8. You can install the node module n with npm. Then update node with n and npm with npm install npm@latest -g.

**Comment by ecesena** [comment]
Awesome, thank you!

**Comment by xrmx** [comment]
@ecesena if npm is not new enough you'll get errors, if something is buggy we can't do much am afraid.
