### ISSUE TITLE
required polyfills for older browser support

### ISSUE THREAD

**Issue by gschrader** [airbnb/caravel#1302]
I found that adding `Object.assign` and `Array.prototype.includes` polyfills I was able to get an older browser to work that I need to be able to support. This might also address #1201 I haven't had a chance to test IE yet.

I'm wondering if this is something that should be added to the project or if I should just patch my installs.  I can raise a PR, I'm just not sure the best place to add them. Any thoughts?

**Comment by xrmx** [comment]
A PR would be appreciated of course, regarding the place to add them i suppose just add them as npm dependencies like the others js libraries and require them where needed?

**Comment by gschrader** [comment]
I think polyfills have to be global but I'll give it a try.

**Comment by ascott** [comment]
@gschrader what browser are you trying to support?

**Comment by gschrader** [comment]
@ascott It's the javafx webview browser, which I believe is based on an old version of webkit.

**Comment by gschrader** [comment]
I can confirm #1323 works with the javafx webview, thanks again @ascott
