### ISSUE TITLE
Copy Query url shortener

### ISSUE THREAD

**Issue by vera-liu** [airbnb/caravel#1310]
Use a url shortener for sharing query functionality, without exposing userId, dbId and sql query in url.
related: https://github.com/airbnb/caravel/issues/1052

**Comment by bkyryliuk** [comment]
I meant a bit different thing. For the external product to be able to open a query in SQL Lab it would be challenging to know the user_id and database_id:
* User ID is already known in state, that should not be parameter, and when different user open's the query up - it should be tied to his account.
* Database name  should be sufficient for us to look up the database id 
* Schema may be needed as user can create the query using database and schema.

**Comment by vera-liu** [comment]
@bogdan Ahh gotcha,  created another issue https://github.com/airbnb/caravel/issues/1328  will work on it

**Comment by vera-liu** [comment]
@bkyryliuk  Actually after looking at this, userID is not part of the copy query link, and schema is already in the link, so the only thing left to do here is changing dbId to dbname

**Comment by bkyryliuk** [comment]
@vera-liu  - great news !

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1314

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1314
