### ISSUE TITLE
Cannot view dashboards as an anonymous user in 0.11

### ISSUE THREAD

**Issue by Rapsutin** [airbnb/caravel#1319]
When viewing the dashboard
`dash_edit_perm = check_ownership(dash, raise_if_false=False)`
https://github.com/airbnb/caravel/blob/master/caravel/views.py#L1647 
is called

and inside check_ownership
`orig_obj.created_by.username == g.user.username):`
https://github.com/airbnb/caravel/blob/master/caravel/views.py#L148 

is called, but an anonymous user has no username so it raises an exception.

**Comment by xrmx** [comment]
Care to cook a patch? Adding this at the top of the function should do it:

```
 if g.user.is_anonymous():
    return False
```

**Comment by Rapsutin** [comment]
I'll try.

**Comment by Rapsutin** [comment]
The change is breaking some tests. I wrote a test for the bug and it seems to work fine, but some other tests are failing now. Looking into it a bit later.

**Comment by Rapsutin** [comment]
#1320

**Comment by xrmx** [comment]
Fixed in 1e6e144d24da38aef0d306889dc3b8f962ca4b32 . Thanks again!
