### ISSUE TITLE
js_bulid error

### ISSUE THREAD

**Issue by xiefan46** [airbnb/caravel#1324]
> caravel@0.1.0 test /home/xiefan/caravel/caravel/assets
> echo "Error: no test specified" && exit 1

Error: no test specified

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! caravel@0.1.0 test: `echo "Error: no test specified" && exit 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caravel@0.1.0 test script 'echo "Error: no test specified" && exit 1'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the caravel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo "Error: no test specified" && exit 1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs caravel
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls caravel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xiefan/caravel/caravel/assets/npm-debug.log

**Comment by ascott** [comment]
what version of node and npm to you have installed?

**Comment by xiefan46** [comment]
node v4.2.6  
npm  v3.5.2

**Comment by ascott** [comment]
we use node 6.2.2 and npm 3.9.5.

i updated contributing.md with these details.

https://github.com/airbnb/caravel/pull/1344

**Comment by ascott** [comment]
we also haven't found any issues with node>=5.10 and npm>=3.9.

**Comment by tangshan-risk** [comment]
when I built my node_modules, I got the following tips. I don't know how can resolve it:
ERROR in ./~/_css-loader@0.28.3@css-loader!./~/_less-loader@4.0.3@less-loader/dist!./stylesheets/react-select/select.less
Module build failed: 

        &:hover {
                box-shadow: @select-input-hover-box-shadow;
            ^
Variable @select-input-hover-box-shadow is undefined
      in /Users/Alex/Desktop/superset/superset/assets/node_modules/_react-select@1.0.0-rc.5@react-select/less/control.less (line 64, column 14)
 @ ./stylesheets/react-select/select.less 4:14-162
 @ ./javascripts/css-theme.js

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! superset@0.17.6 build: `NODE_ENV=production webpack --colors --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the superset@0.17.6 build script 'NODE_ENV=production webpack --colors --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --colors --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Alex/Desktop/superset/superset/assets/npm-debug.log

**Comment by xrmx** [comment]
@tangshan-risk don't hijack closed issues please.

**Comment by claireliumo** [comment]
@ascott I have tried with node >=6 and npm >=3.9 on windows 7, but still got this error. is there any other suggestion?

**Comment by mistercrunch** [comment]
Install a linux VM
