### ISSUE TITLE
Unable to run "Make your own build" due to npm dependency error

### ISSUE THREAD

**Issue by jasonshah** [airbnb/caravel#1331]
Hi,
I am attempting to follow the ["Make your own build"](http://airbnb.io/caravel/installation.html#making-your-own-build) section to build from source.
When I run `npm install`, it fails with:

	$ npm install
	npm WARN package.json caravel@0.11.0 No README data
	npm WARN package.json Dependency 'style-loader' exists in both dependencies and devDependencies, using 'style-loader@^0.13.0' from dependencies
	npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
	npm ERR! Darwin 14.5.0
	npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install"
	npm ERR! node v4.2.1
	npm ERR! npm  v2.14.7
	npm ERR! code ETARGET

	npm ERR! notarget No compatible version found: victory@'>=0.12.1 <0.13.0'
	npm ERR! notarget Valid install targets:
	npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.3.0","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1","0.6.0","0.6.1"]
	npm ERR! notarget 
	npm ERR! notarget This is most likely not a problem with npm itself.
	npm ERR! notarget In most cases you or one of your dependencies are requesting
	npm ERR! notarget a package version that doesn't exist.
	npm ERR! notarget 
	npm ERR! notarget It was specified as a dependency of 'caravel'
	npm ERR! notarget 

	npm ERR! Please include the following file with any support request:

And my npm-debug.log is attached.

[npm-debug.log](https://github.com/airbnb/caravel/files/525545/npm-debug.log.txt)

**Comment by prokh** [comment]
You could first try to update npm and node: "It works with node v6.6.0 and npm v3.10.8. You can install the node module n with npm. Then update node with n and npm with npm install npm@latest -g. "

**Comment by xrmx** [comment]
@jasonshah could you please try to remove node_modules and try again?

**Comment by jasonshah** [comment]
@prokh 's solution worked for this issue. Unfortunately I don't know how to actually run the server now that it's built. :/
