### ISSUE TITLE
[explore-v2] issues with wrapping existing viz's in V2

### ISSUE THREAD

**Issue by ascott** [airbnb/caravel#1341]
- [x] table type has a dependency on slice.d3format:
  ![screenshot 2016-10-13 14 57 07](https://cloud.githubusercontent.com/assets/130878/19368554/5cbd8cee-9155-11e6-9c4e-b784173bf43f.png)
  ![screenshot 2016-10-13 14 57 19](https://cloud.githubusercontent.com/assets/130878/19368555/5ccf870a-9155-11e6-8363-596dfa85b170.png)
- [x] big number with trendline doesn't show big number
  ![screenshot 2016-10-13 14 41 53](https://cloud.githubusercontent.com/assets/130878/19368099/437f2c58-9153-11e6-8eee-3cedea901a06.png)
- [x] big number doesn't render big number:
  ![screenshot 2016-10-13 14 42 55](https://cloud.githubusercontent.com/assets/130878/19368134/6ccb781e-9153-11e6-95df-113f42f63068.png)
  ![screenshot 2016-10-13 14 43 07](https://cloud.githubusercontent.com/assets/130878/19368133/6cc44fda-9153-11e6-9fa6-7f4e2e19e619.png)
- [x] directed force layout looks a little different.... 
  ![screenshot 2016-10-13 14 44 39](https://cloud.githubusercontent.com/assets/130878/19368178/a94075a6-9153-11e6-9b4e-57ee74ed8c7a.png)
  ![screenshot 2016-10-13 14 44 54](https://cloud.githubusercontent.com/assets/130878/19368179/a94b6c0e-9153-11e6-84ee-13e4d03ac33c.png)
- [x] region filter is broken on /explore/
  ![screenshot 2016-10-13 14 46 20](https://cloud.githubusercontent.com/assets/130878/19368207/d7809c84-9153-11e6-8a5d-8e79f9252440.png)
- [x] /exploerV2/ has dependency on `slice.getFilters`
  ![screenshot 2016-10-13 14 47 07](https://cloud.githubusercontent.com/assets/130878/19368236/fd2bb36a-9153-11e6-893b-27e4fcff02f1.png)
- [x] heat map has some layout issues:
  ![screenshot 2016-10-13 14 48 12](https://cloud.githubusercontent.com/assets/130878/19368284/27d0cd3a-9154-11e6-9ab0-f546dd37ff88.png)
  ![screenshot 2016-10-13 14 48 28](https://cloud.githubusercontent.com/assets/130878/19368285/27d13bd0-9154-11e6-8355-b1d37af83ad7.png)
- [x] pivot table type throws an error in V2:
  ![screenshot 2016-10-13 14 52 57](https://cloud.githubusercontent.com/assets/130878/19368444/dc1cbcf4-9154-11e6-992b-7012e7075895.png)
  ![screenshot 2016-10-13 14 53 24](https://cloud.githubusercontent.com/assets/130878/19368445/dc1cfc46-9154-11e6-8d36-77d3392a6024.png)
- [x] sankey as layout/visual issues in V2:
  ![screenshot 2016-10-13 14 54 17](https://cloud.githubusercontent.com/assets/130878/19368476/03186754-9155-11e6-9131-247a05f0611a.png)
  ![screenshot 2016-10-13 14 54 36](https://cloud.githubusercontent.com/assets/130878/19368477/0318c4b0-9155-11e6-8c1b-649350c645c8.png)
- [x] sunburst has layout/visual issues in V2:
  ![screenshot 2016-10-13 14 55 16](https://cloud.githubusercontent.com/assets/130878/19368525/39994c12-9155-11e6-98a4-22d096b89632.png)
  ![screenshot 2016-10-13 14 55 59](https://cloud.githubusercontent.com/assets/130878/19368526/3999c1e2-9155-11e6-8d7b-29986dab8bb3.png)
- [x] world_map type throws an error in V2:
  ![screenshot 2016-10-13 14 58 35](https://cloud.githubusercontent.com/assets/130878/19368601/99a18688-9155-11e6-9431-0e7a161c33d5.png)
  ![screenshot 2016-10-13 14 58 49](https://cloud.githubusercontent.com/assets/130878/19368600/99a0d332-9155-11e6-9930-d5c1e3008e63.png)

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1361
https://github.com/airbnb/caravel/pull/1360
https://github.com/airbnb/caravel/pull/1359
https://github.com/airbnb/caravel/pull/1353

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1432

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1443
