### ISSUE TITLE
DRUID_TZ config param not working?

### ISSUE THREAD

**Issue by DaimonPl** [airbnb/caravel#1376]
As can be seen in https://github.com/airbnb/caravel/blob/master/caravel/config.py:

```
# Druid query timezone
# tz.tzutc() : Using utc timezone
# tz.tzlocal() : Using local timezone
# other tz can be overridden by providing a local_config
DRUID_IS_ACTIVE = True
DRUID_TZ = tz.tzutc()
```

I was expecting that changing this param would change global TZ to defined one.

I tried setting `DRUID_TZ = tz.tzstr('Europe/Warsaw')` but it looks that there's no effect on queries/displayed data - all times are still UTC

**Comment by xrmx** [comment]
Closing as dup of #1369
