### ISSUE TITLE
Is adding new viz different now?

### ISSUE THREAD

**Issue by github35** [airbnb/caravel#1406]
@mistercrunch

I like Caravel a lot and am trying to adding other nvd3 viz into it. I found below examples, and followed, but it didn't work -- I got an error message from explore.js when I selected the new viz in creating slice. I wonder if the process is different now and there are other files I need to change? Many thanks!

https://github.com/airbnb/caravel/pulls?q=is%3Apr+label%3Aexample+is%3Aclosed

**Comment by github35** [comment]
The detailed error message is as below:
explore.0.11.0.entry.js -- s.default[t.form_data.viz_type] is not a function

**Comment by xrmx** [comment]
Do you have any backtrace in the caravel python app logs? Have you added your class to caravel.viz.viz_types_list ?

**Comment by github35** [comment]
Yes I did and I could select the new Viz from the drop down list, but it just didn't work . I also added in ../../visualizations/main.js vizMap.

**Comment by github35** [comment]
I guess I know the reason... Thank you:)

**Comment by github35** [comment]
The problem is the JS I added is not included in explore.0.11.0.entry.js. Is there anything I need to do to generate new explore.0.11.0.entry.js? Thank you for helping.

**Comment by ascott** [comment]
@github35 are you using `npm run dev` to build client side assets/js in development?

**Comment by github35** [comment]
@ascott There seems to be a lot issues of building on Windows system. I will further explore any other possibilities. Thank you! Caravel is amazing. It will be great if we can customize visualization from browser, e.g. http://echarts.baidu.com/demo.html#heatmap-cartesian.

**Comment by xrmx** [comment]
@github35 can we close this?

**Comment by github35** [comment]
@xrmx Sure. Thank you!
