### ISSUE TITLE
Updating any field for a database entry can reset DB password to XXXXXXXXXX

### ISSUE THREAD

**Issue by supertetelman** [airbnb/caravel#1431]
I had a database setup and working with a few dashboards.

After updating the dashboard by enabling the 'Expose in SQL Lab' check box all my dashboards stopped working due to an invalid access error. (On this page: http://localhost:8088/databaseview/edit/2)

I believe that the 'SQLAlchemy URI' field showed XXXXXXXXXX for security reasons, however upon saving any changes to the database that value overwrites the actual password.

This page should either prompt for the user to re-type the password or not update fields that have not been changed by the user.

I'm not sure if this would be considered a bug or an improvement but it took me a little too long to debug on my end.

I'm currently running/browsing caravel on Windows, using mysql, and am able to reproduce this fairly easily.

**Comment by xrmx** [comment]
Which version is this?

**Comment by supertetelman** [comment]
Caravel 0.11.0

**Comment by bkyryliuk** [comment]
I couldn't replicate the issue on master. It should be solved with new release.

<img width="1244" alt="screen shot 2016-10-28 at 11 14 51 am" src="https://cloud.githubusercontent.com/assets/5727938/19817281/d0dd748a-9cff-11e6-99cb-f9d196a07d6b.png">

**Comment by mistercrunch** [comment]
I released 0.12.0, you can install that and let confirm the issue is fixed.
