### ISSUE TITLE
How about pagination in table view

### ISSUE THREAD

**Issue by kylozw** [airbnb/caravel#1433]
Now I can only see the first 50 records in table view Choosing 50 limit.
There's no way to see the next 50 records. I can choose 100 limit to get more records, but more records more data, and the page could break down.
So I think the pagination is needed.

**Comment by ascott** [comment]
thanks for the report @kylozw. we have another issue related to this https://github.com/airbnb/caravel/issues/1433

**Comment by kylozw** [comment]
@ascott, did you type wrong with the related issue's id? Which one I should watch?

**Comment by karthikbala** [comment]
any update on this
