### ISSUE TITLE
Query that runs in Airpal hangs in SQL Lab

### ISSUE THREAD

**Issue by jefffeng** [airbnb/caravel#1437]
The following query runs in 18 seconds in Airpal but hangs for 1.5 hours+ in SQL Lab:

SELECT a.ds, dau, overall_wau
FROM meta.dim_data_products_cube a
LEFT JOIN (
    SELECT ds, dau as overall_wau
    FROM meta.dim_data_products_cube 
    WHERE grouping__id = 0
) b ON a.ds = b.ds
WHERE grouping__id = 4

<img width="1255" alt="screen shot 2016-10-26 at 7 47 33 am" src="https://cloud.githubusercontent.com/assets/18297825/19731428/2c33bf4c-9b52-11e6-9057-307d4adedea3.png">
<img width="1722" alt="screen shot 2016-10-26 at 7 53 33 am" src="https://cloud.githubusercontent.com/assets/18297825/19731429/2c3792f2-9b52-11e6-9feb-339d165aeae2.png">

**Comment by bkyryliuk** [comment]
can't reproduce, query works on both prod and master.
Looks like it was transient error.
