### ISSUE TITLE
Dynamic Filter Issue

### ISSUE THREAD

**Issue by sid88in** [airbnb/caravel#144]
when I add 2 separate dynamic filters on the dashboard with the same data source. So lets say they are filters X and Y. When I select a dimension in X and a dimension in Y simultaneously - I notice that the labels/values of filter Y gets changed to filter X and filter X's labels/values disappears.

**Comment by gbrian** [comment]
Hi,
I'm adding a `getFilter` to fix this issue but on my way I've found that `table` visualization acts as a filter as well.
That forces me to change the way filters are saved. 
@mistercrunch Is there any reason to use `slice_id` when storing filters ? I'm thinking on storing filters by `column` instead. In this way doesn't matter where there filter comes from. Of course you will not be able to show and filter two different columns with same name (different datasources).

Thanks

**Comment by sid88in** [comment]
great! Let me know if you need any help and I can chip in.
