### ISSUE TITLE
Totals do not show up on tooltips for stacked line charts

### ISSUE THREAD

**Issue by jefffeng** [airbnb/caravel#1440]
When viewing a stacked line chart in Caravel, the totals do not show up in the tooltips.
Chart: https://panoramix.d.musta.ch/caravel/dashboard/meta/

### Caravel version
https://panoramix.d.musta.ch/

### Expected results
Tooltips should show up for all points in time

### Actual results
![screen shot 2016-10-26 at 3 57 34 pm](https://cloud.githubusercontent.com/assets/18297825/19748207/2d001428-9b95-11e6-8424-991fa971794d.png)

**Comment by vera-liu** [comment]
This was due to y_axis_format set to d while avg wau could be a float number. solved by switching y_axis_format
