### ISSUE TITLE
Showing table metadata should sort metadata in alphabetical order

### ISSUE THREAD

**Issue by jefffeng** [airbnb/caravel#1444]
When displaying the table metadata, SQL Lab should automatically sort the metadata in alphabetical order:

Current state:
<img width="442" alt="screen shot 2016-10-27 at 6 20 59 am" src="https://cloud.githubusercontent.com/assets/18297825/19768756/a53629dc-9c0d-11e6-8635-1179598a251c.png">

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1464
