### ISSUE TITLE
0.12.0 artifact missing on pypi.python.org/simple

### ISSUE THREAD

**Issue by amancevice** [airbnb/caravel#1481]
The artifact for v0.12.0 seems to be missing from [https://pypi.python.org/simple/caravel/](https://pypi.python.org/simple/caravel/), even though v0.12.0 is defined at [https://pypi.python.org/pypi/caravel/](https://pypi.python.org/pypi/caravel/).

Not a huge issue, but it causes `pip install caravel==0.12.0` to fail.

**Comment by mistercrunch** [comment]
Oh interesting, thanks for reporting this, I'll try to fix this.

**Comment by mistercrunch** [comment]
Ok should be fixed now.
