### ISSUE TITLE
Visualize flow is broken since results in SouthPane

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#1553]

**Comment by vera-liu** [comment]
Sorry I forgot to exclude query results from storing result data in local state, [https://github.com/airbnb/caravel/pull/1552](url) should solve it.

**Comment by mistercrunch** [comment]
VisualizeModal needs the column information, but not the data, perhaps ResultSet should only cache `results.data`, not the whole `results` object that also contains the column info

**Comment by vera-liu** [comment]
Since we don't want user to re-run query everytime one refreshes the page, I think best approach would be not storing query result data to local state, only do it for data preview of tables.
