### ISSUE TITLE
Chrome javascript debugger fails setting breakpoints

### ISSUE THREAD

**Issue by gbrian** [airbnb/caravel#174]
Hi,

I'm having problems while debugging js code on chrome, looks like it fails detecting where to place the breakpoint.
I've found some posts related to webpack and line numbers error, did you have same issue?

Thanks

**Comment by williaster** [comment]
Are you seeing this with production or dev environment? Currently I don't think we include the source maps for production but you should see them in dev.

**Comment by mistercrunch** [comment]
Oh the source map may ship with the python package, should I remove them?

**Comment by gbrian** [comment]
Dev environment.
I'm using Anaconda2 as python framework and debugging with PyCharm.
On an another console I have `npm run dev` running.
Is that correct?

Thanks
