### ISSUE TITLE
Responsive gridster

### ISSUE THREAD

**Issue by gbrian** [airbnb/caravel#177]
Hi there,

Looking for a responsive gridster version found: https://github.com/dsmorse/gridster.js
What do you think about? BTW I'm working on adding maximize option to the widgets, is this already on the roadmap?

Thanks.

**Comment by mistercrunch** [comment]
By responsive do you mean as in "responsive design" or by a "more active fork"?

**Comment by gbrian** [comment]
Ops, sorry. 

I'm talking about design. 
I'd like to define dashboard once and be able to consume it from many devices.
At least, I guess, it will be enough if the dashboard can be manged by desktop and tablet.
Form mobile I prefer to define specific ones.

About "active fork" I have found many comments about gridster been dormant, the dsmorse  fork looks more active.

Thanks.
