### ISSUE TITLE
Data cache

### ISSUE THREAD

**Issue by gbrian** [airbnb/caravel#179]
Hi,

I'll need to cache some data to avoid querying DB continuously. Any preferred approach ?
Currently I'm thinking on adding basic caching. It will include an new attribute for the slice- "Time to live", "Cache time" or similar with 0 meaning no cache-. We'll need a way to invalidate cache as well ;)

What about something quite basic using https://pypi.python.org/pypi/pyfscache/ ?
We can use it at class method **BaseViz::get_df** level, don't you?

Thanks

**Comment by mistercrunch** [comment]
I've used flask-cache before, works as a decorator on a web view. Query level might be more targeted. 

I'd like for it to be parametrizable at the application / DB / dataset / dashboard / slice level, where it goes up the chain of defaults with the right fallback rule. It needs to support a wide variety of backends (memcache, redis, filesystem, ..,).

The UI should also be upfront about how old the cache is (icon with tooltip, `as of 00:03:22 ago`)

**Comment by gbrian** [comment]
Agree,

So a cache wrapper we can extend later with multiple providers, will it do the job?. 
What do you mean with "Query level" I was looking for a single point where to apply the cache and I landed at **BaseViz::get_df**. Maybe do you prefer it to managed per datasource ?

Nice idea about adding the info in a tooltip.

**Comment by gbrian** [comment]
HI @mistercrunch,
I guess https://github.com/airbnb/caravel/pull/188 answers this request, right?

**Comment by mistercrunch** [comment]
Yeah we're done here :)
