### ISSUE TITLE
Error: make_declarative_base() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by agiap** [airbnb/caravel#220]
I installed caravel on Windows 10 (Python 2.7) and got the following error message after following the installation steps: 

C:\Anaconda2\Scripts>fabmanager create-admin --app caravel
Username [admin]: wizzz
User first name [admin]: Wiii
User last name [user]: Zzzz
Email [admin@fab.org]: wizzz123@gmail.com
Password:
Repeat for confirmation:
Was unable to import caravel Error: make_declarative_base() takes exactly 1 argument (2 given)

Thanks,

**Comment by dacort** [comment]
Looks like for some reason, installing caravel from scratch using pip installs the wrong version of flask-sqlalchemy. 

I found [this bug](https://github.com/dpgaspar/Flask-AppBuilder/issues/263) on the Flask-AppBuilder project referencing the same error. Even though caravel has flask-sqlalchemy [pinned at 2.0](https://github.com/airbnb/caravel/blob/1c44f34490666ae2eb262b0b454dcc961b9512b1/setup.py#L22), 2.1 got installed for me.

You can work around it by installing flask-sqlalchemy v2.0 first:
```bash
pip uninstall flask-sqlalchemy
pip install flask-sqlalchemy==2.0
```

After doing that, the create-admin step worked fine.

**Comment by mistercrunch** [comment]
Diamond dependencies? I've seen that bug before too. I'm not sure where the `2.1` gets picked up from. I didn't see it when digging in using the `pipdeptree` utility

**Comment by mistercrunch** [comment]
I have no way of testing things on windows though, so I'm surprised it even works. I think Travis (our build system) can do windows build. It would be nice if someone added windows to the build matrix.

**Comment by dacort** [comment]
My build was on Ubuntu 14.04.4 LTS, experienced the same issue.

**Comment by xrmx** [comment]
Closing after b48101ca51da8bd07608ccdbd9912efb2000cd0b

**Comment by bcambel** [comment]
I am having the same issue with Python 2.7 on Ubuntu 16. Here is my frozen pip

```
alembic==0.8.8
amqp==1.4.9
anyjson==0.3.3
Babel==2.3.4
billiard==3.3.0.23
celery==3.1.23
cffi==1.9.1
click==6.6
colorama==0.3.7
cryptography==1.5.3
enum34==1.1.6
Flask==0.11.1
Flask-AppBuilder==1.8.1
Flask-Babel==0.11.1
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Migrate==1.5.1
Flask-OpenID==1.2.5
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-Testing==0.5.0
Flask-WTF==0.13.1
future==0.16.0
gunicorn==19.6.0
humanize==0.5.1
idna==2.1
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.8
kombu==3.0.37
Mako==1.0.6
Markdown==2.6.6
MarkupSafe==0.23
numpy==1.12.0b1
pandas==0.18.1
parsedatetime==2.0
pyasn1==0.1.9
pycparser==2.17
pydruid==0.3.0
PyHive==0.2.1
python-dateutil==2.5.3
python-editor==1.0.2
python-openid==2.2.5
pytz==2016.7
requests==2.10.0
sasl==0.2.1
simplejson==3.8.2
six==1.10.0
SQLAlchemy==1.0.13
SQLAlchemy-Utils==0.32.7
sqlparse==0.1.19
superset==0.13.2
thrift==0.9.3
thrift-sasl==0.2.1
Werkzeug==0.11.10
WTForms==2.1
```
