### ISSUE TITLE
Static assets not resolving

### ISSUE THREAD

**Issue by bertomartin** [airbnb/caravel#226]
Though I'm new to the Flask project setup, I think I have everything setup properly. When I run the app, I don't get the css theme due to being unable to reference the file: /static/assets/javascripts/dist/css-theme.entry.js. This file does exist in that location, but the browser can't seem to resolve it. Any help highly appreciated.

**Comment by gbrian** [comment]
Hi,
Have you tried running `npm install` and `npm run dev` on **assests** folder ?

**Comment by mistercrunch** [comment]
Did you follow the instructions here?
https://github.com/airbnb/caravel/blob/master/CONTRIBUTING.md

**Comment by bertomartin** [comment]
Yes, I ran both. It's really strange as the file it's complaining about exist in the directory as expected. The link is hardcoded in the codebase to: '/static/assets/javascripts/dist/css-theme.entry.js'. This file does exist in the given location.

**Comment by bertomartin** [comment]
I went to the file: basic.html, deleted it's content, and re-run the application. It still worked, which is unexpected. So, there's something that I'm missing. Modifying any file has no effect. This is probably just something fundamental to flask that I'm missing. Any help appreciated.

**Comment by bertomartin** [comment]
Do I need to use the command: caravel runserver -d to run the app or can I run it some other way to make sure it's interpreting the source code?

**Comment by mistercrunch** [comment]
Looks like you're running multiple installs
`pip uninstall caravel`
`python setup.py develop`

**Comment by bertomartin** [comment]
@mistercrunch thank you. I ended up running it from the build directory, but good to know this.

**Comment by ivdelchev** [comment]
I actually have the same problem and not running multiple installs for sure. The javascripts/dist/ files are there after running 

    npm run dev 

in the assets folder and yet the response back for anything in the assets/dist/ is a 404. 
@bertomartin How did you run from the build directory?
