### ISSUE TITLE
Unable to install Caravel on Mac

### ISSUE THREAD

**Issue by deepujain** [airbnb/caravel#228]
$ sudo pip install caravel
The directory '/Users/dvasthimal/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/dvasthimal/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting caravel
  Downloading caravel-0.8.4.tar.gz (26.4MB)
    100% |████████████████████████████████| 26.4MB 60kB/s 
Requirement already satisfied (use --upgrade to upgrade): alembic<0.9.0,>=0.8.5 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): cryptography<2.0.0,>=1.1.1 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-appbuilder<2.0.0,>=1.6.0 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-cache<0.14.0,>=0.13.1 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-migrate<2.0.0,>=1.5.1 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-script<3.0.0,>=2.0.5 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask-testing<0.5.0,>=0.4.2 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): flask<1.0.0,>=0.10.1 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): humanize<0.6.0,>=0.5.1 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): gunicorn<20.0.0,>=19.3.0 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): markdown<3.0.0,>=2.6.2 in /Library/Python/2.7/site-packages (from caravel)
Collecting numpy<2,>=1.9 (from caravel)
  Downloading numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 403kB/s 
Collecting pandas<0.19.0,==0.18.0 (from caravel)
  Downloading pandas-0.18.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.1MB)
    100% |████████████████████████████████| 8.1MB 192kB/s 
Collecting parsedatetime==2.0.0 (from caravel)
  Downloading parsedatetime-2.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pydruid<0.3,>=0.2.2 in /Library/Python/2.7/site-packages (from caravel)
Collecting python-dateutil<3.0.0,>=2.4.2 (from caravel)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 4.8MB/s 
Requirement already satisfied (use --upgrade to upgrade): requests<3.0.0,>=2.7.0 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy<2.0.0,>=1.0.12 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy-utils<0.32.0,>=0.31.3 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): sqlparse<0.2.0,>=0.1.16 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): werkzeug<0.12.0,>=0.11.2 in /Library/Python/2.7/site-packages (from caravel)
Requirement already satisfied (use --upgrade to upgrade): Mako in /Library/Python/2.7/site-packages (from alembic<0.9.0,>=0.8.5->caravel)
Requirement already satisfied (use --upgrade to upgrade): python-editor>=0.3 in /Library/Python/2.7/site-packages (from alembic<0.9.0,>=0.8.5->caravel)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /Library/Python/2.7/site-packages (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /Library/Python/2.7/site-packages (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /Library/Python/2.7/site-packages (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /Library/Python/2.7/site-packages (from cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): click>=3.0 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Flask-BabelPkg>=0.9.4 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.2.11 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Flask-OpenID>=1.1.0 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Flask-SQLAlchemy==2.0 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF>=0.9.1 in /Library/Python/2.7/site-packages (from flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Library/Python/2.7/site-packages (from flask<1.0.0,>=0.10.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from flask<1.0.0,>=0.10.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas<0.19.0,==0.18.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /Library/Python/2.7/site-packages (from Mako->alembic<0.9.0,>=0.8.5->caravel)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Library/Python/2.7/site-packages (from cffi>=1.4.1->cryptography<2.0.0,>=1.1.1->caravel)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in /Library/Python/2.7/site-packages (from Flask-BabelPkg>=0.9.4->flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /Library/Python/2.7/site-packages (from Flask-BabelPkg>=0.9.4->flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): python-openid>=2.0 in /Library/Python/2.7/site-packages (from Flask-OpenID>=1.1.0->flask-appbuilder<2.0.0,>=1.6.0->caravel)
Requirement already satisfied (use --upgrade to upgrade): WTForms in /Library/Python/2.7/site-packages (from Flask-WTF>=0.9.1->flask-appbuilder<2.0.0,>=1.6.0->caravel)
Installing collected packages: numpy, python-dateutil, pandas, parsedatetime, caravel
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 726, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 746, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-UVCrCP-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'
$ 

Any suggestions ?

**Comment by mistercrunch** [comment]
`pip install numpy` first, then proceed with `pip install caravel`?

**Comment by dheerajrav** [comment]
@mistercrunch I am getting the same error. I tried installing/upgrading numpy and still the same error.

**Comment by bvirlet** [comment]
Try `sudo pip install caravel --ignore-installed numpy`

**Comment by bertomartin** [comment]
I was able to install it on my mac. I used anaconda to create virtual environments. I use conda install for some packages and pip for others.

**Comment by whiteboardmonk** [comment]
> Try sudo pip install caravel --ignore-installed numpy
@bvirlet This worked for me. Thanks!

**Comment by mistercrunch** [comment]
Awesome, I also just unpinned the `numpy` dependency in the package to let `pandas` dictate the version it needs. This will make the next release:
https://github.com/airbnb/caravel/pull/234

**Comment by deepujain** [comment]
sudo pip install caravel --ignore-installed numpy worked for me as well.
