### ISSUE TITLE
Make some dockerfile & docker-compose-file available

### ISSUE THREAD

**Issue by shouze** [airbnb/caravel#232]
To help testing this tool in a blink ;)

**Comment by mistercrunch** [comment]
Totally, I'd love if someone could contribute this!

**Comment by Grummfy** [comment]
here is something made in a quick & dirty way https://gist.github.com/Grummfy/c8bee043f167e456c43a78cc5018e399

just create files in a directory and
docker build .
run --rm -it --link site_dbsite_1:mysql -p 8088:8088 [image id]

**Comment by Grummfy** [comment]
don't hesitate to try it, it's working. In try with a mysql database ;)
