### ISSUE TITLE
Would be good to log tracebacks

### ISSUE THREAD

**Issue by davidascher** [airbnb/caravel#237]
When trying to add a new data source, I get this alert dialog:

![image](https://cloud.githubusercontent.com/assets/51278/14218420/e027a93e-f808-11e5-90ab-370ffd81c9b1.png)

Which is almost useful but not quite.  It'd be great if the full traceback was at least logged in the web console.

**Comment by mistercrunch** [comment]
Yeah the python stacktrace in the javascript popup isn't great...

**Comment by williaster** [comment]
Seems like it should be pretty easy to at least log the full trace in the console, I can add that soon.

**Comment by mistercrunch** [comment]
We're at a much better place now in terms in error message handling. Closing.
