### ISSUE TITLE
Any suggestion for how to pass in a cert for SSL access to a SQL database?

### ISSUE THREAD

**Issue by davidascher** [airbnb/caravel#239]
I'm trying to connect to a SQL database hosted on AWS RDS.

The Amazon docs explain that one needs to specify an AWS specific cert (http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html).

I've tried to monkey-patch the `create_engine` call in `views.py` to pass in `connect_args` with the value `{'sql': {'ca': '<path to the PEM file>'}}`. I've tried adding and trusting the AWS certificate to the Keychain (on OSX), but I'm still getting a fairly opaque `OperationalError: (pymysql.err.OperationalError) (1045, u"Access denied for user '<username>'@'<ip>' (using password: YES)")`

I'm using a URI for the database that looks like: `mysql+pymysql://username:password@host:3306/dbname`

Anyone else trying something similar?

**Comment by mistercrunch** [comment]
We use an RDS mysql as a backend and it works well. We're not doing anything special though there might be magic I'm unaware of on the boxes config...

**Comment by mistercrunch** [comment]
I think we'll need to add more options quickly to allow for all the "beyond the URI" settings of SqlAlchemy

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/249

**Comment by deniszgonjanin** [comment]
You can put in the path to your cert file right in the connection string, as url-params. Take a look at the PG docs: http://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING. Relevant settings are `sqlmode=require` and `sslcert=...path_to_cert`

Mind you, I haven't tested this with redshift yet, so, fingers crossed.

**Comment by deniszgonjanin** [comment]
This worked for me: In the database connection settings, you can use the Extra field (recently added I think by #249), which should look something like:
```
{
    "metadata_params": {},
    "engine_params": {
          "connect_args":{
              "sslmode":"require",
              "sslrootcert": "/path/to/my/pem"
        }
     }
}

```

**Comment by mistercrunch** [comment]
Nice! Thanks @deniszgonjanin, I just added a not in the docs:
https://github.com/airbnb/caravel/commit/3d1fc99353557aa42c14e760e01774fd624d7805
