### ISSUE TITLE
REST API client

### ISSUE THREAD

**Issue by hugo-pires** [airbnb/caravel#245]
Hello

Is it possible to use a REST API as a source for the widget?

Thank you

**Comment by mistercrunch** [comment]
What kind of REST service are you envisioning? The "Queryable" interface we use for Druid and SqlAlchemy sources is fairly complex and the service would have to implement it.

**Comment by tiffyangel89** [comment]
Do you know what a GUI is?

**Comment by hugo-pires** [comment]
I guess so. Could it help to answer my question?

**Comment by mistercrunch** [comment]
So the answer is: it's possible and you'd have to implement the Queryable interface in models.py, it's not trivial though.
