### ISSUE TITLE
Sankey diagram redraws on resize

### ISSUE THREAD

**Issue by andrewhn** [airbnb/caravel#254]
OS: Ubuntu 14.04.4 LTS Server
Extra system info: Exhibited in FF and chrome
To reproduce: Select "Sankey" chart with appropriate data, render chart, resize window, see two sankey diagrams

Having trouble setting up a dev environment so I can't test but it seems like the sankey render function should clear the element [before drawing](https://github.com/airbnb/caravel/blob/1b4e750b2aa111445703dca07fe929f7ffde38c9/caravel/assets/visualizations/sankey.js#L26), as the other d3 charts do (e.g. [here](https://github.com/airbnb/caravel/blob/1b4e750b2aa111445703dca07fe929f7ffde38c9/caravel/assets/visualizations/big_number.js#L27)).

**Comment by williaster** [comment]
you're totally right, thanks for the issue, will fix. 

for dev setup running `npm install && npm run dev` from the assets folder should work if you have node + npm installed?

**Comment by andrewhn** [comment]
Fixed with e3e8202
