### ISSUE TITLE
Sort distribution bar chart breakdowns

### ISSUE THREAD

**Issue by amancevice** [airbnb/caravel#260]
I have some data that looks like this:

Time | Type | Value
------------ | ------------- | -------------
2016-04-04T11:00:00Z | SomeTypeA | 1.00
2016-04-04T20:00:00Z | SomeTypeA | 0.50
2016-04-04T11:00:00Z | SomeTypeB | 3.00
2016-04-04T20:00:00Z | SomeTypeB | 1.50
&amp;c | &amp;c | &amp;c

I would like to chart the data in a distribution bar chart where the x-axis is `type` and the y-axis is `value`. Each bar in the breakdown should be the value in a time bucket. Ideally the bars in the breakdown would be ordered so that the leftmost bar in the breakdown is for the earliest time and the rightmost is for the most-recent time. However, when I chart this graph the bars are in a shuffled order, so it's hard to see how a breakdown progresses over time.

**Comment by mistercrunch** [comment]
Well consistency in the order of the bars within the group, across groups, is important too, so I'd vote for sorting within the group based on the total across groups. 

I think you could sort the columns here based on their total:
https://github.com/airbnb/caravel/blob/master/caravel/viz.py#L874

Interested in cutting a PR for it?

**Comment by amancevice** [comment]
I dropped a pdb on that line and inspected the DataFrame, but the columns look like they're in decent order:
```
        sum__val                                            
date     2016-03-30 2016-03-31 2016-04-01 2016-04-04 2016-04-05
Group A    2.400150   2.445438   2.352801   1.544879   0.993623
Group B    1.873592   1.634727   1.374716   0.927041   0.827326
Group C    0.000000   0.000000   0.000000   1.116525   4.070212
Group D    0.189162   0.362045   0.496035   0.114470  -0.101997
Group E    0.662968   0.602643   0.316768  -0.393172  -0.259234
Group F   -1.222564  -1.341251  -1.482262  -1.397279  -1.035352
```

So, I would expect the chart to plot each `Group` as a group of bars where the leftmost is for 3/30 and the rightmost is for 4/5 but I see this:
<img width="1010" alt="screen shot 2016-04-05 at 5 25 05 pm" src="https://cloud.githubusercontent.com/assets/157711/14298523/70b246ce-fb53-11e5-89ea-d5e7f70f8cce.png">

Notice how it's mostly in order, except 3/31 is the leftmost. This order appears to change from day to day, so I guess it's being hashed somewhere and the order is lost?

**Comment by amancevice** [comment]
I'd be happy to open a pull request for this, but I'm not sure where/how the data gets loaded into the page/widget

**Comment by amancevice** [comment]
@mistercrunch any advice?

**Comment by amancevice** [comment]
@mistercrunch nvm! I found what I needed to change: https://github.com/airbnb/caravel/pull/302
