### ISSUE TITLE
How do I join tables?

### ISSUE THREAD

**Issue by gavinjackson** [airbnb/caravel#261]
Great looking product, any ideas how I join tables together? Or do I need to create views in the SQL database?

**Comment by mistercrunch** [comment]
Views or summary tables. We're not planning on supporting the level of semantics allowing joins anytime soon.

**Comment by mahedi0244** [comment]
I created a view in the SQL database but I cannot access it and it doesn't show up in caravel. Any kind of help would be appreciated.

**Comment by arun-rangarajan** [comment]
@mahedi0244 - I faced the same issue after creating a VIEW using "DB Browser for SQLite" with a SQLite3 database. The view doesn't get written to the database file until you click on "Write Changes" button in "DB Browser for SQLite". Once you ensure the view is persisted in the database file, you can just import it as a table in Superset.
