### ISSUE TITLE
Widgets or embed dashboards

### ISSUE THREAD

**Issue by rrjanbiah** [airbnb/caravel#264]
As in Kibana, is there anyway to embed the dashboard in some 3rd party sites?

**Comment by mistercrunch** [comment]
There's a standalone mode for individual slices, but not for the dashboard currently. You could try hiding the menu in the dashboard's CSS and "iframing" it as is.

**Comment by Marco-Santoni** [comment]
Is the standalone mode for slices documented anywhere?

**Comment by mistercrunch** [comment]
Its a somewhat obvious button on the explore view.

**Comment by jwthomp** [comment]
Is there a way to do this without requiring authentication for viewers?

**Comment by wixosk** [comment]
How about this permission setting for Public role: [datasource access on [main].[birth_names](id:3), can explore on Caravel] ?

**Comment by wixosk** [comment]
Sorry, worked only on local for some reason. Otherwise it throws AttributeError: 'AnonymousUserMixin' object has no attribute 'username'. Any workaround?

**Comment by mistercrunch** [comment]
@jwthomp you'd have to allow set the flag to allow public users and add the datasource to the public role. As for embedding the dashboard, you can alter the CSS of the dashboard to hide the Caravel menu.

**Comment by XavierDeLapeyre** [comment]
Hello,
Has there been new changes to use the dashboards standalone since ?
Either as a widget or embeded?

**Comment by harshKotadiya** [comment]
You can embed Dashboard in an iframe, How? for that you have to add a parameter in iframe src URL: "&standalone=true" or if there are no '?' in URL then add ?standalone=true. it will disable menu bar from the dashboard.

**Comment by rrjanbiah** [comment]
Few related issues to watch #2571, #3201, #5692 & https://github.com/apache/incubator-superset/projects/4#card-12531556
