### ISSUE TITLE
CSS: Empty traceback error

### ISSUE THREAD

**Issue by lerrua** [airbnb/caravel#267]
![screen shot 2016-04-05 at 11 15 23 am](https://cloud.githubusercontent.com/assets/154603/14284904/dea768be-fb1f-11e5-9b47-f5f127fe11af.png)

The image above appears blank, but can see the exception message when you select the text.

**Comment by lerrua** [comment]
This printscreen is better.

![screen shot 2016-04-05 at 11 21 49 am](https://cloud.githubusercontent.com/assets/154603/14285137/b0d61330-fb20-11e5-9b99-66a4f407fe8f.png)

I'm using python 2.7 and pypi installation.

**Comment by mistercrunch** [comment]
is `id` not a date or datetime field? Looks like it may be an epoch?

The debugger not rendering well in our CSS context is a known issue that we're ok with, I guess it'd be nice to fix it. 

In production mode (if you turn off the debugger) you'd get a nicer looking error message.

**Comment by mistercrunch** [comment]
You could create an expression on that table that would cast id (if it's an epoch) to a datetime and use this field as a DATETIME. Of course this makes any indexes or partitioning on `id` useless to the optimizer.

**Comment by lerrua** [comment]
@mistercrunch thanks for the explanation. It's ok now with my expression using another column with datetime field.

This issue is just about the blank color traceback.

**Comment by mistercrunch** [comment]
Ok, I fixed the css.
