### ISSUE TITLE
Welcome page headers have byte prefix (ex: b'Creator')

### ISSUE THREAD

**Issue by Morgan243** [airbnb/caravel#268]
![caravel_b_prefix](https://cloud.githubusercontent.com/assets/1437221/14285263/d3f0093c-fb18-11e5-95ba-93f944f33d45.PNG)

This is running Caravel on Python 3.5.1 compiled from source on RHEL 6.7. I've reproduced this across multiple machines by following the install instructions in a new Python virtual environment.

**Comment by mistercrunch** [comment]
Oh interesting, I wonder where this is coming from. Do people see this in `3.4` too?

**Comment by andrewhn** [comment]
I see this in 3.4 too. Problem seems to be upstream in in flask appbuilder, in particular [this line](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/baseviews.py#L450). I'll raise it there.

**Comment by andrewhn** [comment]
See https://github.com/dpgaspar/Flask-AppBuilder/issues/312

**Comment by xrmx** [comment]
This has been fixed in flask-appbuilder, closing.
