### ISSUE TITLE
UnicodeEncodeError during Slice creation

### ISSUE THREAD

**Issue by lerrua** [airbnb/caravel#269]
Hi guys,

I'm trying to use Caravel in my local environment (osx, python 2.7, pypi installation) and got the following error because portuguese characters:

```
UnicodeEncodeError
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 9: ordinal not in range(128)

File "/Users/leroy/.virtualenvs/caravel/lib/python2.7/site-packages/caravel/views.py", line 510, in save
Open an interactive python shell in this framemsg = "Slice [{}] has been saved".format(slice_name)
```

![screen shot 2016-04-05 at 11 52 29 am](https://cloud.githubusercontent.com/assets/154603/14286290/ee48cab0-fb24-11e5-8ff2-247174167bd4.png)

**Comment by mistercrunch** [comment]
I'm thinking adding the `from __future__ import unicodeliterals` will help here, I'll try to get those all around. PR coming soon

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/288
