### ISSUE TITLE
 'openssl/e_os2.h' file not found while running python setup.py develop in MAC osx 10.11.3

### ISSUE THREAD

**Issue by wilson-wu** [airbnb/caravel#277]
This is the error message:

build/temp.macosx-10.11-intel-2.7/_openssl.c:423:10: fatal error: 
      'openssl/e_os2.h' file not found
#include <openssl/e_os2.h>
         ^
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1

**Comment by kingo55** [comment]
Have you satisfied the requirements here?: http://airbnb.io/caravel/installation.html

```
brew install pkg-config libffi openssl
env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography
```

**Comment by wilson-wu** [comment]
Thank you kingo55 for providing the link... that worked after resolving the dependences. 

I was following the instruction in 

https://github.com/airbnb/caravel/blob/master/CONTRIBUTING.md

for setting up development environment, I guess the dependency part is missed in that document.
