### ISSUE TITLE
How to load/save config from external sources

### ISSUE THREAD

**Issue by philippfrenzel** [airbnb/caravel#279]
Hi,

1st we love caravel and it's a pleasure to see how it works - we work since more than 12 years in BI and currently most of our projects are based upon qlikview (old version). Caravel makes a fresh and clean impression to us!

We wanna setup a new BI stack with caravel and for doing so, we would need to have the possibility to store and reload:

* connections
* tables
* slices
* dashboards 

from an external config - as we wanna run it within our CI process.
I haven't found anything in the docs, so hints are welcome!

Best Philipp

**Comment by mistercrunch** [comment]
I'm glad you enjoy the tool! Thanks for the feedback

So if you're in Python you can check out how things are done in here to load up the examples using the ORM:
https://github.com/airbnb/caravel/blob/master/caravel/data/__init__.py

Now if you want to do this from other languages, Flask Appbuilder exposes an awesome REST api to the underlying models. It's already active. Checkout:
https://flask-appbuilder.readthedocs.org/en/latest/quickhowto.html#rest-api

Each ORM model has its own api endpoint. So assuming your model list view is at `http://localhost:8088/slicemodelview/list/`, your api description endpoint is at `http://localhost:8088/slicemodelview/api`. You'll find json here that describes the schema and the endpoints for CRUD operations.

**Comment by philippfrenzel** [comment]
Thanks! That's a point to start ;) You should add this information to the docs! Would make sense - and while we work on it, we could send some pull requests to enhance it;)

Best Philipp
