### ISSUE TITLE
Document steps to upgrade to a new version

### ISSUE THREAD

**Issue by kingo55** [airbnb/caravel#280]
It would be nice to have some commands and general steps for active users to upgrade between versions of Caravel. Even if it's as simple as:

```
pip install caravel --upgrade
```

It seems there are breaking changes between versions in the DB/config. e.g. 0.8.5 and current master branch contents.

The Snowplow Analytics guys do a really good job of it on their blog posts:

http://snowplowanalytics.com/blog/2016/03/15/snowplow-r78-great-hornbill-released/#upgrading

**Comment by mistercrunch** [comment]
Done, thanks for the feedback
https://github.com/airbnb/caravel/commit/1756c279302f4df08cf1242fe3fec570d548240b
