### ISSUE TITLE
SQL Server click table link will show index out of range error

### ISSUE THREAD

**Issue by jumboalex** [airbnb/caravel#292]
I'm pretty new to this, and thanks for the effort to putting up a great tool like this.

So I managed to get Caravel connected to my sql server instance and successfully added the database and several tables.  But when I try to click the table link in the table edit view, it will pop list index out of range error.  The error trace back to
```
File "/usr/local/lib/python2.7/dist-packages/caravel/forms.py", line 113, in __init__
        self.viz = viz
        from caravel.viz import viz_types
        viz = self.viz
        datasource = viz.datasource
        default_metric = datasource.metrics_combo[0][0]
       ** default_groupby = datasource.groupby_column_names[0]**
        group_by_choices = [(s, s) for s in datasource.groupby_column_names]
        # Pool of all the fields that can be used in Caravel
        self.field_dict = {
            'viz_type': SelectField(
                'Viz',
```
Any idea how should I fix this issue?  One of the table contains many many rows, but other tables are fairly small.  I'm running Caravel on a Ubuntu, and my sql server is on a windows 10 instance in the same LAN with the Ubuntu.

Thanks

**Comment by scrimshander** [comment]
Had this same issue with a Postgres database - added it, tested connection fine, added table, but could not create slice due to "list index out of range" error as above.

**Comment by mistercrunch** [comment]
Is it possible that you do not have a single column flagged as "Groupable By" in your table edit view? (referring to this view: http://airbnb.io/caravel/_images/matrix.png)

**Comment by jumboalex** [comment]
Thanks, by checking the groupby box the error is gone.  But should this be an option instead of a must-have check?
