### ISSUE TITLE
Big Number Visual Type Loading Error

### ISSUE THREAD

**Issue by DavidTPate** [airbnb/caravel#331]
When attempting to use the visualization `Big Number` I receive the following error in the console: 

`explore.entry.js:31 Uncaught Error: require(big_number_total) failed.`

Utilizing `Big Number with Trendline` though loads successfully.

Version Info:
```
Metadata-Version: 1.1
Name: caravel
Version: 0.8.6
```

**Comment by mistercrunch** [comment]
Thanks for reporting this, it's fixed in 0.8.7

**Comment by DavidTPate** [comment]
Perfect, thanks! Definitely like the tool. Looks like I need to spin up on Python again to start contributing :shipit:
