### ISSUE TITLE
Issues with caravel command (Windows 10)

### ISSUE THREAD

**Issue by jragonesi** [airbnb/caravel#333]
Has anyone had success running caravel from the command prompt on Windows 10? I was able to run the installation successfully with pip but could not initialize the database. The command prompt gives the error below, unrecognized command. I verified the environmental variables had the correct path.  I changed the caravel script file to a .exe so that I could run it at the command prompt.  I received an error (below) stating the file was not compatible with a 64 bit system.  Has anyone had success with this phase of the installation in Windows?

C:\>caravel db upgrade
'caravel' is not recognized as an internal or external command,
operable program or batch file.

C:\>caravel db upgrade
This version of C:\Users\Work Station\Anaconda3\Scripts\caravel is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by gbrian** [comment]
Try `python caravel db upgrade`

**Comment by jragonesi** [comment]
thanks, i had to drill down to the bin directory:

> C:\Anaconda3\Lib\site-packages\caravel\bin

 once i was there the python command worked as it should. much appreciated.

**Comment by andrewhn** [comment]
I had the same issue on win 10. Seems the `scripts` argument in the setup.py file isn't working for some reason, where it is on Linux. Possibly upstream?

**Comment by cons0l3** [comment]
The setup.py should be switched from using "scripts" to using [automatic script creation](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation) via entry_points. I have tried it locally, but not going to open a PR. maybe someone from the core team can implement the fix.

**Comment by dmenin** [comment]
Here's how I solved it:

Go to the installation folder (in my case):
C:\Anaconda2\Lib\site-packages\caravel\bin>

and type:
python caravel db upgrade

**Comment by roemhildtg** [comment]
I too was having problems with this, but as @dmenin mentioned, just navigate into `virtualenv\scripts` and type `python caravel db upgrade`. 

I'm stuck here though, it runs a bunch of flask_appbuilder.base commands and stalls out on 

`Running upgrade -> 4e6a09bad7a8, Init`. Is this happening to anyone else?

**Comment by bmogili-involve** [comment]
I cannot install caravel on my windows system. Please let me know how would we do it?

**Comment by gbrian** [comment]
@bmogili-involve which error?
BTW for running in Windows use "runserver -d" and optional a port, reason is **gunicorn** is not available for windows.

Hope this helps

**Comment by JoeBrody** [comment]
Went into my installation folder 
     C:\Users\Me\Documents\GitHub\caravel-master\caravel-master\caravel\bin
Entered Command:
     python caravel db upgrade

Got this message: 
Traceback (most recent call last):
  File "caravel", line 8, in <module>
    import celery
ImportError: No module named 'celery'

Any ideas on this?

**Comment by roemhildtg** [comment]
@JoeBrody `pip install celery` should fix that.

**Comment by xrmx** [comment]
I don't think there's much actionable here, closing.

**Comment by github35** [comment]
I spent two days to solve sasl depency problem on Windows. If anyone had the same problem, please refer to this link: http://stackoverflow.com/questions/26505882/unable-to-install-sasl-0-1-3-python-package-on-windows-machine

**Comment by EvanGerry** [comment]
modify cli.py method（runserver）  let modify debug to True
 then run superset server do not use  gunicorn start 👍 

def runserver(debug, no_reload, address, port, timeout, workers, socket):
    """Starts a Superset web server."""
    debug = debug or config.get("DEBUG")
    """modify debug to True"""
    if True:
        app.run(
            host='0.0.0.0',
            port=int(port),
            threaded=True,
            debug=True,
            use_reloader=no_reload)
    else:
        addr_str = " unix:{socket} " if socket else" {address}:{port} "
        cmd = (
            "gunicorn "
            "-w {workers} "
            "--timeout {timeout} "
            "-b " + addr_str +
            "--limit-request-line 0 "
            "--limit-request-field_size 0 "
            "superset:app").format(**locals())
        print("Starting server with command: " + cmd)
        Popen(cmd, shell=True).wait()

**Comment by mistercrunch** [comment]
Isn't it the same as running `superset runserver -d` ? BTW I wouldn't recommend running the debug server in production.
