### ISSUE TITLE
Issue in adding tables for Redshift

### ISSUE THREAD

**Issue by shahneil88** [airbnb/caravel#336]
Hi,

1) I created a connection using 
redshift+psycopg2://username:password@host:5439/dev
2) I clicked on Test Connection. It says "Connection seems ok!"
3) I save it and go back.
4) I click on Sources -> Tables -> New table
5) Give name of table and Database as my newly created Database and click on save. It gives me below error.

![screen shot 2016-04-13 at 12 18 28 pm](https://cloud.githubusercontent.com/assets/7529421/14482702/e54a46a2-0171-11e6-8ebf-ddaebdb9747b.png)

6) I go back to my Database and see that connection string has become

redshift+psycopg2://username:XXXXXXXXXX@host:5439/dev
I believe password has been masked.
But now when i click on Test Connection it gives error

![screen shot 2016-04-13 at 12 20 59 pm](https://cloud.githubusercontent.com/assets/7529421/14482724/35348e16-0172-11e6-94d7-26f489097616.png)

7) When I click on table name, which I created in step 5, it redirects me to error page

![screen shot 2016-04-13 at 12 32 38 pm](https://cloud.githubusercontent.com/assets/7529421/14482892/10a9832e-0174-11e6-9d4c-3ae98ffb677d.png)

Not sure, what am I doing wrong.

**Comment by kingo55** [comment]
+1

@shahneil88 - I believe it masks the password with Xs and uses the mask as the password when you test the connection. Just replace the Xs with your actual password and try "Test Connection" again.

As for adding tables, can you add tables manually after updating your search path? E.g.

Sources > Tables > Add new Sqla table

Type the table name in eg. if it's "atomic.impressions" with the schema, just use "impressions".

In general though, this is a bug I've also noticed.

**Comment by shahneil88** [comment]
@kingo55 - 

I did try adding tables. I cannot add tables even from public schema.

**Comment by kingo55** [comment]
Interesting... Does the user have access to the table? Do they also have usage on the schema?

I had a similar issue where I managed to fix it by granting usage of the schema to the user.

**Comment by shahneil88** [comment]
Yes, My Redshift DB has only 1 user. Admin user. 
I have provided those credentials in caravel connections DB.
