### ISSUE TITLE
Exception explore druid datasource then no result match query

### ISSUE THREAD

**Issue by vasiliy-kiryukhin** [airbnb/caravel#349]
![image](https://cloud.githubusercontent.com/assets/2155501/14533002/e6b76eb6-026b-11e6-910a-ca61495c09ff.png)

Exception thrown when no/empty resultset from druid, otherwise (query results are present) everything is fine

**Comment by mistercrunch** [comment]
Exceptions look ok when not in DEBUG mode. Showing the debugger is a feature.

**Comment by mistercrunch** [comment]
Oh and I fixed the CSS doing white on white in the error report in 0.8.7.

Thanks for taking the time to file bug reports and providing good screenshots though, that's really helpful!
