### ISSUE TITLE
Password to databases should be hidden by default

### ISSUE THREAD

**Issue by lenguyenthedat** [airbnb/caravel#354]
If you go to `http://localhost:8088/databaseview/show/2` (where 2 is the id of your database), you will see password in plain sight:

![screen shot 2016-04-15 at 10 18 24](https://cloud.githubusercontent.com/assets/1543321/14549670/92c32d02-02f4-11e6-960b-7ba9eaf92071.png)

I don't think it's very secured, since https is not enforced by default either :disappointed:

**Comment by mistercrunch** [comment]
Oh wow. Thanks for reporting that. The password is encrypted in the database, but shouldn't be in plain sight here. I'll pull it out of that view right now.

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/355

**Comment by mistercrunch** [comment]
Merged, 0.8.8 is out and addressing the issue. I'm communicating to the community now via the Google group and Gitter channel. Again, thanks for pointing this out.
