### ISSUE TITLE
Cannot create table in Caravel, when we have same table name in different schema

### ISSUE THREAD

**Issue by shahneil88** [airbnb/caravel#356]
I have 3 schema in Redshift
1) Schema1 
2) Schema2
3) Schema3

Each schema has a table called users

I went to Caravel -> Sources -> Tables -> Add a new record
1)
Table name - users
Schema name - Schema1
It add successfully.

2) 
Table name - users
Schema name - Schema2
Error - Table name already exists.

There should be a way to add tables with same name in different schema

**Comment by alanmcruickshank** [comment]
As mentioned on #330

One option would be to allow qualified names at the table creation stage:
specifying name "schema1.tablename" to distinguish it from
"schema2.tablename".

On Fri, 15 Apr 2016 04:55 Neil Shah, <notifications@github.com> wrote:

> I have 3 schema in Redshift
> 1) Schema1
> 2) Schema2
> 3) Schema3
>
> Each schema has a table called users
>
> I went to Caravel -> Sources -> Tables -> Add a new record
> 1)
> Table name - users
> Schema name - Schema1
> It add successfully.
>
> 2)
> Table name - users
> Schema name - Schema2
> Error - Table name already exists.
>
> There should be a way to add tables with same name in different schema
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/airbnb/caravel/issues/356>
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825

**Comment by shahneil88** [comment]
@alanmcruickshank - I did try that, but it gave error, "Table does not exist"

**Comment by mistercrunch** [comment]
And here's the fix, thanks for reporting this issue.
https://github.com/airbnb/caravel/pull/360

**Comment by shahneil88** [comment]
@mistercrunch - Thanks for fixing this issue. When would this be released? I am currently on 0.8.8

**Comment by jerowe** [comment]
This issue also exists for mysql. Any fixes?

**Comment by mistercrunch** [comment]
What version are you on @jerowe ?

**Comment by xrmx** [comment]
@jerowe PR for docs are more than welcome, there's a "tutorial for administrators" that may fit or not :)

**Comment by jerowe** [comment]
The information was definitely around, just a bit spread out. I have had to
figure out a few things, but I felt the process was very intuitive. If you
accept prs on docs I may write something up for migrating to a different
background.

Thanks for the great tool!
