### ISSUE TITLE
MySQL Table: Running Query raises Exception("test")

### ISSUE THREAD

**Issue by RogerKaufmann** [airbnb/caravel#364]
When running a query on a table stored in a MySQL DB, the query doesn't run and caravel raises an Exception("test").

Operating System: Raspbian GNU/Linux 8 (jessie)
Python: 2.7.9.
Caravel version: 0.8.8
Caravel is running in wsgi/apache2, named "caravelapp.py"

Steps:
- caravel_config with connection string to local mysql instance
- Created admin user with "fabmanager --create-admin --app caravelapp"
- Created DB with "fabmanager --create-db --app caravelapp"
(Setup of DB works correctly)
- Added Datasource / Table from same mysql instance
- Tried to execute SQL via caravel-link on table view; Can see all the fields and datatypes but executing raises an Exception("test) (see attached picture/error.log)

Thanks.
![bug_report_airbnb](https://cloud.githubusercontent.com/assets/3726945/14587037/0519a162-04ab-11e6-8cbe-3797ecb97072.PNG)

[error.txt](https://github.com/airbnb/caravel/files/222638/error.txt)

**Comment by mistercrunch** [comment]
Fixed here:
https://github.com/airbnb/caravel/commit/04f1b176c49fc3d005178e18db39d08b8fc7de30

This view now is more clear about requiring the permission `all_datasource_access` which means the Admin or Alpha role.
