### ISSUE TITLE
How to get the tables located on schemas other than public in postgres

### ISSUE THREAD

**Issue by nessyh** [airbnb/caravel#373]
I need to get the tables from a schema other than public, currently the tables available in the public schema is listing, but the tables on other schema is not available. Is there any way to add tables located on other schema in caravel. I have seen lot of issues related to schema is already raised, but I didn't get a proper solution from those. Any suggestions?

**Comment by xrmx** [comment]
Which version are you using? Shouldn't this be already handled in
https://github.com/airbnb/caravel/commit/5cadd6794cfb6c70f54e968b9e82b2c991f5ea5b ?

**Comment by nessyh** [comment]
Thanks @xrmx, Updated the latest version, Option for providing the schema is available in the latest version. Now its working.

**Comment by xrmx** [comment]
@nessyh then please close the bug :) Next time please remember it's good habit to report bugs against latest code.
