### ISSUE TITLE
Tables not showing in sqlite database upon successfully testing connetion

### ISSUE THREAD

**Issue by maresk** [airbnb/caravel#378]
I created an sqlite database using the python api and loaded data into it from a csv and it works correctly and responds to `SQL` queries. I for some reason cannot see the columns upon  using 'sqlite:////tmp/mydatabase.db' in Caravel . The `testing connection`  says `ok` when the table loads but the column names do not show up in the bottom. I can see the column names when I click the `sql` link in the `SQL link column` and can SELECT columns and load the data on that page but cannot actually use any of the the column names when I try to create a new table and get the `Table doesn't seem to exist in the specified database, couldn't fetch column information` message. The tutorial says the column names should show up below after testing the connection. It works for the example database using 'sqlite:////tmp/caravel.db' but not for any other database. . Any idea what is wrong here ?

**Comment by mistercrunch** [comment]
Are you sure you're pointing to your database properly? The `Test Connection` can give false positives.

**Comment by maresk** [comment]
I don't think that is the reason because I did  suspect that and so copied my database into /tmp just to make sure that it exists alongside the caravel.db (from which loads columns correctly as expected). To be specific when I use the following  `sqlite:////tmp/caravel.db` the columns show up correctly. But they do not show up when I substitute my database name which also exists in `/tmp`. As I mentioned in the previous post the columns do exist and are there  because I can see the column name fields and select them using the SQL query  when I click on the `SQL Link` field.  Looks like the column names are not populated upon loading the database for some reason. Instead only a `Data` button shows up.

**Comment by maresk** [comment]
Fixed, turns out the only table was `DATA` .
