### ISSUE TITLE
Add timestamp formatting on Tableviz (Similar to x axis on LineChart)

### ISSUE THREAD

**Issue by sid88in** [airbnb/caravel#379]
@mistercrunch I am planning to add drop down on Tableviz to choose different timestamp formats (similar to line chart x axis). This can be done either in back end - while preparing json payload (default isoformat) or java script.

Where would your recommend to add this feature?

**Comment by mistercrunch** [comment]
So far we've been exposing d3 time formatters so I'd stick to that, you might be able to reuse the form element `x_axis_format`, with a different label. The backend should probably stick a css class to identify that it's a date and on the client you'd select `td.date` and apply the formatting.
