### ISSUE TITLE
Non-standard SQL datetime format?

### ISSUE THREAD

**Issue by joshwalters** [airbnb/caravel#397]
I am looking at this line here: https://github.com/airbnb/caravel/blob/master/caravel/models.py#L588

```python
tf = '%Y-%m-%d %H:%M:%S.%f'
```

This is used for parsing the datetime column when doing SQLAlchemy queries.

Is there a reason why this format is used instead of [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)?

Something like:

```python
tf = '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by mistercrunch** [comment]
I think it has to do with how different databases autocast and/or how people store dates as string.

I've been spending some time trying to figure out how to have sqlalchemy do the proper casting but haven't figured it out yet.

We may need for `is_dttm` columns to allow to define how the time constants should be casted when comparing to them...

**Comment by mistercrunch** [comment]
This should help https://github.com/airbnb/caravel/pull/446, please test and report whether it fixes your issues.

**Comment by joshwalters** [comment]
This did not fix my issues, because my dttm column is in a custom format ("%Y%m%d%H").

We are thinking of adding an option to the dttm columns to allow users to provide the datetime format regex string that they want to use, if the default does not work the way they need. Would that sound reasonable? It would then be used in the query generation, and in the visualization.

**Comment by xrmx** [comment]
@joshwalters has this been fixed by https://github.com/airbnb/caravel/pull/652 ?

**Comment by joshwalters** [comment]
@xrmx Yes it has, closing ticket now.
