### ISSUE TITLE
[slice height ] - Resizing one slice modifies the height of other slices on a dashboard

### ISSUE THREAD

**Issue by martindaniel4** [airbnb/caravel#398]
- OS : MacOSX - El Capitan 
- Browser : Chrome `Version 50.0.2661.86 (64-bit)`

Bug description : when I resize a slice on one of my dashboard, this modifies also the height of other slices (in the screenshot below, I modified the content of the upper right slice). 

If this is related, the upper left slice is referenced in the `filter_immune_slice` in the dashboard property. 

![screen shot 2016-04-25 at 5 31 39 pm](https://cloud.githubusercontent.com/assets/695006/14803121/aa30f414-0b0b-11e6-82b9-45bccd3286c3.png)

**Comment by mistercrunch** [comment]
I'm pretty sure I fixed that today. Can you confirm?

**Comment by martindaniel4** [comment]
Yep that works now!
