### ISSUE TITLE
when i create and save a databse it flash "General Error <class 'sqlalchemy.exc.StatementError'>"

### ISSUE THREAD

**Issue by mili-yini** [airbnb/caravel#399]
i  create a database and test ok,but when i save  it, caravel flash " General Error <class 'sqlalchemy.exc.StatementError'>" , how can i solve this problem .thank you

**Comment by mistercrunch** [comment]
Is your connection string valid?

**Comment by xrmx** [comment]
3 months without reporter feedback, closing.

**Comment by FrankXfs** [comment]
I met the same issue, does anyone knows how to solve it? thx.

**Comment by FrankXfs** [comment]
Test connection is good, after tested connection , the tables can be listed on the bottom of the page, but when I clicked 'save',  it returns :General Error <class 'sqlalchemy.exc.StatementError'>

**Comment by xrmx** [comment]
@FrankXfs we can reopen the issue if you have a stacktrace, can reproduce on master and you report your database connection uri. Also please double check that's your stacktrace is not the same of #464.

**Comment by chatlourd** [comment]
same prodlem - no juice?
