### ISSUE TITLE
Druid Metrics and Columns Not Populating

### ISSUE THREAD

**Issue by therevoltingx** [airbnb/caravel#409]
#### Environment
Ubuntu 14.04
Caravel 0.8.9
Druid 0.8.1

#### Description
We have two data sources and one of them is failing to automatically populate the columns and metrics table.  One data source correctly generates all the columns such as `__time` and `count` but not the other data source.

Tried to refresh the druid metadata several times and ran `caravel refresh_druid` several times also without any luck.

Looking at the datasource through Druid's various APIs doesn't reveal anything too different from the other data source.  The only thing that's different is the name and the dimensions being indexed.

**Comment by mistercrunch** [comment]
Most likely you'll have to follow and debug the `refresh_druid` process in your environment. It's just impossible to debug remotely.

Note that we use the segment metadata endpoint in druid to figure out the metadata, if you don't have segments (only a realtime server), this may not work.

**Comment by therevoltingx** [comment]
Hi,

After some digging in it seems that it is indeed to the realtime server issue/bug.
There's a piece of code that will not extract the metadata for segments less than 24 hours.  
After a day, i was able to refresh the metadata and was able to see data.

We don't use realtime, but we do a lot of small batches and then one big daily batch.  
It seems to be working now, but perhaps it should be documented somewhere that new data sources will not be scannable for 24 hours.

Thanks.

**Comment by bohemia420** [comment]
@therevoltingx Is it ?  So this means I need to wait for 24 hours to see the metrics and columns showing up ? I mean after 24 hours I refresh the datasource metadata and then only shall I be able to make fancy reports oil paintings graphs and all crap :D rofl!! how did you trace the error btw .. ?

**Comment by therevoltingx** [comment]
@bohemia420 

Yeah, you can look at the code itself.  I don't ever use PHP but this seems to be the cause: https://github.com/airbnb/caravel/blob/master/caravel/models.py#L1016

**Comment by xrmx** [comment]
This should have been fixed in #526.
