### ISSUE TITLE
caravel 0.8.9

### ISSUE THREAD

**Issue by sid88in** [airbnb/caravel#413]
pip install caravel==0.8.9

Collecting caravel==0.8.9
  Could not find a version that satisfies the requirement caravel==0.8.9 (from versions: 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8)
No matching distribution found for caravel==0.8.9

**Comment by philippfrenzel** [comment]
well, I guess the latest release is 0.8.8 so no 0.8.9 tag is existing - i guess you wanna try latest or dev-master

**Comment by cooldudehackcode** [comment]
I do see tag 0.8.9 here https://github.com/airbnb/caravel/tags

**Comment by sid88in** [comment]
I see 0.8.9 tag here: https://github.com/airbnb/caravel/tags

**Comment by philippfrenzel** [comment]
yes you are right ...! sorry - didn't saw that before!

**Comment by xrmx** [comment]
@sid88in having a tag in git does not mean having a package for the same version uploaded to pypi :)
Looks like 0.8.9 has been uploaded so you can close this: https://pypi.python.org/pypi/caravel

**Comment by sid88in** [comment]
Yay! cool didn't know that :)
