### ISSUE TITLE
Caching doesn't seem to apply to dashboards

### ISSUE THREAD

**Issue by joshwalters** [airbnb/caravel#416]
Caching works for slices, but for dashboards it looks like a new query is triggered on every reload.

For long running queries, or for dashboards with many slices, this can become a problem.

**Comment by mistercrunch** [comment]
It works on my side. If you refresh a dashboard you don't see a red refresh button?
<img width="524" alt="screen shot 2016-05-01 at 8 06 44 am" src="https://cloud.githubusercontent.com/assets/487433/14942511/b417aa42-0f73-11e6-9b1a-3648039604a7.png">

**Comment by joshwalters** [comment]
No, I don't see a red refresh button. This is not a Druid connection, but a SQLAlchemy connection, maybe that is the difference?

The caching works fine for slices, but on the dashboards a new query is triggered each time.

**Comment by joshwalters** [comment]
After further testing, I think this issue is invalid. Not sure what was causing problems before.
