### ISSUE TITLE
How to bypass login page?

### ISSUE THREAD

**Issue by sid88in** [airbnb/caravel#417]
For our use case, users can only access dashboards once they have proper authentication in place. The flow is:

User -> Internal Authentications -> Caravel Login Page (username/password) -> Dashboards

In current state of the application, user is assigned a role within some access permissions. Our use case in particular does not require login authentication (its redundant). But in my understanding  the flask app is bounded to access permissions based on user login. 

What the right way to move forward if I want to deprecate user login page and route him/her directly to dashboards based on internal authentications. How will access permissions work in that case.

**Comment by mistercrunch** [comment]
This is a RemoteUser-type authentication, check out the Flask App Builder documentation here:
http://flask-appbuilder.readthedocs.io/en/latest/security.html

**Comment by sid88in** [comment]
Thanks!
