### ISSUE TITLE
Can't use custom columns in NOT GROUPED BY

### ISSUE THREAD

**Issue by aquach** [airbnb/caravel#420]
I've been playing around and familiarizing myself with Caravel for an hour or so, so I might be totally on the wrong track with how I'm using columns and metrics. I can't tell the difference between them: are metrics meant for rollup functions?

Anyways, I have a varchar column `date` formatted like `2015-01-01` and I created a custom column with an arbitrary SQL expression that transforms it into `caravel_date` like this: `2015-01-01 00:00:00.000000` so that I can use it in datetime computations. That's worked well, but I can't seem to use it in NOT GROUPED BY: instead of substituting the custom expression instead of the name, it uses the name directly:

```
SELECT caravel_date FROM transactions 
```

instead of

```
SELECT CONCAT(date, ' 00:00:00.000000') FROM transactions
```

I can use the column in GROUP BY and it works just fine, so this seems like a bug. Thanks for listening!

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/421

**Comment by mistercrunch** [comment]
Fixed on master branch

**Comment by aquach** [comment]
:bow: cheers!
