### ISSUE TITLE
add additional time grains

### ISSUE THREAD

**Issue by itajaja** [airbnb/caravel#425]
Is there a specific reason postgres time grains are [limited to specific values](https://github.com/airbnb/caravel/blob/master/caravel/models.py#L397)? postgres allows for more values outside of the range defined in caravel ([pg doc](http://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC)). Is it possible to add some of these grains?

**Comment by mistercrunch** [comment]
Yes, pull requests are welcomed!

**Comment by itajaja** [comment]
Perfect!
