### ISSUE TITLE
Can I use sketch columns with druid datasource

### ISSUE THREAD

**Issue by emtiazahmed** [airbnb/caravel#433]
Hi,

We are using sketches with druid. Is it possible to query that in caravel? If yes, how?

Thanks,
Imtiaz

**Comment by mistercrunch** [comment]
You can just paste the json for the aggregation (as specified here http://druid.io/docs/latest/development/extensions-core/datasketches-aggregators.html) in the DruidMetric's `expression` field.

**Comment by joshwalters** [comment]
This pull request should fix this issue: https://github.com/airbnb/caravel/pull/613
