### ISSUE TITLE
Problem with SQL Server Date Format

### ISSUE THREAD

**Issue by smarquis84** [airbnb/caravel#440]
Hi ! 

I'm connecting to a SQL Server where the date format is mdy. However, when I add the table entry then click on it I'm getting the following error message :

OperationalError: (pymssql.OperationalError) (241, 'Conversion failed when converting date and/or time from character string.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') [SQL: "SELECT TOP 50000 COUNT(*) AS count \nFROM event.[MyTable] AS [MyTable_1] \nWHERE CreatedDate >= '2016-04-29 15:09:42.000000' AND CreatedDate <= '2016-05-06 15:09:42.000000'"]

I tried a workaround that I found which was replacing the tf line with the US format however no luck and still encountering the same issue :( 

Thanks !

**Comment by gbrian** [comment]
Case still open, check https://github.com/airbnb/caravel/issues/185 for a workaround.

**Comment by mistercrunch** [comment]
This should help, please test it and report on whether it works: https://github.com/airbnb/caravel/pull/446

**Comment by xrmx** [comment]
Possibly dup of #185, no feedback since 3 months, closing.
