### ISSUE TITLE
LDAP config ok but not working

### ISSUE THREAD

**Issue by viniciusrsdutra** [airbnb/caravel#443]
Hi everyone!
I'm new to Caravel and made the necessary changes to bind to LDAP.
According to the app log the changes are ok, but users can't login at the front end.
Any help?

Thanks in advance
![ldap-problem](https://cloud.githubusercontent.com/assets/6311982/15086187/62a45408-13b5-11e6-80a5-710254bcd354.png)
![ldap-problem-2](https://cloud.githubusercontent.com/assets/6311982/15086197/7961c4c8-13b5-11e6-8f3f-da51d7d75dce.png)

**Comment by mistercrunch** [comment]
This is actually managed by Flask Appbuilder, you may want to open an issue against their repo.

**Comment by andrewhn** [comment]
@viniciusrsdutra see #334 - I was able to get LDAP auth working but the auto user creation on sign in doesn't seem to work.

**Comment by viniciusrsdutra** [comment]
Thanks @mistercrunch! I've opened and issue against Flask AppBuilder repo.

@andrewhn, thanks also! The thing is I'm using OpenLDAP. I think might be a bug.

**Comment by mtrbean** [comment]
Flask App builder has fixed this in version 1.6.1 but you have to enable `AUTH_USER_REGISTRATION `

**Comment by viniciusrsdutra** [comment]
Thank you so much @mtrbean !
Now it's working!

**Comment by xrmx** [comment]
Looks like it has been fixed, closing.

**Comment by fangyeqing** [comment]
I hava enable AUTH_USER_REGISTRATION,but still come with the following error:
`
Was unable to import caravel Error: name 'AUTH_LDAP' is not defined
`

**Comment by zfbp** [comment]
@fangyeqing AUTH_TYPE=2
http://flask-appbuilder.readthedocs.io/en/latest/config.html
