### ISSUE TITLE
Word cloud error when metric is not text

### ISSUE THREAD

**Issue by wil5for** [airbnb/caravel#444]
The world cloud visualization UI for editing/creating slices breaks when a non-text metric is chosen.

Setup
Osx 10.10.4
sqlite caravel backend
postgres db connection

To reproduce:

Add a non text metric to a table, the default `Count(*)` metric works.
Click on the table to create a new slice.
Change the visualization type to a Word Cloud.
Select the count metric

Result: UI is unhappy, query never runs
js console logs an error

I believe the issue is in caravel.js (colorBnb function), s is not a string
```
  var colorBnb = function () {
    // Color factory
    var seen = {};
    return function (s) {
      if (!s) { return; }
      // next line is for caravel series that should have the same color
      s = s.replace('---', '');
      if (seen[s] === undefined) {
        seen[s] = Object.keys(seen).length;
      }
      return this.bnbColors[seen[s] % this.bnbColors.length];
    };
  };
```

**Comment by mistercrunch** [comment]
This should do it:
https://github.com/airbnb/caravel/pull/447
