### ISSUE TITLE
Druid Datasource- Error "Please define at least one metric for your table"

### ISSUE THREAD

**Issue by vinjadhav** [airbnb/caravel#445]
Hi,

I am using druid data source. When I click on the data source  i get error "Please define at least one metric for your table" .
But  the data source has the metrics defined. I checked it on druid at  "http://localhost:8082/druid/v2/datasources/datasource-name" i get following dimension and metrics details
{"dimensions":["sensortype","sensorunit","sensorid"],"metrics":["sensorvalue"]}

Please suggest 
Thanks

**Comment by vinjadhav** [comment]
Just an update, I am using Druid 0.9.0..

**Comment by mistercrunch** [comment]
I think Caravel somehow failed at picking up your table definition. I'm guessing that if you edit your datasource on the Caravel side you won't see columns or metrics. One known issue is that we need at least one physical segment in order for us to pick up the column definitions. 

We're still on Druid 0.8 at Airbnb and can't insure that 0.9.0 is fully compatible at the moment. If we want to support more version we'd need more sophisticated mocking in the unit tests that would represent things that the REST API for different versions of Druid may return.

**Comment by bohemia420** [comment]
@vinjadhav  did u ever go thru this ? 
https://github.com/airbnb/caravel/issues/409

**Comment by vinjadhav** [comment]
@bohemia420 yes i had gone though #409 .. my problem is not about the datasource.. but I am not able to see dimension and metric data in Caravel. @mistercrunch i do have 2 physical segment in my druid datasource

**Comment by deyani27** [comment]
Hi, I am facing the same issue with druid-0.9.0, from #409 , will waiting for 24hours solve the issue? That is kind of not an acceptable solution for my case.

**Comment by bohemia420** [comment]
Ghanta solve the issue :-)..I switched to metaphase.i have been online
night and day on gitter channel for caravel...found a lot of hue and cry
all over.

**Comment by F-hertz** [comment]
Hi,

Caravel is a beautiful tool, but i got the same problem with druid-0.9.0, i can't show metrics.
Any patch is coming ?
Bohemia420 what was the issue ? 

Thanks
FH

**Comment by xrmx** [comment]
This should have been fixed in #526, closing.
