### ISSUE TITLE
how to disable authentication

### ISSUE THREAD

**Issue by bluepopopo** [airbnb/caravel#450]
Hi,
I want to integrate dashboard to another application. But i didn't find a way to disable caravel authentication. I tried to uncomment AUTH_ROLE_PUBLIC in config.py, but it still asks for login. Is there anyway to do this? 

```
# Uncomment to setup Public role name, no authentication needed
AUTH_ROLE_PUBLIC = 'Public'
```
Thanks

**Comment by mistercrunch** [comment]
I haven't tested public access much, but you can try opening the Public role from the Security menu in the app and adding all/some permissions to it. I just did a bit of testing and it seems to work. Beware that anyone on your network will then have those rights.

**Comment by bluepopopo** [comment]
After copied all admin's roles to Pubilc, I can see http://192.168.0.107:8088/caravel/welcome, but no dashboard or slice displayed.

It throws exception after anonymous access dashboard directly, here is the screenshot,

![dashboard](https://cloud.githubusercontent.com/assets/7251354/15215620/fb63c122-1885-11e6-96fb-adf20e8311df.png)

**Comment by mistercrunch** [comment]
Looks like this is fixed in `master`. I'll push a release today or tomorrow.

**Comment by xrmx** [comment]
Shoule be fixed, closing.

**Comment by ayssi** [comment]
In my config.py I've set AUTH_ROLE_PUBLIC to "Public"  and give all the necessary grants to this Public role but the application still asking for login and password
I've superset 0.28.1 version.
Thanks.

**Comment by levyitay** [comment]
Same here, same issue

**Comment by nnkteja** [comment]
Please provide a fix, it's not fixed.

**Comment by willbarrett** [comment]
I can verify that this functionality works properly in 0.37 - please share additional information on your issue, such as your current Superset version and configuration, if this is not the case for you.

**Comment by nnkteja** [comment]
<img width="693" alt="Screenshot 2020-09-17 at 11 34 51 PM" src="https://user-images.githubusercontent.com/14221696/93510135-64a45000-f93e-11ea-9b91-3cbead75686e.png">
Can you please share documentation on how to disable default authentication. I tried to set AUTH_ROLE_PUBLIC to public in config.py file. But it still asks for login.

**Comment by manasjain0699** [comment]
facing the same issue i create my own image 
```
### Uncomment to setup Public role name, no authentication needed
AUTH_ROLE_PUBLIC = 'Public'
### AUTH_USER_REGISTRATION_ROLE = "Public"
## Grant public role the same set of permissions as for a selected builtin role.
PUBLIC_ROLE_LIKE: Optional[str] = None
class CeleryConfig:  # pylint: disable=too-few-public-methods
ROBOT_PERMISSION_ROLES = ["Public", "Gamma", "Alpha", "Admin", "sql_lab"]
```

![Screenshot from 2021-09-02 12-47-22](https://user-images.githubusercontent.com/75062591/131800277-4a412b80-a231-4332-9df8-71e7bb69a4cc.png)

**Comment by clarabez** [comment]
Facing the same issue here:

-> uncommented `"AUTH_ROLE_PUBLIC = 'Public'"` on` config.py`, no login is necessary when accessing Superset from link, but it is still requesting authentication when adding dashboard link to iframe content on html.

**Comment by FireJohnny** [comment]
still unfixed ,i have got 
![image](https://user-images.githubusercontent.com/19511703/149688173-e5564781-b7f9-4c2f-8380-f90e44223266.png)
set `superset_config.py`
```
# Uncomment to setup Public role name, no authentication needed
AUTH_ROLE_PUBLIC = 'Public'
PUBLIC_ROLE_LIKE: Optional[str] = "Gamma"
```

**Comment by sagar-appperfect** [comment]
We are facing same issue, these are the steps that we followed 
1. Clone Superset's GitHub repository `git clone https://github.com/apache/superset.git`
2. Updated config.py
`# Uncomment to setup Public role name, no authentication needed`
`AUTH_ROLE_PUBLIC = 'Public'`
3. Docker compose (tried it with both dev and non-dev)
NONDEV
`docker-compose -f docker-compose-non-dev.yml pull`
`docker-compose -f docker-compose-non-dev.yml up`
DEV
`docker compose build`
`docker-compose up -d`
4. On UI still redirecting to login page

**Comment by ShreyasJothish** [comment]
The issue with public access is faced by me too. I have enabled the configurations needed and created a role to support public access. But the public dashboard access is still prompting for a password.

# Uncomment to setup Public role name, no authentication needed
AUTH_ROLE_PUBLIC = "Public"
PUBLIC_ROLE_LIKE = "Restricted Gamma No Charts No CSV"

**Comment by SwapnilKhante** [comment]
Is there any update or fix for this issue?

**Comment by keenborder786** [comment]
Facing the same issue. Any updates?

**Comment by oleksandrsv** [comment]
Is it possible to disable auth at all?

**Comment by postwait** [comment]
It still appears broken.  I've tried just about every combination of config options and I'm always redirected to /login

**Comment by OlegBorzin** [comment]
maybe this will help

my superset_config.py file:

`SECRET_KEY="*******************************************"
TALISMAN_ENABLED = False

ENABLE_PROXY_FIX = True
HTTP_HEADERS = {'X-Frame-Options': 'ALLOWALL'}

AUTH_ROLE_PUBLIC = 'Gamma'

FEATURE_FLAGS = {
   "DASHBOARD_RBAC": True,
   "EMBEDDED_SUPERSET": True,
   "EMBEDDABLE_CHARTS": True,
   "ENABLE_TEMPLATE_PROCESSING": True,
   "DASHBOARD_NATIVE_FILTERS": True,
   "DASHBOARD_CROSS_FILTERS": True,
}
CONTENT_SECURITY_POLICY = {
  'default-src': ['self', 'http://**.**.**.**', 'http://**.**.**.**:8088'],
}
ENABLE_JAVASCRIPT_CONTROLS = True`
