### ISSUE TITLE
Fix the wrong foreign key on columns.column_name

### ISSUE THREAD

**Issue by x4base** [airbnb/caravel#466]
In the commit c2bb49f, the foreign key that references datasource.datasource_name was set on columns.column_name when it should be columns.datasource_name. This causes errors when there are any new columns to be created when refreshing the druid datasources.

I am trying to generate a migration script to fix this. However, op.drop_constraint() requires the name of the foreign key you want to drop. 
The following code works on SQLite because the foreign keys don't have any names:

```
naming_convention = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}

def upgrade():
    with op.batch_alter_table('columns', schema=None, naming_convention=naming_convention) as batch_op:
        fk_name = 'fk_columns_column_name_datasources'
        batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.create_foreign_key(fk_name, 'datasources',
                                    ['datasource_name'], ['datasource_name'])
```

But for MySQL, the foreign keys are named like "columns_ibfk_1". Should I presume that on every machines, this foreign key has the same name and just drop the foreign key named columns_ibfk_1?
Do you have any suggestion about how to write a universal migration script that works on every SQL dialects? Or should I iterate through the known default names in different dialects in try-catch blocks?
I just couldn't figure out a way to drop the foreign key without knowing its name.

**Comment by sid88in** [comment]
For me https://github.com/airbnb/caravel/pull/531/files fixed the issue

**Comment by x4base** [comment]
Yes, because it is specialized for MySQL and will only work on MySQL. You can try it on SQLite or other databases. It won't work because the foreign key is not named that way

**Comment by x4base** [comment]
That's why I said I want a "universal migration script that works on every SQL dialects"

**Comment by waterwoodwind** [comment]
Yes，it can't get the real value from the foreign key on SQLite

**Comment by bkyryliuk** [comment]
```
class DruidColumn(Model, AuditMixinNullable):

    """ORM model for storing Druid datasource column metadata"""

    __tablename__ = 'columns'
    id = Column(Integer, primary_key=True)
    datasource_name = Column(
        String(255),
        ForeignKey('datasources.datasource_name'))
    # Setting enable_typechecks=False disables polymorphic inheritance.
    datasource = relationship('DruidDatasource', backref='columns',
                              enable_typechecks=False)
```

Models show correct foreign key now. Closing the issue.

**Comment by x4base** [comment]
Are you sure? It's not about the model, I know the model was fixed. The problem is whether the underlying database is migrated correctly.

**Comment by bkyryliuk** [comment]
@x4base - you right, looks like migrated DB doesn't have the foreign keys:
![screen shot 2016-09-12 at 10 52 12 am](https://cloud.githubusercontent.com/assets/5727938/18446414/12ebb2e4-78d7-11e6-9cfa-f04ca481da04.png)
![screen shot 2016-09-12 at 10 52 29 am](https://cloud.githubusercontent.com/assets/5727938/18446413/12e82d18-78d7-11e6-89e2-b54ddd875a4b.png)
