### ISSUE TITLE
Mysql DB connection not working 

### ISSUE THREAD

**Issue by mohanguruswamy** [airbnb/caravel#482]
Hi ,

when i try to connect to Mysql DB it throws an error as General Error <class 'sqlalchemy.exc.StatementError'>"

Please let us know 

thanks
Mohan

**Comment by alanmcruickshank** [comment]
My SQL connection is working fine for me. Could you include a stack trace
for the error you're receiving?

On Wed, 18 May 2016 12:56 Mohan Guruswamy, <notifications@github.com> wrote:

> Hi ,
>
> when i try to connect to Mysql DB it throws an error as General Error "
>
> Please let us know
>
> thanks
> Mohan
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/airbnb/caravel/issues/482>
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825

**Comment by xrmx** [comment]
3  months without reporter feedback, closing
