### ISSUE TITLE
Chinese characters shows "????" on plot

### ISSUE THREAD

**Issue by jjdblast** [airbnb/caravel#485]
I have some Chinese character data stored in Mysql, which charset is 'utf-8'. When I add this table into caravel, everything works well. But when I try to make some slice, the label and legend change into strange symbol like "???".

By the way, the example data(world's bank data and birth) works well.

![image](https://cloud.githubusercontent.com/assets/3394810/15364105/ce6b3cfa-1d4d-11e6-8be0-661fb73551e6.png)

![image](https://cloud.githubusercontent.com/assets/3394810/15364291/94e27114-1d4e-11e6-86e1-beef9d241a71.png)

**Comment by licq** [comment]
Look at the url of the database connection. If you use mysql, add ?charset=utf8 to the end of the connection url.

**Comment by bnpysse** [comment]
谢谢！您在国内么？我在济南，想交个朋友，希望能常联系。
最近，想把这个caravel改造一下，苦于水平有限，希望能多和您交流一下。谢谢！
------------------------------------------------------------------发件人：Li Chaoqun <notifications@github.com>发送时间：2016年5月25日(星期三) 12:09收件人：airbnb/caravel <caravel@noreply.github.com>主　题：Re: [airbnb/caravel] Chinese characters shows "????" on plot (#485)
Look at the url of the database connection. If you use mysql, add ?charset=utf8 to the end of the connection url.—

**Comment by jjdblast** [comment]
I think @licq's method worked !

**Comment by lifeinearth** [comment]
thank you very much . i have the same problem.

**Comment by yuanhaoliang** [comment]
thanks the same.
