### ISSUE TITLE
Dashboard Filter

### ISSUE THREAD

**Issue by mohanguruswamy** [airbnb/caravel#499]
Hi ,

How can i add the Dashboard filter so all my slices get the filter.
Even though i add filter in slice i don't any where asking for the input.

I know i am missing something.

Can you please share any steps to add the filters.

Thanks
Mohan

**Comment by kkalyan** [comment]
👍 for this request. 

I'd like to have Global Date Filter on Dahsboard, changing which (for eg: 7 day to 30 day) should refresh all the slices on the dashboard. 

@joshwalters See if you can pick this item.

**Comment by kkalyan** [comment]
I believe this is already supported.  In the explore view - select 'Filters' as visualization. List of possible values are shown in drop down. If you add this slice to dashboard and select any of values, remaining slices get refreshed based the selection. 

What is missing is, date filter @mistercrunch mentioned about it here: https://github.com/airbnb/caravel/issues/363#issuecomment-211705872

**Comment by RajkumarKadari** [comment]
Can you please explain step by step so its is very help full to all 


Thanks
