### ISSUE TITLE
Backups of Caravel

### ISSUE THREAD

**Issue by Frituurpanda** [airbnb/caravel#509]
Hi all,

I know that this probably is a very trivial question but how do you guys backup all the work done in Caravel. Say I wanted to export the dashboards, settings and users and import those in another Caravel instance. 

Does anyone know how to export/copy that data?

Thanks in advance!

**Comment by joshwalters** [comment]
That should be stored in the caravel database. By default that is a sqlite db in /tmp/caravel.db I think.

Should be the `SQLALCHEMY_DATABASE_URI` setting in `caravel/config.py`.

**Comment by Frituurpanda** [comment]
Thanks for the reply Josh. I indeed already moved the caravel.db out of the /tmp/ to make it persist when the instance crashes. Am I correct in assuming that all of the caravel configuration and data is in that caravel.db file?

**Comment by joshwalters** [comment]
Yes, I think all the config data will be in that database (users, slices, etc).

**Comment by Frituurpanda** [comment]
Allright Josh. I pulled the file, uploaded it to another instance and it works. Thanks heaps!
