### ISSUE TITLE
Caravel doesn't query metadata in new Druid Datasources

### ISSUE THREAD

**Issue by LAlbertalli** [airbnb/caravel#516]
Hi,

We are evaluating Druid + Caravel for using in our analytic platform and we found a strange behavior being that Caravel doesn't load the metadata information for newly created druid datasources (usually datasources with less than one day worth of data).

Inspecting the code we noticed that in models.py line 1021 (checking commit 7d27692) there's this line `intervals += (max_time - timedelta(days=1)).isoformat()` and a reference to a bug in Druid fixed in 0.8.2 (https://groups.google.com/forum/#!topic/druid-user/gVCqqspHqOQ).

Since we are using Druid 0.9 I've changed the line in our code but I was wondering which is the best approach to remove this workaround (e.g: using conditional code based on Druid Version). I could contribute the patch but I want to discuss how you want to manage this kind of situations.

Thanks

**Comment by xrmx** [comment]
This should have been fixed in #526.
