### ISSUE TITLE
error with i18n

### ISSUE THREAD

**Issue by wgzhao** [airbnb/caravel#527]
I clone the project and complete translations/zh/LC_MESSAGES/message.po .
then I compile and install it with python3.5.

I use `caravel run server -d ` to run up ,it works. I change locale to chinese. after I logged in ,it give me an error like this:
`builtins.TypeError
TypeError: unhashable type: '_LazyString'`

I googling the question and attempt to variant "solutions" .but all of them failed.

How can i fix it .

**Comment by xrmx** [comment]
@wgzhao can you post the full backtrace please?

**Comment by xrmx** [comment]
One month without reported feedback, closing.
