### ISSUE TITLE
UI rendering problem on cloned repo

### ISSUE THREAD

**Issue by ramashishb** [airbnb/caravel#540]
Hi,

I have cloned caravel and set it up following instructions in CONTRIBUTING.md. Steps followed-
```
    # setup a virtual env and activate it
    virtualenv env
    source env/bin/activate

    # install for development
    python setup.py develop

    # Create an admin user
    fabmanager create-admin --app caravel

    # Initialize the database
    caravel db upgrade

    # Create default roles and permissions
    caravel init

    # Load some data to play with
    caravel load_examples

    # start a dev web server
    caravel runserver -d
```
The home page post login however doesn't render. Attached screenshot. My environment is OS X 10.9.5.
Any idea?

Regards,
Ramashish

<img width="596" alt="screen shot 2016-05-31 at 1 01 43 pm" src="https://cloud.githubusercontent.com/assets/3232760/15666721/f99be4ec-272f-11e6-95c1-4846df0f3da9.png">

**Comment by IljaKroonen** [comment]
You also need to follow the steps in the next part, Setting up the node / npm javascript environment. It will generate the static assets you need.
