### ISSUE TITLE
Dashboard Access Control to specific user

### ISSUE THREAD

**Issue by nivpawar** [airbnb/caravel#550]
Hello Team,

could you please help how to given permission to show or access specific dashboard for specific user, if i don't want to show my all dashboard to my all user, can you please suggest to right permission for dashboard access control, which kind of permission i need to assign for limited access user. i have checked all permission but there is no permission regarding this

**Comment by xrmx** [comment]
This is a dup of #538

**Comment by fingermark** [comment]
Still not obvious how to do this.  I have a multi-tenant situation, which I could solve w/ permissions on views (instead of row level granularity) and roles.  I need each role to have a pre-defined dashboard.

**Comment by gowtham-sai** [comment]
Is there any update on this?

**Comment by nivpawar** [comment]
Hi Gowtham,

We can change permission as per our requirement for specific users, but in
dashboard tab its visible for all user. in case want share specific
dashboard with specific user you can share only link of this dashboard.

**Comment by gowtham-sai** [comment]
Hi Nivawar, 

I don't have problem if the dashboard names are visible in dashboard tab to all the users. But the problem is say, I have a dashboard named Finance which is created from a table "Agg_Data" and another dashboard named Category which is also created from the same table Agg_Data. 

The Users who are able to access Category dashboard ( Permission on company.agg_data ) can see the dashboard of Finance (In side dashboard -slices and all) because of permission. 

Is there a way to give permission to a user for particular dashboard/slice only?

**Comment by jackpgao** [comment]
We have the same problem.

**Comment by sachinhub** [comment]
We also have same problem. Any suggestions ?

**Comment by mistercrunch** [comment]
Currently it's data-centric access definition, assuming that we want users to slice/dice to answer their own questions beyond the dashbaord/report.

We could add per-dashboard access and cut these users off from using the explore view. Speaking for Airbnb I don't think we need that feature so it would have to be community contributed.

**Comment by vidhaat** [comment]
@mistercrunch can you please point me in the right direction so that I can make the required changes as this is needed for my usecase?

**Comment by laresbernardo** [comment]
Same here!

**Comment by gdeepali** [comment]
I need this feature in my application too. Any updates on this?

**Comment by aabdinur** [comment]
Same here! I would like to have this feature. How do we do this?

**Comment by SpyderRivera** [comment]
We have implemented a hack for this. We have the dashboard page only show certain dashboards based off of the owner. We have a published owner and then they see their own. This allows the users to still share their dashboards with links, but removing the clutter on the dashboards page. Not everyone wants to share their dashboards with the world.

**Comment by aabdinur** [comment]
@SpyderRivera, how does the hack work? Is there a restriction based on the owner of the dashboard? Please elaborate more on this.

**Comment by SpyderRivera** [comment]
The hack is based on the owner of the dashboard. We are working on how to better implement, but this worked for us.

**Comment by naveedalamiowa** [comment]
Hi SpyderRivera,
Could you gives us the details on how to implement the hack. Is the hardcoded "published" like a role or is this something more. Kindly explain the steps if possible.
Thanks

**Comment by SpyderRivera** [comment]
@naveedalamiowa https://github.com/apache/incubator-superset/pull/4725
