### ISSUE TITLE
Webpack serves old bundles

### ISSUE THREAD

**Issue by PZaytsevUSC** [airbnb/caravel#552]
Hello, I am currently trying to implement several new visualizations in caravel.
I don't usually use modern web technologies in my development, so I might be doing something wrong.
I set up my dev environment and everything seems to be working fine. 
However there is a problem with a webpack serving old bundles. Not only it does not update in watch mode, it also does not update in a regular mode. 
It look like that path and public paths are set correctly. 
(probably not an issue: [https://github.com/webpack/webpack-dev-server/issues/24](url))
When the application is run from the new port the updates are served correctly, also when the browser cache is cleared. 
Running both 

`caravel runserver -d -p [port-number]`
`npm run dev`
every time does not seem to work either.

**Comment by mistercrunch** [comment]
Looks like an external issue to Caravel. May be specific to your version of node.

**Comment by xrmx** [comment]
Closing then.
