### ISSUE TITLE
Tutorial for Post Agg in Caravel v9.0

### ISSUE THREAD

**Issue by sid88in** [airbnb/caravel#554]
@x4base is there any tutorial on how to use post agg in 9.0? 
Looks like I can create a new metric and metric name = postagg
do I have to give the operations as json? Is there an example snapshot of how to create a derived metric in caravel

**Comment by mistercrunch** [comment]
Is what is in here clear enough?
http://airbnb.io/caravel/druid.html

**Comment by sid88in** [comment]
Nevermind - I didn't look at this link. Thanks!
