### ISSUE TITLE
Add 'utf-8' support

### ISSUE THREAD

**Issue by xiaohanshi** [airbnb/caravel#563]
Hello,

Sometimes, we might have chinese character in the ldap config, like `CN=xiaohan.shi, OU=用户`
So, Maybe you should do some changes to the code to support chinese character.
```
# encoding= utf8
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```

**Comment by xrmx** [comment]
@xiaohanshi is it a theoretical problem or do you have a stacktrace to show?

**Comment by xiaohanshi** [comment]
**As you can see, my config.py of LDAP contains chinese character**
![4 pic](https://cloud.githubusercontent.com/assets/11733909/15822338/bed2f2f4-2c27-11e6-9614-5092ee822000.jpg)
**When i am trying to login in via LDAP, i meet the problem below**
![1 pic_hd](https://cloud.githubusercontent.com/assets/11733909/15822353/dc9cb57c-2c27-11e6-8daa-0b354073f091.jpg)
![2 pic_hd](https://cloud.githubusercontent.com/assets/11733909/15822386/0bb860a4-2c28-11e6-82e1-aad851709f13.jpg)
**So, i add some codes to views.py and i solves the problem**
![3 pic](https://cloud.githubusercontent.com/assets/11733909/15822469/878faa16-2c28-11e6-854b-3144ec0a666f.jpg)

**Comment by xiaohanshi** [comment]
@xrmx 
Another error we have found:
![30 pic](https://cloud.githubusercontent.com/assets/11733909/15847789/4aae6676-2cbb-11e6-8b5d-f0b37e28d5fd.jpg)
![29 pic_hd](https://cloud.githubusercontent.com/assets/11733909/15847796/50c56a64-2cbb-11e6-81ea-365aa5037289.jpg)

**Comment by mistercrunch** [comment]
http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script
```
export PYTHONIOENCODING=UTF-8
```
