### ISSUE TITLE
keep user infomation

### ISSUE THREAD

**Issue by guoyangyangyang** [airbnb/caravel#569]
I have encounted such a problem like that I cannot reserve my user infomation while I restart my machine.The caravel use sqlite as database, so how could I change the source code to save my user infomation permanently?

Thanks,

**Comment by alanmcruickshank** [comment]
Caravel uses a sqlite database in a temporary folder of the instance it's
running on. You can see the path to it in your caravel_config.py. Check
that this file is persisting when you restart the machine. If you're using
an environment like docker (which rebuilds the instance every time you
start) then the configuration won't persist. Try changing the directory to
a mounted folder, or using an external database (like a MySql server).

On Tue, 7 Jun 2016 at 03:33 guoyangyangyang <notifications@github.com>
wrote:

> I have encounted such a problem like that I cannot reserve my user
> infomation while I restart my machine.The caravel use sqlite as database,
> so how could I change the source code to save my user infomation
> permanently?
>
> Thanks,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/airbnb/caravel/issues/569>, or mute the thread
> <https://github.com/notifications/unsubscribe/AEdFuHfYxdX6ysi-DWO4nZLz3tzYWTMLks5qJNiGgaJpZM4Ivf3G>
> .
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825

**Comment by mistercrunch** [comment]
Answer is right, should be trivial to figure out. Closing.
