### ISSUE TITLE
Bug: Cannot save slice where there is not Group by set

### ISSUE THREAD

**Issue by bseng** [airbnb/caravel#571]
Scenario:
I've a database set with mssql+pyodbc table created. When I create a table view slice without group by( remove count(*) from default) and a list of columns in no group by. After I save and reload the slice the count(*) in group by reappears, giving me error saying "Exception: Choose either fields to [Group By] and [Metrics] or [Columns], not both". This happens to overwrite as well.

Expected behaviour:
my saved slice should reappear again. 

Caravel version: 0.9.0

**Comment by mistercrunch** [comment]
This is fixed in master and will make 0.9.1!
