### ISSUE TITLE
TypeError: unhashable type: '_LazyString'

### ISSUE THREAD

**Issue by jjdblast** [airbnb/caravel#589]
When I first login the caravel, it's came this builtins.TypeError.

`TypeError: unhashable type: '_LazyString'`

I install caravel with python3 `pip3 install caravel`, and do exactly as installation&configuration guide.

here's screenshot:

![image](https://cloud.githubusercontent.com/assets/3394810/15937222/8d76e5f0-2ea0-11e6-8bd0-e69a671600bc.png)

![image](https://cloud.githubusercontent.com/assets/3394810/15937224/8f970ae0-2ea0-11e6-9dae-55884d8f58cd.png)

**Comment by nostalgiaz** [comment]
Hi @jjdblast,
I have the same problem.

The requirement says `'flask-appbuilder>=1.6.2, <2.0.0'` and it installed the 1.8.2 version that seems to produce this bug.
I tried to `pip install Flask-AppBuilder==1.7.0` and it seems to work... 

Indeed, they have some problem with dependencies...

**Comment by xrmx** [comment]
Is this fixed for you? Anyway it looks like a flask-appbuilder issue so we can't do much here.

**Comment by xrmx** [comment]
Or maybe this has been fixed here 7dd5b6716e44880f6481f0f454e415b545701503
