### ISSUE TITLE
database test connection does not work after model has been saved

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#596]
Because the password is substituted with Xs. Could be an easy patch for someone willing to start contributing.

**Comment by jkeller-miovision** [comment]
I'm having this issue.  I don't understand how this is usable for any db with a password.  Is there a work-around?  Has this always been broken?  Thanks.

**Comment by xrmx** [comment]
@jkeller-miovision don't panic, it's annoying but does not do any harm.
