### ISSUE TITLE
black text on black background on sunburst

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#598]
A picture is worth a thousand words :)

![sunburst-black](https://cloud.githubusercontent.com/assets/12932/15970577/8c2fa520-2f35-11e6-8235-b730f17e4a40.png)

**Comment by mistercrunch** [comment]
@williaster

**Comment by xrmx** [comment]
So the black background is for values of empy string, changed to NULL in my datasource and they are now not shown. It still may happen if the first metric is NULL and the second metric is not NULL to have the first metric displayed in black. I've poked at the code but can't sort out where black is used for empty values. Any hint?

**Comment by mistercrunch** [comment]
Fixed in master
