### ISSUE TITLE
Export as CSV/JSON is exporting only the first 2 columns.

### ISSUE THREAD

**Issue by kkalyan** [airbnb/caravel#601]
Export as CSV/JSON is exporting only the first 2 columns.

**Comment by mistercrunch** [comment]
Fixed in `master`

**Comment by Noah-Heil** [comment]
Thanks I came here because I am experiencing the same issue but I guess I will just have to wait for the changes to propagate their way up.

**Comment by mistercrunch** [comment]
It's fixed in 0.9.1 which is out since yesterday.

**Comment by kkalyan** [comment]
Thank you @mistercrunch
