### ISSUE TITLE
Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead

### ISSUE THREAD

**Issue by ylkjick532428** [airbnb/caravel#603]
when i use the command
/usr/local/python27/bin/fabmanager create-admin --app caravel

/usr/local/python27/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/python27/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/python27/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning

**Comment by mistercrunch** [comment]
Should be fixed in the next version of FAB. I fixed it here:
https://github.com/dpgaspar/Flask-AppBuilder/pull/332

**Comment by qinzl1** [comment]
I don't understand i find the same issues:

fabmanager create-admin --app caravel
Traceback (most recent call last):
  File "/usr/local/bin/fabmanager", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Flask-WTF>=0.9.1

**Comment by l0n3r4n83r** [comment]
I see the same issue when I run fabmanager create-admin -app caravel

$ fabmanager create-admin -app caravel
/usr/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning
Error: no such option: -a
