### ISSUE TITLE
Labels cut-off in distribution bar chart

### ISSUE THREAD

**Issue by apitts** [airbnb/caravel#607]
Please see image below for example:
![rsz_screenshot_from_2016-06-13_145831](https://cloud.githubusercontent.com/assets/4076720/15997493/0fa9fe48-3178-11e6-98c0-49432ee6e262.jpg)

**Comment by mistercrunch** [comment]
Should we do some math around the max string length or parameterize the bottom margin?

**Comment by apitts** [comment]
My vote would be to parameterize the bottom margin as it's likely easier to implement and allows for more flexibility.

**Comment by apitts** [comment]
The option to add padding on either side of the x and y axes would actually be helpful in a number of other charts. I have also experienced the need in the bubble chart and time series chart. I wonder whether it would make the most sense just to have a general padding config across all these chart types as it would solve for all.

**Comment by mistercrunch** [comment]
Fixed here https://github.com/airbnb/caravel/pull/629
