### ISSUE TITLE
Unable to login after system restart

### ISSUE THREAD

**Issue by addresseerajat** [airbnb/caravel#636]
Hello

I have installed caravel on my system using the [installation](http://airbnb.io/caravel/installation.html) guide. All database login credentials and everything is in place. However whenever I restart my system and start caravel server, I am unable to login. 
Whenever I enter login credentials and hit enter, a message appears which says Invalid Login. I have tried this on two different machines (one Ubuntu, and other Mac), and on both the machine, I experienced similar behaviour. As a result, I have to setup caravel again.

Is this a bug, or am I missing something ? 

Thanks

**Comment by apitts** [comment]
By default caravel places the caravel.db database in your tmp folder which is cleared on restart. If you use config.py to change the location of this database then the issue should be resolved.
