### ISSUE TITLE
Does caravel expose a health-check endpoint?

### ISSUE THREAD

**Issue by amancevice** [airbnb/caravel#642]
If not, can it be added?

something like:

```bash
curl http://localhost:8088/health
```

**Comment by mistercrunch** [comment]
Yes, though it pretty much measures whether the web server is up or not.

**Comment by amancevice** [comment]
Sorry, @mistercrunch, but what is the endpoint if it exists? Is it just there login page?

**Comment by mistercrunch** [comment]
It's `/health` and returns "OK"

**Comment by amancevice** [comment]
Oh, well I feel sheepish. Thanks!

**Comment by alanmcruickshank** [comment]
I didn't know about this either so I've submitted a PR to add it to the
documentation.

On Sun, 19 Jun 2016 at 13:02 Alexander Mancevice <notifications@github.com>
wrote:

> Oh, well I feel sheepish. Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/airbnb/caravel/issues/642#issuecomment-226993704>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEdFuH5lLqiARZGXy-WB2h1AbpxanoXdks5qNS_XgaJpZM4I48rj>
> .
>
-- 

_______
Alan Cruickshank
E: alanmcruickshank@gmail.com
T: +44 770 6851825
