### ISSUE TITLE
Installing on fedora, vanilla environment , failing at cryptography 

### ISSUE THREAD

**Issue by bf16574403** [airbnb/caravel#643]
Hi, 

I am following developer instructions, starting clean fedora 23, and have double checked the dependancies,please help, install fails at;

pip install caravel
...
...
```

-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:718:6: error: conflicting types for ‘BIO_new_mem_buf’
     BIO *BIO_new_mem_buf(void *, int);
          ^
    In file included from /usr/include/openssl/asn1.h:65:0,
                     from build/temp.linux-x86_64-2.7/_openssl.c:434:
    /usr/include/openssl/bio.h:692:6: note: previous declaration of ‘BIO_new_mem_buf’ was here
     BIO *BIO_new_mem_buf(const void *buf, int len);
          ^
    build/temp.linux-x86_64-2.7/_openssl.c:2107:15: error: ‘SSLv2_method’ redeclared as different kind of symbol
     SSL_METHOD* (*SSLv2_method)(void) = NULL;
                   ^
    In file included from build/temp.linux-x86_64-2.7/_openssl.c:520:0:
    /usr/include/openssl/ssl.h:2287:19: note: previous declaration of ‘SSLv2_method’ was here
     const SSL_METHOD *SSLv2_method(void); /* SSLv2 */
                       ^
    build/temp.linux-x86_64-2.7/_openssl.c:2108:15: error: ‘SSLv2_client_method’ redeclared as different kind of symbol
     SSL_METHOD* (*SSLv2_client_method)(void) = NULL;
                   ^
    In file included from build/temp.linux-x86_64-2.7/_openssl.c:520:0:
    /usr/include/openssl/ssl.h:2289:19: note: previous declaration of ‘SSLv2_client_method’ was here
     const SSL_METHOD *SSLv2_client_method(void); /* SSLv2 */
                       ^
    build/temp.linux-x86_64-2.7/_openssl.c:2109:15: error: ‘SSLv2_server_method’ redeclared as different kind of symbol
     SSL_METHOD* (*SSLv2_server_method)(void) = NULL;
                   ^
    In file included from build/temp.linux-x86_64-2.7/_openssl.c:520:0:
    /usr/include/openssl/ssl.h:2288:19: note: previous declaration of ‘SSLv2_server_method’ was here
     const SSL_METHOD *SSLv2_server_method(void); /* SSLv2 */
                       ^
    build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_d_EC_GFp_nistp224_method’:
    build/temp.linux-x86_64-2.7/_openssl.c:24869:10: warning: implicit declaration of function ‘EC_GFp_nistp224_method’ [-Wimplicit-function-declaration]
       return EC_GFp_nistp224_method();
              ^
    build/temp.linux-x86_64-2.7/_openssl.c:24869:10: warning: return makes pointer from integer without a cast [-Wint-conversion]
    build/temp.linux-x86_64-2.7/_openssl.c: In function ‘_cffi_f_EC_GFp_nistp224_method’:
    build/temp.linux-x86_64-2.7/_openssl.c:24879:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
       { result = EC_GFp_nistp224_method(); }
                ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cryptography
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-JlmHIk/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Id05gE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-JlmHIk/cryptography/
```

**Comment by xrmx** [comment]
@mistercrunch the cryptography dependency should be bumped to (at least) 1.1.2

**Comment by bf16574403** [comment]
hi xrmx, 

Just did a git clone and made the change you suggested, identical error and failure I am afraid :(

Any other suggestions please let me know, trying to get this working for a demo coming up soon which was to praise caravel functionality.

thanks!

**Comment by mistercrunch** [comment]
Can you try `pip install cryptography` ?

**Comment by jgbarah** [comment]
Hi. I'm running Debian testing, and had a very similar problem. I got a similar error when running `pip install caravel`. After the error, I did run, as you suggest

```
pip install cryptography
```

And I see how cryptography-1.1.4 is installed. But the weird thing is that if I run after that

```
pip install caravel
```

I see that cryptography-1.1.1 is installed once again:

```
(caravel)jgb@expisito:~/venvs$ pip install caravel
Requirement already satisfied (use --upgrade to upgrade): caravel in ./caravel/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): babel==2.3.4 in ./caravel/lib/python2.7/site-packages (from caravel)
Downloading/unpacking cryptography==1.1.1 (from caravel)
  Downloading cryptography-1.1.1.tar.gz (348kB): 348kB downloaded
  Running setup.py (path:/tmp/pip-build-yqz2Om/cryptography/setup.py) egg_info for package cryptography
...
```

And then the same error again, after installing many packages...

Any idea?

**Comment by jgbarah** [comment]
Curiously enough,

```
pip install https://github.com/airbnb/caravel/zipball/master
```

again installs cryptography-1.1.1, but installing from a git clone works!

```
git clone https://github.com/airbnb/caravel.git
cd caravel
pip install -e .
```

So,  maybe there is something with pip that I don't understand, but I can confirm that the current dependencies in the git repo work perfectly (at least with respect to installation).

**Comment by xrmx** [comment]
Il 21/06/2016 23:03, Jesus M. Gonzalez-Barahona ha scritto:
> Curiously enough,
>
> |pip install https://github.com/airbnb/caravel/zipball/master |
>
> again installs cryptography-1.1.1, but installing from a git clone works!
>
> |git clone https://github.com/airbnb/caravel.git cd caravel pip install -e . |
>
> So, maybe there is something with pip that I don't understand, but I can confirm
> that the current dependencies in the git repo work perfectly (at least with
> respect to installation).

The latest master has a different dependency than the latest released version ;)

**Comment by bf16574403** [comment]
Hi all , moving Cryptography 1.3.4 did the trick thank you !!

However, when the server starts, im not getting any response when trying to hit it on its ports.. have double checked he networking..

Could I trouble you for a sample mysql connection string one would use to connect to a mysql db. I am new to sqlalchamy.

At this point in time im willing to pay someone to help me get it going... and connecting to my myql db.

Truly love this project..!

**Comment by xrmx** [comment]
@bf16574403 checkout sqlalchemy docs for the db string and double check the port, are you hitting the right one? Both discussions do not belong to this bug though :)

**Comment by mistercrunch** [comment]
Until the next version, `pip install cryptography==1.4` should do the trick

**Comment by alexandercbooth** [comment]
I had the same issue on Debian, too and cloning then pip installing was the only thing that worked for me. Manually installing different versions of cryptography did not work for me. 
Thanks @jgbarah!

**Comment by bf16574403** [comment]
Basically, if it was not for the dodgy/unstable install and the difficult manner in which data sources are added (as opposed to adding via GUI)  this tool from an analytic and dashboard perspective would be on par with splunk or anything else in the filed..
