### ISSUE TITLE
Implementing self joins for sql alchemy backend

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#654]
i'd like to implement some cohort analysis in caravel like this:
https://www.periscopedata.com/blog/how-to-calculate-cohort-retention-in-sql.html#calculating-retention-of-new-vs-existing-users

Do you think it is feasible? Other than the self join i'll also need a way to assign metrics to another table than the default one. What do you think?

**Comment by mistercrunch** [comment]
The Caravel approach would be to precompute your data a pipeline and point Caravel to the output. We may support many-to-one joins in the future, but self-join seems like a slippery slope.

We are planning on adding a state of the art, integrated SQL editor to Caravel, so some of that more advanced SQL pre-processing could be done in that editor, and then visualized in Caravel.

If you are interested in retention, check out this super-informative video by an ex-Facebook colleague about "Growth Accounting":
https://www.facebook.com/video.php?v=3707283286197

**Comment by xrmx** [comment]
With my actual data pipeline the self join would be quite handy as i have denormalized data. Thanks for the interesting video. Looking forward to the SQL editor then, thanks!
