### ISSUE TITLE
Support IATA airport code to display cities on the world map?

### ISSUE THREAD

**Issue by izzyleung** [airbnb/caravel#656]
Hi, 

I was wondering if you guys will support using the IATA airport code to represent a city and display them onto the world map (probably user will be able to zoom in and out).

I am trying to integrate this function into my dashboard using Google Maps's heatmap, I would be very happy if you guys can help to make it possible to make this function available for Caravel.

Thanks in advance for your reply.

**Comment by mistercrunch** [comment]
You'll need lat/long, but this PR is a good preview of what is to come:
https://github.com/airbnb/caravel/pull/650
