### ISSUE TITLE
Filter widget should highlight targeted widgets on hover

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#659]
With filters widget targeting a set of values for a specific field, some widget can't be affected by the filter. If the widget comes from a dataset that does not have a column by the same name as the filter, or if it is set in the immune_to_filter setting. 

Highlighting which widgets are affected would bring some clarity.

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1439
