### ISSUE TITLE
Time option in FilterBox

### ISSUE THREAD

**Issue by kkalyan** [airbnb/caravel#665]
This is discussed on other issues/comments, adding new issue to track this. 
Current FilterBox does not support Time dimension. It would be nice to have boolean like 
`show time filter`  in FilterBox that would show as two datepickers at the top of the widget.

References. 
https://github.com/airbnb/caravel/issues/499 
https://github.com/airbnb/caravel/issues/363#issuecomment-211705872

**Comment by mistercrunch** [comment]
Yes I agree. How should we deal with many datetime column? Apply the filter across the board?

**Comment by danield9tqh** [comment]
I think being able to filter an entire dashboard by time would be very helpful. In addition to an dashboard-wide filter, each slice could have an option to edit the time interval from the dashboard instead of having to go to the Edit Slice form.

**Comment by kkalyan** [comment]
> How should we deal with dashboard having slices across different datetime columns? 
When the user changes the dashboard time filter, it should propagate the date down to all the slices. Default can be left as whatever the datetime set on the slices.

**Comment by neevany** [comment]
Is this going to be implemented,I think it a important and useful filter to have. When can we expect it.

**Comment by nigeljyng** [comment]
Agreed. A dashboard-wide date/time filter will be really useful! Perhaps let it override individual slices date/time filters?

**Comment by optossav** [comment]
Please add this feature!

**Comment by priteshwatch** [comment]
would love to have this feature, or contribute if necessary.

**Comment by himanshugahlaut** [comment]
Please add this feature! Almost every person using caravel in our company has asked for a dashboard wide time filter.

**Comment by toabey** [comment]
Is it better to create dashboard with a different time granularity and date option ?
with a template of previous dashboards(slices included).

**Comment by priteshwatch** [comment]
@mistercrunch ideally, you want to control Time Granularity and Filters from the dashboard. Typical use case would be show me data for time range with these filters for the whole dashboard. 

If you could point me in the right direction, I am happy to look into it.

**Comment by maver1ck** [comment]
One of the best date pickers I found.
https://github.com/christopheclc/polymer-date-picker

**Comment by mistercrunch** [comment]
https://github.com/airbnb/caravel/pull/1165

**Comment by agfunder** [comment]
I love Caravel, but this item is a real issue for us.  My single biggest problem atm.
Without this feature we are forced to make multiple slices/dashboards for different time periods which is very wasteful, non-DRY.

> Yes I agree. How should we deal with dashboard having slices across different datetime columns? Apply the filter across the board?

Yes please Apply the filter across the board if filter is set.

**Comment by bkyryliuk** [comment]
@agfunder - time filter is implemented.
<img width="1374" alt="screen shot 2016-09-30 at 12 04 03 pm" src="https://cloud.githubusercontent.com/assets/5727938/19003535/2c3ec0dc-8706-11e6-80ec-64ea9e94503c.png">
![Uploading Screen Shot 2016-09-30 at 12.03.56 PM.png…]()

**Comment by panutat** [comment]
I noticed there is some basic cross-filtering implemented (clicking on a row in data table slice) which filters all other slices in the dashboard. Is there a way to add cross-filtering to the line chart time filter widget? perhaps pass the date/time range to the time range fields in the filter slice? This seems to be a feature that many users have asked me about. Thanks!

**Comment by kalarikkalbabu** [comment]
Hi, Is there any way to change the label of Filter_box filters, the column name is coming as filter label, unable to change , please cuggest

**Comment by vschoener** [comment]
I didn't find a answer, but is it possible to select a range of date from the dashboard and not a predefined value of day / hour etc.. ?

**Comment by wuxuedaifu** [comment]
@bkyryliuk where is code for superset time filter shown in the picture? very appreciate
