### ISSUE TITLE
Can you publish a new version to PyPI?

### ISSUE THREAD

**Issue by paulborza** [airbnb/caravel#671]
The latest published version still references cryptography 1.1.1 which won't compile against latest openSSL. The git checked in version depends on cryptography 1.4 and should work. Thanks!

**Comment by xrmx** [comment]
@paulborza FYI you can install caravel with pip from git repository 
```
pip install git+https://github.com/airbnb/caravel.git
```

**Comment by paulborza** [comment]
@xrmx Thanks! I'd still push for updating the package since the official instructions are via `pip install caravel` and lots of people will be confused as to why it's not working.

**Comment by mistercrunch** [comment]
The new version is coming this week for sure.

**Comment by xrmx** [comment]
@mistercrunch this can be closed :)
