### ISSUE TITLE
Flask-AppBuilder has upgraded to 1.8.0

### ISSUE THREAD

**Issue by rocky1001** [airbnb/caravel#679]
According to http://flask-appbuilder.readthedocs.io/en/latest/versionmigration.html#migrating-to-1-8-0 ,
this will fix flask-babel bugs under python 3.5 env.
So, when will caravel upgrade the flask-appbuilder module?

**Comment by xrmx** [comment]
They have released 1.8.1 too

**Comment by mistercrunch** [comment]
Master is pointing to it. We have a big release coming up soon with tons of good stuff.

**Comment by rocky1001** [comment]
@mistercrunch that's REALLY a good news, looking forward to the big release :+1:
