### ISSUE TITLE
installation fails perpectually on ubuntu

### ISSUE THREAD

**Issue by tOlorun** [airbnb/caravel#683]
Please see error below

Thanks in advance

i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-i686-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Q0RSoR/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DXNaJb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Q0RSoR/cffi/

**Comment by xrmx** [comment]
It looks like something needs libffi-dev, care to upload the full log to a pastebin please?

**Comment by deadlocks** [comment]
Try installing `libffi-dev` and make sure `python-dev` package is installed. I was also facing same problem. If you are just evaluating then [try docker image   ](https://hub.docker.com/r/amancevice/caravel/)

**Comment by tOlorun** [comment]
Thanks good fellas

Please here is the paste bin link http://pastebin.com/JQBbs90H

i also intend to use it not just evaluate

Thanks in advance once again

**Comment by tOlorun** [comment]
wow
the install from the git repo worked

thanks everyone

you guys rock. ..

cheers
