### ISSUE TITLE
latest master breaks sqlite

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#687]
*/tablemodelview/list/* raise this exception:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError)
no such column: table_columns.python_date_format 
```

caravel db upgrade:
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 956a063c52b3 -> 1226819ee0e3, Fix wrong constraint on table columns
WARNI [root] Could not find or drop constraint on `columns`
INFO  [alembic.runtime.migration] Running upgrade 1226819ee0e3 -> d8bc074f7aad, Add new field 'is_restricted' to SqlMetric and DruidMetric
/home/rm/caraveltest/venv/lib/python3.4/site-packages/alembic/util/messaging.py:69: UserWarning: Skipping unsupported ALTER for creation of implicit constraint
  warnings.warn(msg)
INFO  [alembic.runtime.migration] Running upgrade d8bc074f7aad -> 960c69cb1f5b, add dttm_format related fields in table_columns
```

**Comment by mistercrunch** [comment]
I don't understand why the sqlite build is working on travis then. Is it a sqlite version problem?

**Comment by xrmx** [comment]
It's an oldish *3.8.7.1*, will try on another machine with *3.13.0*. BTW postgres still hangs on first migration in 0.9.1 here.  And travis is fine there too.

**Comment by mistercrunch** [comment]
Should one add an older version of sqlite and postgres to the build matrix?

**Comment by ascott** [comment]
i just pulled master and i'm getting the same error on `caravel db upgrade`

**Comment by xrmx** [comment]
Upgraded to 0.10.0 and it seems fine. @ascott does 0.10.0 works fine for you too?

**Comment by xrmx** [comment]
@mistercrunch regarding postgres (9.4 here) fab tables are added proprerly it's just the first migrations that hangs.
