### ISSUE TITLE
druid

### ISSUE THREAD

**Issue by guoyangyangyang** [airbnb/caravel#693]
What's the relationship between Druid and caravel?
I'm trying to learn Druid. So I want to know what can I do with druid and caravel?

Thanks a lot.

**Comment by xrmx** [comment]
What about reading the documentation? :)

**Comment by mistercrunch** [comment]
Yeah that's a really vague question that would require writing a long essay to answer. 

The short answer is Caravel allow you to query and consume data out of [amongst other things] Druid.

Please RTFM and ask more specific questions.
