### ISSUE TITLE
Druid : Datasource Link throws sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by yassmarzou** [airbnb/caravel#695]
I followed the [Druid Quickstart](http://druid.io/docs/latest/tutorials/quickstart.html) to setup Druid (0.9.1) on a single machine and load the wikiticker data. The data is successfully loaded and I could query it using Druid.

The datasource is correctly listed in Caravel (0.10.0) but the _Datasource Link_ page gives the following error:
```
sqlalchemy.exc.OperationalError
OperationalError: (sqlite3.OperationalError) no such column: datasource_link [SQL: u'SELECT datasources.created_on AS datasources_created_on, datasources.changed_on AS datasources_changed_on, datasources.id AS datasources_id, datasources.datasource_name AS datasources_datasource_name, datasources.is_featured AS datasources_is_featured, datasources.is_hidden AS datasources_is_hidden, datasources.description AS datasources_description, datasources.default_endpoint AS datasources_default_endpoint, datasources.user_id AS datasources_user_id, datasources.cluster_name AS datasources_cluster_name, datasources."offset" AS datasources_offset, datasources.cache_timeout AS datasources_cache_timeout, datasources.changed_by_fk AS datasources_changed_by_fk, datasources.created_by_fk AS datasources_created_by_fk \nFROM datasources ORDER BY datasource_link asc\n LIMIT ? OFFSET ?'] [parameters: (500, 0)]
```

The datasource page (/caravel/explore/druid/1/) throws an exception : `Exception: No data was returned.`

Any Idea?
Thanks.

**Comment by xrmx** [comment]
Have you upgraded caravel without upgrading the db with *caravel db upgrade*?

**Comment by yassmarzou** [comment]
I didn't upgrade Caravel, I did a a fresh install of Caraval, with a _caravel db upgrade_ as mentioned [here](http://airbnb.io/caravel/installation.html#caravel-installation-and-initialization)

**Comment by mistercrunch** [comment]
I'm guessing there's no data for the data range you queried. 

I'm fixing the column header links as a quickfix.

**Comment by xrmx** [comment]
@mistercrunch isn't it strange that *datasource_link* got in the query though?

**Comment by yassmarzou** [comment]
@mistercrunch  Thank you, how can I get the quickfix in the pip package?
I tried to do a fresh install from the quickfix commit using `pip install git+ssh://git@github.com:airbnb/caravel.git@f407bd45fd118d7d315b18e7f4385422a2beca8e`, but the [welcome page](http://i.imgur.com/gr9D1G6.png) didn't load correctly (got a lot of 404 for the GET requests)

**Comment by yassmarzou** [comment]
As @mistercrunch mentioned, it turned out the problem was with the data range I queried.
I will mark the issue as closed.
