### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by tOlorun** [airbnb/caravel#698]
Please is there anywhere i can get tutorials for a beginner

Part of my concerns are that i want to be able to run caravel from a folder where the files reside and i can set it and customize it further 

The basic info on the setup and installation does not seem to cover this

except iam missing something

please i need someone to help me out

Thanks in advance

yours

**Comment by mistercrunch** [comment]
This isn't 100% up to date but should help you get going:
http://airbnb.io/caravel/tutorial.html
