### ISSUE TITLE
Add function to set label based on sum of column values Mapbox visualization when GROUP BY is presented

### ISSUE THREAD

**Issue by izzyleung** [airbnb/caravel#700]
Currently, the label is set by `COUNT(*)` if a `GROUP BY` clause is presented, or by the aggregation of the numeric columns if there are no `GROUP BY` clause.

However, I want to set the label to be sum of a numeric column when there is a `GROUP BY` clause. 
I cannot manually edit the SQL generated by Caravel, so there is no way to accomplish this function on the interface, I have to request you guys to add this function.

**Comment by izzyleung** [comment]
Found a solution around it, thanks for the wonderful platform guys.

**Comment by CaraWuu** [comment]
Meet the same question,could u plz tell me how u fix this problem? Many thanks.

**Comment by izzyleung** [comment]
@CaraWuu 

I resolved the issue by creating a view in the database, and use the newly created view in Caravel to do the visualization.

You can do the group by in a SQL statement and use that statement to create a view, and thus Caravel will have no problem.

**Comment by CaraWuu** [comment]
OIC,I've tried this before. And now that I found a new way to solve this problem. You can add column or metric from editing table. You can write  simple SQL statement as well, which is pretty cool. Anyway, thx a lot. ^ ^
