### ISSUE TITLE
sunburst: ordering of groupby not preserved on dashboard

### ISSUE THREAD

**Issue by xrmx** [airbnb/caravel#702]
I have a couple of slices with these groupby clauses, they both render fine as invidual slices but once in a dashboard the rendered hierarchy is sorted [''disciplina", "scuola", "tipologia_utente"] 

```
    "groupby": [
        "tipologia_utente",
        "scuola",
        "disciplina"
    ]
```

``` 
    "groupby": [
        "scuola",
        "tipologia_utente",
        "disciplina"
    ],
```
This is with 0.9.1

**Comment by mistercrunch** [comment]
Should be fixed in 0.10.0, can you confirm?

**Comment by xrmx** [comment]
Cannot test, all sunburst are broken for me with newer caravel versions, see #673

**Comment by xrmx** [comment]
Works fine for me on 0.10.0 plus the sunburst fix backported. Thanks!
