### ISSUE TITLE
refresh druid metadata

### ISSUE THREAD

**Issue by birdspring** [airbnb/caravel#708]
##

I've followed the druid tutorial and created a druid cluster on my local computer and loaded some data into the datasource. I tried to load it in caravel, but I cannot see any data in my datasource.
How could I view my data in caravel?
When I refresh druid metadata and hit the datasource"wikiticker", it replies "Please define at least one metric for your table".
This is a screenshot from the druid quickstart.
![screenshot from 2016-07-04 10 24 47](https://cloud.githubusercontent.com/assets/19747498/16549697/5ec34c20-41d4-11e6-9713-49f0b31b02df.png)

Any advice, thanks.

**Comment by birdspring** [comment]
It seems I didn't have the access to this datasource.

**Comment by Laxman-SM** [comment]
Check your historical node configuration. as well as check sql connectivity. i found same issue today and fixed via historical node configuration update.
