### ISSUE TITLE
pip install caravel --upgrade  fail

### ISSUE THREAD

**Issue by chejinye** [airbnb/caravel#709]
when I 
pip install caravel --upgrade 

Cannot remove entries from nonexistent file /home/chejinye/anaconda2/lib/python2.7/site-packages/easy-install.pth

OSError: [Errno 2] nonexistent file: '/home/chejinye/anaconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg'

**Comment by xrmx** [comment]
This looks like more than a broken virtualenv rather than a caravel issue.

**Comment by mistercrunch** [comment]
Yes, not a Caravel problem but an anaconda or virtualenv problem...
