### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by apitts** [airbnb/caravel#714]
A histogram visualisation would be very nice with variable bins...I'm not sure how easy that is to do with nvd3 though....

**Comment by xiaoxisun** [comment]
Same here. Appreciate!

**Comment by katemarielewis** [comment]
yes this would be really useful!

**Comment by shkr** [comment]
I do not see a reference to a branch here. If there is a branch/prior work done on this. I can contribute/collaborate.

**Comment by ascott** [comment]
@shkr i'll be working on this and will post here when it's been added. thx.

**Comment by ascott** [comment]
@shkr knocked this out before i was able to get to it. 🎉 
https://github.com/airbnb/caravel/pull/888
