### ISSUE TITLE
Error about "refresh druid metadata"

### ISSUE THREAD

**Issue by ouoc** [airbnb/caravel#719]
I've followed the druid quickstart manual to deploy a druid cluster on my local machine and started all the services. 
Then I configured the druid cluster in caravel. When I hit refresh druid metadata, the "wikiticker datasource" appeared. 
But as I hit it, the error occurred  "Please define at least one metric".
Any ideas?

**Comment by xrmx** [comment]
This is a dup of #708, please close and subscribe to the other one, thanks.
