### ISSUE TITLE
dist folder is missing in javascript folder

### ISSUE THREAD

**Issue by sbookworm** [airbnb/caravel#723]
After I installed the caravel with master code get from github, I found that there is some problem with the dashboard.
Then I found there is missing the dist folder in static/assets/javascripts.
after I install caravel with pip the problem fixed,
How can I get the latest code?

**Comment by x4base** [comment]
You need build it if you want to install from the source.
You need to run `npm run prod`. See https://github.com/airbnb/caravel/blob/master/CONTRIBUTING.md#setting-up-the-node--npm-javascript-environment

**Comment by sbookworm** [comment]
Thank you very much, I will try that, thanks again
