### ISSUE TITLE
Global custom where clause for dashboard

### ISSUE THREAD

**Issue by katemarielewis** [airbnb/caravel#736]
I would like to be able to create a dashboard with multiple different slices. I have a list of topics that I would like to do this for. Currently in each slice I am using a where statement to specify the topic for the slice. However it would be great if I could do this from the dashboard so that it affects all the slices in the dashboard at once. Then I would be able to easily go from topic to topic by altering only one thing. Is this currently possible? if so how can I do this?

**Comment by georgeke** [comment]
Check out the "Filters" visualization, which exposes columns that you can filter on at a dashboard level that affects all slices.

**Comment by katemarielewis** [comment]
Thank you @georgeke I didn't realize that I needed to make it its own slice with the filter visualization type to get it to show up on the dashboard
