### ISSUE TITLE
Don't show clear text password in databaseview/show

### ISSUE THREAD

**Issue by AndreasMeisingseth** [airbnb/caravel#745]
Seems like https://github.com/airbnb/caravel/pull/355 (accidentally?) got reverted in https://github.com/airbnb/caravel/pull/298

Original issue: https://github.com/airbnb/caravel/issues/354 (I am experiencing this on 0.10.0)

Idea:
Maybe one could use ```show_exclude_columns``` to not show the password, but still show some additional properties such as "Changed By"?

**Comment by ascott** [comment]
thx for the report @AndreasMeisingseth. taking a look at this today.

**Comment by ascott** [comment]
fixed with https://github.com/airbnb/caravel/pull/748

**Comment by AndreasMeisingseth** [comment]
Thanks for the fast reply & PR @ascott
