### ISSUE TITLE
Replace jquery plugin Select2 with react-select

### ISSUE THREAD

**Issue by ascott** [airbnb/caravel#753]
- this will help us get closer to react controls on the explore page

https://github.com/JedWatson/react-select

**Comment by prokh** [comment]
I took a look at the react-select component. As far as I can see, one cannot change the order of the items in a multiselect by drag and drop. Some viz depend on the order. Thus, users have to delete all the items if they decide that the last item should go to the front.

**Comment by ascott** [comment]
assigned this one to you vera, i think we could mark this as done since you've been rewriting the control elements to use react-select

**Comment by vera-liu** [comment]
Awesome!
