### ISSUE TITLE
Error log when the caravel-flask app is started

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#765]
I installed the caravel app as per the instructions provided. Then I start the flask app using this command :

caravel runserver -d

In the logs that are posted I see two issues -

1) This error log is posted

```flask_appbuilder.base:Add Permission on Menu Error: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type. [SQL: u'SELECT ab_view_menu.id AS ab_view_menu_id, ab_view_menu.name AS ab_view_menu_name \nFROM ab_view_menu \nWHERE ab_view_menu.name = ?\n LIMIT ? OFFSET ?'] [parameters: (<flask_babel.speaklater.LazyString object at 0x476b1d0>, 1, 0)]```

2) The index page (`http://localhost:8088/caravel/welcome`) does not load css, js. The other pages are rendered properly.

Here are the logs from the javascript console -
```
/static/assets/node_modules/font-awesome/css/font-awesome.min.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/static/assets/javascripts/dist/css-theme.entry.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/static/assets/javascripts/dist/welcome.entry.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/static/assets/node_modules/font-awesome/css/font-awesome.min.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```
I am looking inside my py virtual environments site-packages directory. Inside /static/assets there are the only directories 

images  javascripts  js_build.sh  package.json  stylesheets  utils  vendor  visualizations  webpack.config.js

Inside the javascripts directory both of the above listed files in the error logs are missing. 

How to solve those two issues ? Is there a relationship between the error log and welcome page not rendered properly ?

**Comment by georgeke** [comment]
Which Caravel version do you have? I just tried a fresh virtualenv with `caravel==0.10.0` and those files seem to be in the site-packages for the env.

**Comment by shkr** [comment]
Yes. I installed caravel again via pip, and I now those files exist both errors are now resolved. I think I had a different version of caravel where the title bar had a black background.
