### ISSUE TITLE
Missing jquery-ui.css file when running npm run dev

### ISSUE THREAD

**Issue by djbobbydrake** [airbnb/caravel#768]
I ran into the following issue when trying to set up the assets in my development environment:
```ERROR in ./javascripts/caravel-select2.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/jquery-ui/themes/base/jquery-ui.css in /Users/{path}/caravel/caravel/assets/javascripts
 @ ./javascripts/caravel-select2.js 5:0-62```

Here were the previous commands that led up to the error:
1. `cd /caravel/assets`
2. `npm install`
3. `npm run dev`

Looking at the `../node_modules/jquery-ui/themes/base` directory, I don't see any jquery-ui.css file present.

Running Caravel 0.10.0 on OS X 10.11.5 with python 2.7.

**Comment by ascott** [comment]
i ran into this problem this week too @djbobbydrake. jquery-ui needs to use version `1.10.5` and not `^1.10.5`.

i've made the change in this PR and should be merging it tonight. https://github.com/airbnb/caravel/pull/762/files#diff-d2817346ce989351d5ea8705329683c9R57

in the meantime, i would `rm -rf /node_modules/jquery-ui` and then `npm i jquery-ui@1.10.5 --save`

**Comment by ascott** [comment]
fix is in master.

**Comment by djbobbydrake** [comment]
Thank you @ascott !!
