### ISSUE TITLE
Does support spark sql

### ISSUE THREAD

**Issue by gaoxuesong** [airbnb/caravel#770]
As we all know, caravel supports druid.
But in my project, we use spark mllib and spark sql. So I want caravel support spark sql.
Does caravel support spark sql? If not, how the druid integrate with hortonworks hdp?

**Comment by xrmx** [comment]
Looks like a dup of https://github.com/airbnb/caravel/issues/241

**Comment by shkr** [comment]
I have replied to question on #241 since I was able to successfully connect caravel to spark sql using dropbox/pyhive.
