### ISSUE TITLE
How to save changes?

### ISSUE THREAD

**Issue by jalonsob** [airbnb/caravel#783]
First, sorry for my english. I have discovered Caravel few days ago and I'm playing with it. I have installed Caravel successfully, and I have played with the examples. Now I want to save some changes but I don't know how to do it (shut down the Caravel server and then turn on again with the last changes). Do I need a caravel_config.py file in my PYTHONPATH to get it?

Some notes: I follow the next steps

```
# Install caravel
pip install caravel

# Create an admin user
fabmanager create-admin --app caravel

# Initialize the database
caravel db upgrade

# Create default roles and permissions
caravel init

# Load some data to play with
caravel load_examples

# Start the web server on port 8088
caravel runserver -p 8088

# To start a development web server, use the -d switch
# caravel runserver -d
```

When I wanna to shut down the caravel server I do ctrl+c in the shell (I use ubuntu). Then I shutdown the laptop, and when I turn on it again I lost all the last changes that I have done.

Any help?

**Comment by x4base** [comment]
See http://airbnb.io/caravel/installation.html#configuration
You have to change the path of the database 
```
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/caravel.db'
```
The path defaults to /tmp/caravel.db, which will be deleted when the server restarts
Change it to somewhere else.

**Comment by xrmx** [comment]
@mistercrunch what do you think of updating default path to the parent dir of runcaravel or similar?

**Comment by jalonsob** [comment]
So, I have to create a caravel_config.py in my PYTHONPATH (that could be "/Library/Python/2.7/", the directory where I have python installed), and then for example I create the next:
```

#---------------------------------------------------------
# Caravel specific config
#---------------------------------------------------------
ROW_LIMIT = 5000
CARAVEL_WORKERS = 16

CARAVEL_WEBSERVER_PORT = 8088
#---------------------------------------------------------

#---------------------------------------------------------
# Flask App Builder configuration
#---------------------------------------------------------
# Your App secret key
SECRET_KEY = '\2\1thisismyscretkey\1\2\e\y\y\h'

# The SQLAlchemy connection string to your database backend
# This connection defines the path to the database that stores your
# caravel metadata (slices, connections, tables, dashboards, ...).
# Note that the connection information to connect to the datasources
# you want to explore are managed directly in the web UI
SQLALCHEMY_DATABASE_URI = 'sqlite://///home/mylaptop/Desktop/caravel.db'

# Flask-WTF flag for CSRF
CSRF_ENABLED = True
```

Another question... what is the use of the secret key? It could be for example...:

`SECRET_KEY = 'aaabbb123'`

?

**Comment by xrmx** [comment]
@jalonsob caravel is a flask app so general flask documentation applies here. Secret key is needed for sessions  http://flask.pocoo.org/docs/0.11/quickstart/#sessions
