### ISSUE TITLE
issue with TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by aibati2008** [airbnb/caravel#787]
the dashboard show the below issue, can anyone have solutions?
![image](https://cloud.githubusercontent.com/assets/10130476/16976171/93d7552a-4e7f-11e6-904d-ec6e33c7516c.png)

`  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1079, in_handle_dbapi_exception
    util.reraise(*exc_info)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 920, in _execute_context
    context)
  File "/root/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 425, in do_execute
    cursor.execute(statement, parameters)

  File "/root/anaconda2/lib/python2.7/site-packages/MySQLdb/cursors.py", line 189, in execute
    query = query % tuple([db.literal(item) for item in args])

TypeError: not enough arguments for format string`

**Comment by tan31989** [comment]
The error is specific to execution of the query that is constructed for querying, could you also provide the kind of dashboard you are trying to build or the slices in there?

**Comment by aibati2008** [comment]
@tan31989 thanks for the reply, acuatlly I met the issues in every slices such as dist_bar, table and line_chart...

![image](https://cloud.githubusercontent.com/assets/10130476/16977189/3ce32070-4e87-11e6-810e-e2bf95702cef.png)

**Comment by aibati2008** [comment]
I'm use v0.9.1 for 3 weeks, but the issue appear suddenly today and it never appear before..

**Comment by aibati2008** [comment]
maybe it's related to I changed the default encoding in some scripts, after I reinstall Caravel it's work fine now..
