### ISSUE TITLE
API Documentation url does not work

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#789]
http://pythonhosted.com/caravel

**Comment by xrmx** [comment]
@shkr have you found that url in the documentation? I don't think caravel documentation has ever been on pythonhosted.org (it's not .com btw).

**Comment by shkr** [comment]
I found the link here https://github.com/airbnb/caravel/blob/master/CONTRIBUTING.md

**Comment by mistercrunch** [comment]
@shkr where did you get that link above so we can clean it up? The actual docs are hosted here:
http://airbnb.io/projects/caravel/
