### ISSUE TITLE
Getting error when setting new user to active

### ISSUE THREAD

**Issue by OElesin** [airbnb/caravel#797]
I get the below error when I enable a new user
```Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/caravel/views.py", line 65, in wraps return f(self, *args, **kwargs) File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps return f(self, *args, **kwargs) File "/usr/lib/python2.7/site-packages/caravel/views.py", line 964, in checkbox model_view_cls = getattr(views, model_view) AttributeError: 'module' object has no attribute 'UserDBModelView'```

Kindly help with this.

**Comment by shkr** [comment]
I have the same issue

**Comment by mistercrunch** [comment]
The problem is with the inline checkbox, in the meantime can you click the `edit` button?

**Comment by OElesin** [comment]
@mistercrunch, Thanks. I can click the edit button. I was also able to set the user to active from the edit profile page. So what can be done to correct the above error?

**Comment by xu-xlucas** [comment]
i have the same issue,

**Comment by rhp4515** [comment]
Checkbox tries to fetch UserDBModelView class from caravel/views.py. One solution is to create a class named UserDBModelView in views.py and inherit original UserDBModelView class from flask_appbuilder.security.views

from flask_appbuilder.security.views import UserDBModelView

class UserDBModelView(UserDBModelView):
    pass

**Comment by bkyryliuk** [comment]
I've seen a similar issue:
<img width="1239" alt="screen shot 2016-09-12 at 10 46 59 am" src="https://cloud.githubusercontent.com/assets/5727938/18446594/e81f673a-78d7-11e6-879e-bb25bae38a26.png">

**Comment by mistercrunch** [comment]
fixed
