### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by dineshcaravel** [airbnb/caravel#799]
Hi All, I am new to caravel, I just finished installing Caravel on my ubunutu machine. I went to the available dashboards and tried to run one. I met with the following error. Any help on how to get oer this error is appreciated.

OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'INSERT INTO logs (action, user_id, dashboard_id, slice_id, json, dttm, dt) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)'] [parameters: ('dashboard', u'1', 2, 0, '{"dashboard_id": 2}', '2016-07-21')]

Thanks!

**Comment by mistercrunch** [comment]
Your db location needs to be somewhere where your can read/write files
