### ISSUE TITLE
When moving Caravel from one machine to another what steps need to be taken ?

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#800]
I did a fresh installation of caravel. Then I copied the caravel.db from one machine to the other. Iisted the location of the caravel.db file in the caravel_config.py.

However the new caravel installation fails to accept logins that were working before.

**Comment by mistercrunch** [comment]
Did you change the secret key? It's required to encrypt/decrypt passwords

**Comment by shkr** [comment]
There was mistake when I copied the ../caravel.db sql-lite database. I copied it and added the path to the caravel_config.py and the machine migration worked perfectly.
