### ISSUE TITLE
fabmanager create-admin --app caravel

### ISSUE THREAD

**Issue by xu-xlucas** [airbnb/caravel#808]
[root@slave1 ~]# fabmanager create-admin --app caravel
/usr/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning

**Comment by xrmx** [comment]
@xu-xlucas  that's a warning from a tool of a different project. It's probably already been fixed so please close this issue.
