### ISSUE TITLE
Role Permissions in Table Properties

### ISSUE THREAD

**Issue by markhahnfeld** [airbnb/caravel#827]
In order to avoid redundant workflow, It would be great to select the roles directly in table properties, instead of adding tables to different roles.

Possible solution: A field in table-properties view where i can select roles that should have access to this particular table.

**Comment by xrmx** [comment]
@markhahnfeld but you don't want to give people who has access to tables a way to see permission no?

**Comment by markhahnfeld** [comment]
@xrmx 

> but you don't want to give people who has access to tables a way to see permissions no?

correct! haven't thought about it before though.

**Comment by xrmx** [comment]
@markhahnfeld please close the bug then  :)

**Comment by markhahnfeld** [comment]
it was actually meant as a feature request.
