### ISSUE TITLE
How to set language of caravel app?

### ISSUE THREAD

**Issue by seanDot7** [airbnb/caravel#845]
I set the LANGUAGE property in caravel_config.py but it doesn't work.

**Comment by mistercrunch** [comment]
Do you not see a little country flag in the Navbar?

**Comment by seanDot7** [comment]
I see, but most contents are still written in English. Is the translation of Chinese still in progress? But I found there is a merge like "Complete Chinese Translation".

**Comment by mistercrunch** [comment]
None of the translations are 100% complete... Not all strings are instrumented (most on the python side, none on the javascript side yet), not all the strings instrumented are translated.

**Comment by xrmx** [comment]
Question has been answered, closing.
