### ISSUE TITLE
String metrics can't display

### ISSUE THREAD

**Issue by Georgepentaho** [airbnb/caravel#846]
when I need to display the no numeric metrics such as the interval time,Caravel will always display NaN, export as csv format file, it can display well.

an example:  I have one report like this
 - user_type | online_time(seconds)  | online_time(MMminSSs readable) 
 ----------- | ----------------------- | ------------------------------------
 new            | 200                            | 3min20s
 old            |  280                             |  4min40s
the report display in Caravel just like this:
 - user_type | online_time(seconds)  | online_time(MMminSSs readable) 
 ----------- | ----------------------- | ------------------------------------
 new            | 200                            | NaN
 old            |  280                             |  NaN
when I export this report to csv by Caravel, this report can show right format right.
I check the page html, it just show problem,the data has transfer to the client page but show NaN, It may be this js script bug(explore.entry.js), it can't show the 3min20s if this is no numeric metric.

**Comment by mistercrunch** [comment]
Non numeric metrics?
