### ISSUE TITLE
Caravel installation and initialization on Windows

### ISSUE THREAD

**Issue by jbanegas** [airbnb/caravel#850]
I'm trying to setup caravel on windows following the airbnb installation steps [(see here)](http://airbnb.io/caravel/installation.html) and I'm lock on the step that Initialize the database with this code: `caravel db upgrade`. When I run it I got this message:

> "Caravel" is not recognized as an internal or external command, program or batch file.

Could someone can help me?

Thanks!

**Comment by xrmx** [comment]
Dup of #333, closing.
