### ISSUE TITLE
eslint doesn't pick .jsx files automatically

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#867]
@ascott I dug a bit into it and couldn't find why the `.jsx` files aren't discovered. I can force eslint to parse the files by passing a CLI arg, but the default command `npm run lint` doesn't get them.

**Comment by ascott** [comment]
i will check this out, thx @mistercrunch

**Comment by ascott** [comment]
@mistercrunch did i see you had a pr in for this, or should i tackle it. i'm a bit late 💤

**Comment by mistercrunch** [comment]
solved
