### ISSUE TITLE
How to change appearance of caravel?

### ISSUE THREAD

**Issue by jalonsob** [airbnb/caravel#877]
Hello again. I have been playing with caravel this days. I can create my own dashboards and my own widgets with a remote database. This tool is great, but now I want to present this dashboard to other people. Is there any possibility to change the aparience of my html? I would like to changes things like the logo or the name of my server, that by default is called Caravel.

**Comment by xrmx** [comment]
@jalonsob just change the html? :) I don't think there's currently a way to drop a template in a dir and get that take precedence over the default one.

**Comment by mistercrunch** [comment]
@jalonsob much of the bootstrap theme is here:
https://github.com/airbnb/caravel/blob/master/caravel/assets/stylesheets/less/variables.less

You'll have to maintain a fork with your changes, which should be pretty straightforward.

I'm open to parameterizing the name and logo in `config.py` is you want to send a PR that does that.

**Comment by xrmx** [comment]
Question answered, closing.
