### ISSUE TITLE
How to stop/restart the service after run 'caravel runserver'

### ISSUE THREAD

**Issue by hongqp** [airbnb/caravel#882]
Caravel is a great tool.It's working well on my ubuntu14.
But when I want to stop/restart the caravel,I find nothing on the caraveldocumentation.
Could anyone pls kindly to tell me how to do it?

**Comment by hongqp** [comment]
Thanks tan31989.
By the way, if I change some files ,Caravel can use the lastest files automatically?(like config.py)

**Comment by xrmx** [comment]
@hongqp nope, you have to restart. Please close the issue then :)
