### ISSUE TITLE
flask-appbuilder dependency out of date for Python3

### ISSUE THREAD

**Issue by EricSchles** [airbnb/caravel#891]
Hello all,

I received the following error:

Was unable to import caravel Error: make_declarative_base() takes 1 positional argument but 2 were given

Until I did:

`sudo pip3 install flask-appbuilder`

which resolved things.

**Comment by mistercrunch** [comment]
I'd strongly recommend using virutalenv. From seeing that `sudo` I'm guessing your python environment has some conflicting versions/ incompatible history.

Python isn't great at managing "diamond dependencies" (when 2 different packages need different version of a the same package). Knowing this, it makes a lot of sense to use virtualenv to keep insulated Python environment for each project.

**Comment by xrmx** [comment]
Closing after b48101ca51da8bd07608ccdbd9912efb2000cd0b
