### ISSUE TITLE
caravel db upgrade requires sudo on ubuntu

### ISSUE THREAD

**Issue by EricSchles** [airbnb/caravel#892]
When running installation,

`caravel db upgrade` throws a non-obvious error

However with sudo it works just fine!

**Comment by mistercrunch** [comment]
The error message is infinitely more non-obvious if you don't paste it here... Though this sounds like it's specific to your environment (did you not install in a virutalenv?).

**Comment by xrmx** [comment]
Closing after b48101ca51da8bd07608ccdbd9912efb2000cd0b
