### ISSUE TITLE
Associate entry files to version number

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#898]
When rolling new JS/CSS versions, we sometimes have to force-refresh to get the full update. Sometimes the CSS takes effect while some of the JS doesn't or vice-versa.

To prevent this we may want to version the entry files and all references to them to force a fresh load when rolling out new entry points.

@ascott  @williaster, any simpler way to achieve this?

**Comment by ascott** [comment]
we should be able to handle this in the webpack build process afaik.

**Comment by vera-liu** [comment]
https://github.com/airbnb/caravel/pull/1060

**Comment by ascott** [comment]
nice work @vera-liu !
