### ISSUE TITLE
How to connect caravel to a CAS/SSO system？

### ISSUE THREAD

**Issue by Jackeriss** [airbnb/caravel#925]
I want to connect caravel to our company's SSO system, how to realize that?

**Comment by xrmx** [comment]
Like everything else: look at doc, look at the code, try to understand it and poke at it until it works :)

**Comment by Jackeriss** [comment]
@xrmx I tried，but I can't find it. I'm a new hand，could you please give me some instructions?

**Comment by xrmx** [comment]
@Jackeriss There's no instructions, be the one who write them :) BTW you already sorted out that auth is managed by flask-appbuilder so you have to sort thing out with them i think.

**Comment by Jackeriss** [comment]
@xrmx I realized it, thank you :)
