### ISSUE TITLE
remove extra dashboard title column (last column) on /caravel/welcome

### ISSUE THREAD

**Issue by ascott** [airbnb/caravel#931]
remove extra dashboard title column (last column) on /caravel/welcome

<img width="1272" alt="screenshot 2016-08-11 14 01 34" src="https://cloud.githubusercontent.com/assets/130878/17604740/fbc703e4-5fcb-11e6-9583-0db717084af2.png">

**Comment by KrishMunot** [comment]
Which file is this from? Can you paste a link to its path here? 
Thanks!

**Comment by ascott** [comment]
@vera-liu fixed this up! first pr on caravel 🎉 💯!
