### ISSUE TITLE
caravel/sql/1/?table_name= not rendering sql.html beacuse of jQuery is not defined

### ISSUE THREAD

**Issue by rhp4515** [airbnb/caravel#935]
select2.js?1b82*:39 Uncaught ReferenceError: jQuery is not defined

**Comment by xrmx** [comment]
Which version? How are you serving static files?

**Comment by rhp4515** [comment]
Most recent commit from the master branch. Statics files are served after unpacking using `npm run prod`

**Comment by xrmx** [comment]
@rhp4515 have you tried `rm -rf node_modules && npm install` again?
