### ISSUE TITLE
npm run prod ERROR:

### ISSUE THREAD

**Issue by PickLiDan** [airbnb/caravel#937]
ERROR in ./javascripts/caravel-select2.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/jquery-ui/themes/base/jquery-ui.css in $SOFTHOME/caravel_install/caravel/caravel/assets/javascripts
 @ ./javascripts/caravel-select2.js 5:0-62

What shall I do?

**Comment by PickLiDan** [comment]
解决：
1、 vi caravel/assets/package.json 

"jquery-ui": "^1.10.5",  ->  "jquery-ui": "1.10.5",

2、To install third party libraries defined in package.json, run the following within the caravel/assets/ directory which will install them in a new node_modules/ folder within assets/.

npm install

3、To parse and generate bundled files for caravel, run either of the following commands. The dev flag will keep the npm script running and re-run it upon any changes within the assets directory.

# Compiles the production / optimized js & css
npm run prod


done!!!!  :)

**Comment by xrmx** [comment]
@PickLiDan It's already fixed in master.
