### ISSUE TITLE
Can't get Caravel to work Ubuntu 16.04

### ISSUE THREAD

**Issue by hadyrashwan** [airbnb/caravel#940]
when trying to create an admin 
`fabmanager: command not found` 

I suppose I installed all the dependency
` pip install caravel
Requirement already satisfied (use --upgrade to upgrade): caravel in /home/hady/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pandas==0.18.1 in /home/hady/.local/lib/python2.7/site-packages (from caravel)`

and  
`
build-essential is already the newest version (12.1ubuntu2).
libffi-dev is already the newest version (3.2.1-4).
python-dev is already the newest version (2.7.11-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.1).
python-pip is already the newest version (8.1.1-2ubuntu0.1).
The following packages were automatically installed and are no longer required:
  libosgearth3 libosgearthannotation3 libosgearthfeatures3 libosgearthqt3 libosgearthsymbology3 libosgearthutil3 libqgis-analysis2.8.6
  libqgis-core2.8.6 libqgis-gui2.8.6 libqgis-networkanalysis2.8.6 libqgis-server2.8.6 libqgisgrass2.8.6 libqgispython2.8.6
  linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic linux-headers-4.4.0-22 linux-headers-4.4.0-22-generic linux-headers-4.4.0-24
  linux-headers-4.4.0-24-generic linux-headers-4.4.0-28 linux-headers-4.4.0-28-generic linux-image-4.4.0-21-generic linux-image-4.4.0-22-generic
  linux-image-4.4.0-24-generic linux-image-4.4.0-28-generic linux-image-extra-4.4.0-21-generic linux-image-extra-4.4.0-22-generic
  linux-image-extra-4.4.0-24-generic linux-image-extra-4.4.0-28-generic linux-signed-image-4.4.0-21-generic linux-signed-image-4.4.0-22-generic
  linux-signed-image-4.4.0-24-generic linux-signed-image-4.4.0-28-generic openjdk-9-jdk-headless
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
`

`Linux hady-Lenovo-Z580 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by xrmx** [comment]
You don't have the bin dir inside ./local in your path. Said that (as every other python project) we recommend to create a virtualenv and install caravel in it. See  https://github.com/airbnb/caravel/blob/master/docs/installation.rst#python-virtualenv

**Comment by hadyrashwan** [comment]
ur comment solved my issue can u put that link instead of http://airbnb.io/caravel/installation.html that is in the read file both got the same content anyway except virtualenv part as far as I can tell  so it can help others .
