### ISSUE TITLE
how to format my Dttm  fields to %Y%m%d

### ISSUE THREAD

**Issue by PickLiDan** [airbnb/caravel#944]
i want  format my Dttm  fields to  %Y%m%d  , but i don't know how to set it   help help

**Comment by PickLiDan** [comment]
sql is  ds <= '2016-08-15 16:41:25.000000'   
but i want is ds <='20160815' 
help help

**Comment by xrmx** [comment]
what kind of datasource is that?

**Comment by PickLiDan** [comment]
in  version 0.8.0  i cannot do it
but in version 0.10.0  i can do it by set "Datetime Format" in "Edit Table Column"

**Comment by littlebeandog** [comment]
so how should it word, i put '%Y%m%d' in `Datetime Format`, but it didn't work...

**Comment by yanghaogn** [comment]
+1, can anyone supply a patch to change time column according to 'Datetime Format '
