### ISSUE TITLE
Document that mapbox visualization requires MAPBOX_API_KEY 

### ISSUE THREAD

**Issue by jalonsob** [airbnb/caravel#952]
Hi, I have been playing with new data for Caravel and It representation of data with the widget "Mapbox".

My data consist in a group of entries with an hour and each one has a coordinate LON-LAT (Float), each one with an unique and primary key. I thing that It could be a good example to get something like your example in this page:

https://camo.githubusercontent.com/59348346953e951d5895e12eb743a307402c01bf/687474703a2f2f692e696d6775722e636f6d2f42655574437a462e706e67

But when I want to draw the map in the tables explore section, I get the next errors:

 all_columns_y: Not a valid choice 
 all_columns_x: Not a valid choice 
 mapbox_style: Not a valid choice 

And the map has never been drawn.

On the other hand, when I want to get the visualitations of your example in main.db called MAPBOX LONG/LAT I only can get the bubbles but the map dont draw anything and It continues loading for the eternity. I get the next:

![problem](https://cloud.githubusercontent.com/assets/8788572/17690116/c9040744-638c-11e6-9814-8806ef06ca9e.png)

So... what could be the problem? I am using OS X 10.10.5 and Caravel 0.10.0.

In other way I would like to suggest a new widget of mapping that does not depends on time data. It could be more easy than we have now.

**Comment by xrmx** [comment]
@jalonsob what does the js says? Do you have MAPBOX_API_KEY set in your config?

**Comment by jalonsob** [comment]
My browser's js console says:

Error: An API access token is required to use Mapbox GL

You are right I need MAPBOX_API_KEY in my configuration. How can I get it?

**Comment by xrmx** [comment]
@jalonsob i suppose you just need to create an account on mapbox :)

**Comment by jalonsob** [comment]
It works! Thank you very much! I needed an api key.

**Comment by yamyamyuo** [comment]
create an account in website  https://www.mapbox.com/
and find the api token in your account. That's it!

**Comment by suyile** [comment]
Could some one tell me how to config the API token, I now have the api token but have no idea about where to paste this token number ?

**Comment by yamyamyuo** [comment]
@suyile paste the API in over here https://github.com/apache/incubator-superset/blob/master/superset/config.py#L274

**Comment by malazbw** [comment]
Hi, is it possible to make it without  api token
