### ISSUE TITLE
npm install hangs

### ISSUE THREAD

**Issue by dodoshi** [airbnb/caravel#954]
npm install hangs for a long time with below info:
⸨    ░░░░░░░░░░░░░░⸩ ⠙ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/topojson

npm version is 3.10.5, node version is 6.3.1.

**Comment by xrmx** [comment]
It could be a network issue on your side, a network issue on npm side or whatever in between. Anyway we can't do much about that, sorry :)

**Comment by xrmx** [comment]
It looks like npm had some issue this morning (CET), so please retry and if it works, just close the bug.
