### ISSUE TITLE
Suggestion about tables.

### ISSUE THREAD

**Issue by jalonsob** [airbnb/caravel#958]
I have seen that the name of each table for our dashboard is called with the same name like the original db. For example, if I have a table of a database called "source" and I want to use this table in Caravel I have to call it with the same name. It is saved in my caravel.db situated in the path indicated in caravel_config.py. But we can have a problem that I am having now. If I have two differents databases that I wanna use in caravel, and this databases use a table with the same name, I cant have the two tables of differents databases in two differents tables in Caravel. I think that it could be a good change to add a new column in "Tables" section called "name" to have two differents tables from differents databases but with the same name in each original database.

Now if we try to do this we get the next error in Caravel:

 Integrity error, probably unique constraint 

![error](https://cloud.githubusercontent.com/assets/8788572/17708048/7ab4d954-63e3-11e6-8aaa-087e558dd24a.png)

**Comment by xrmx** [comment]
That's what verbose_name is for in the table model

**Comment by jalonsob** [comment]
I am using Caravel 0.10.0. And the database in the caravel_config.py is:

SQLALCHEMY_DATABASE_URI = 'sqlite:///.../caravel.db'

**Comment by xrmx** [comment]
Closing then, feel free to reopen if doesn't work in the next release.
