### ISSUE TITLE
bootstrap-toggle is missing in package.json

### ISSUE THREAD

**Issue by mahedi0244** [airbnb/caravel#959]
I was trying to set up caravel development environment and after doing "npm install" when I ran "npm run dev", I got the following error:

ERROR in ./javascripts/explore/explore.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../node_modules/bootstrap-toggle/js/bootstrap-toggle.min.js in /Users/lvfrswty/caravel_dev/caravel/caravel/assets/javascripts/explore
 @ ./javascripts/explore/explore.jsx 33:0-73

**Comment by ascott** [comment]
sorry about this. my bug. getting a fix together now.

**Comment by ascott** [comment]
fixed!
