### ISSUE TITLE
fix truncated axis labels

### ISSUE THREAD

**Issue by ascott** [airbnb/caravel#961]
<img width="413" alt="screenshot 2016-08-16 11 26 39" src="https://cloud.githubusercontent.com/assets/130878/17710865/19acc764-63a4-11e6-9281-4eeb4e5a77f4.png">

**Comment by mistercrunch** [comment]
It's not perfect, but the `Bottom Margin` parameter allows users to give more room for the axis.

**Comment by ascott** [comment]
there should be a programmatic way to tell if the labels are too long for the container, and adjust margins or labels as needed.
