### ISSUE TITLE
can Caravel support pyhive? how to write Its Sqlalchemy Uri?

### ISSUE THREAD

**Issue by PickLiDan** [airbnb/caravel#966]
caravel  支持 pyhive吗？ 它的Sqlalchemy Uri怎么写？
can Caravel support pyhive? how to write Its Sqlalchemy Uri?

**Comment by mistercrunch** [comment]
Yes though Presto provides a much better experience than Hive itself. Refer to pyhive's docs for URL format.

**Comment by birdspring** [comment]
@PickLiDan  hive://ip:10000. It still needs a few other dependencies.
