### ISSUE TITLE
Building caravel from master throws error in javascript console

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#980]
```dashboard.entry.js:71 Uncaught Error: Cannot find module "react-map-gl"```

**Comment by xrmx** [comment]
What command is "building"? :)

**Comment by shkr** [comment]
Oops. I meant after building. This is the sequence of commands.


```
pushd caravel/assets
npm install
python setup.py sdist
pip install dist/caravel-0.10.0.tar.gz
caravel runserver -d
```

When I visit the dashboard on caravel, this error is thrown in the javascript console.

```
dashboard.entry.js:71 Uncaught Error: Cannot find module "react-map-gl"
````

**Comment by mistercrunch** [comment]
You forgot `npm run prod` after `npm install`
