### ISSUE TITLE
Error in Histogram

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#982]
This error is thrown by histogram.js.

```
explore.entry.js:61377 Uncaught TypeError: Cannot read property 'category21' of undefined
```

Relevant code in histogram.js

```
const px = window.px || require('../javascripts/modules/caravel.js')
...





....

function(d) { return px.color.category21(d.length); })
````

**Comment by xrmx** [comment]
@shkr care to cook a patch? It should be something like this https://github.com/airbnb/caravel/commit/e243a14c64c97f81e205037bb11bcd9170c17163#diff-dfea42de2be6be52c71f766780861c3cL3
