### ISSUE TITLE
after excute js_build.sh    the slice can not display

### ISSUE THREAD

**Issue by lihemin** [airbnb/caravel#983]
follow is  log of  excute  js_build.sh 
how can i handle it 
thanks

Condition always false [./~/style-loader!./~/css-loader!./visualizations/filter_box.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/filter_box.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/filter_box.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/heatmap.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/heatmap.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/heatmap.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/horizon.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/horizon.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/horizon.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/nvd3_vis.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/nvd3_vis.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/nvd3_vis.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/parallel_coordinates.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/parallel_coordinates.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/parallel_coordinates.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/pivot_table.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/pivot_table.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/pivot_table.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/sankey.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/sankey.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/sankey.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/sunburst.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/sunburst.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/sunburst.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/table.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/table.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/table.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/treemap.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/treemap.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/treemap.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./visualizations/world_map.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./visualizations/world_map.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./visualizations/world_map.css:7,0]
Condition always true [./~/cal-heatmap/cal-heatmap.min.js:8,389]
Condition always true [./~/cal-heatmap/cal-heatmap.min.js:9,13609]
Dropping unused variable selected [./~/select2/select2.js:2288,0]
Dropping unused variable showSearchInput [./~/select2/select2.js:2382,0]
Dropping unused variable data [./~/select2/select2.js:2855,0]
Condition always false [./~/style-loader!./~/css-loader!./~/cal-heatmap/cal-heatmap.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/cal-heatmap/cal-heatmap.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/cal-heatmap/cal-heatmap.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/jquery-ui/themes/base/jquery-ui.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/jquery-ui/themes/base/jquery-ui.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/jquery-ui/themes/base/jquery-ui.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/select2-bootstrap-css/select2-bootstrap.min.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/select2-bootstrap-css/select2-bootstrap.min.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/select2-bootstrap-css/select2-bootstrap.min.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/select2/select2.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/select2/select2.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/select2/select2.css:7,0]
Side effects in initialization of unused variable g [./vendor/parallel_coordinates/d3.parcoords.js:624,8]
Side effects in initialization of unused variable rad [./vendor/parallel_coordinates/d3.parcoords.js:1789,8]
Side effects in initialization of unused variable deg [./vendor/parallel_coordinates/d3.parcoords.js:1796,8]
Dropping unused function paths [./vendor/parallel_coordinates/d3.parcoords.js:553,11]
Side effects in initialization of unused variable line [./vendor/parallel_coordinates/d3.parcoords.js:68,6]
Dropping unused variable clusterCentroids [./vendor/parallel_coordinates/d3.parcoords.js:73,6]
Side effects in initialization of unused variable perimeter [./~/d3-cloud/index.js:102,0]
Condition always true [./~/d3-cloud/~/d3-dispatch/build/d3-dispatch.js:2,0]
Condition always true [./~/d3-sankey/build/d3-sankey.js:2,0]
Dropping unused function moveSourcesRight [./~/d3-sankey/build/d3-sankey.js:141,0]
Condition always true [./~/d3-sankey/~/d3-arrays/build/d3-arrays.js:2,0]
Condition always true [./~/d3-sankey/~/d3-interpolate/build/d3-interpolate.js:2,0]
Condition always true [./~/d3-sankey/~/d3-interpolate/~/d3-color/build/d3-color.js:2,0]
Condition always true [./~/d3-tip/index.js:7,0]
Dropping unreachable code [./~/d3-tip/index.js:10,3]
Dropping unused variable hoverover [./~/datamaps/dist/datamaps.all.js:222,0]
Side effects in initialization of unused variable hoverover [./~/datamaps/dist/datamaps.all.js:309,0]
Side effects in initialization of unused variable svg [./~/datamaps/dist/datamaps.all.js:324,0]
Dropping unused variable that [./~/datamaps/dist/datamaps.all.js:12441,0]
Side effects in initialization of unused variable geo [./~/datamaps/dist/datamaps.all.js:12474,0]
Condition always true [./~/datamaps/dist/datamaps.all.js:12540,0]
Dropping unreachable code [./~/datamaps/dist/datamaps.all.js:12545,0]
Dropping unused variable svg [./~/datamaps/dist/datamaps.all.js:2,0]
Condition always true [./~/mustache/mustache.js:11,3]
Dropping unreachable code [./~/mustache/mustache.js:14,0]
Condition always true [./~/nvd3/build/nv.d3.js:145,0]
Dropping unused variable _self [./~/nvd3/build/nv.d3.js:1168,0]
Side effects in initialization of unused variable gEnter [./~/nvd3/build/nv.d3.js:1588,0]
Side effects in initialization of unused variable wrapEnter [./~/nvd3/build/nv.d3.js:2010,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:2291,0]
Side effects in initialization of unused variable x0 [./~/nvd3/build/nv.d3.js:2531,0]
Dropping unused variable w0 [./~/nvd3/build/nv.d3.js:2555,0]
Dropping unused variable xp0 [./~/nvd3/build/nv.d3.js:2557,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:2756,0]
Dropping unused variable w0 [./~/nvd3/build/nv.d3.js:2797,0]
Dropping unused variable w1 [./~/nvd3/build/nv.d3.js:2798,0]
Side effects in initialization of unused variable lines [./~/nvd3/build/nv.d3.js:3044,0]
Side effects in initialization of unused variable rects [./~/nvd3/build/nv.d3.js:3052,0]
Dropping unused variable transitionDuration [./~/nvd3/build/nv.d3.js:3191,0]
Side effects in initialization of unused variable g [./~/nvd3/build/nv.d3.js:3880,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:4123,0]
Side effects in initialization of unused variable availableLength [./~/nvd3/build/nv.d3.js:4372,0]
Side effects in initialization of unused variable gEnter [./~/nvd3/build/nv.d3.js:4390,0]
Dropping unused variable domain [./~/nvd3/build/nv.d3.js:4351,0]
Side effects in initialization of unused variable gEnter [./~/nvd3/build/nv.d3.js:4528,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:6862,0]
Dropping unused variable endFn [./~/nvd3/build/nv.d3.js:7449,0]
Side effects in initialization of unused variable barsEnter [./~/nvd3/build/nv.d3.js:7614,0]
Side effects in initialization of unused variable defsEnter [./~/nvd3/build/nv.d3.js:8413,0]
Side effects in initialization of unused variable g [./~/nvd3/build/nv.d3.js:8415,0]
Dropping unused variable delay [./~/nvd3/build/nv.d3.js:8330,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:8755,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:9087,0]
Dropping unused function resetBrush [./~/nvd3/build/nv.d3.js:10225,0]
Dropping unused function resetDrag [./~/nvd3/build/nv.d3.js:10230,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:10373,0]
Side effects in initialization of unused variable dimensionTooltip [./~/nvd3/build/nv.d3.js:10318,0]
Dropping unused variable controlWidth [./~/nvd3/build/nv.d3.js:10332,0]
Dropping unused function angle [./~/nvd3/build/nv.d3.js:10926,0]
Side effects in initialization of unused variable paths [./~/nvd3/build/nv.d3.js:10789,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:11080,0]
Side effects in initialization of unused variable vPointClips [./~/nvd3/build/nv.d3.js:11490,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:11880,0]
Side effects in initialization of unused variable gEnter [./~/nvd3/build/nv.d3.js:12228,0]
Side effects in initialization of unused variable g [./~/nvd3/build/nv.d3.js:12229,0]
Dropping unused variable yDistMax [./~/nvd3/build/nv.d3.js:13247,0]
Dropping unused function arcTweenData [./~/nvd3/build/nv.d3.js:13564,0]
Dropping unused variable that [./~/nvd3/build/nv.d3.js:13688,0]
Side effects in initialization of unused variable id [./~/nvd3/build/nv.d3.js:13656,0]
Condition always false [./~/style-loader!./~/css-loader!./~/nvd3/build/nv.d3.min.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/nvd3/build/nv.d3.min.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/nvd3/build/nv.d3.min.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./vendor/parallel_coordinates/d3.parcoords.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./vendor/parallel_coordinates/d3.parcoords.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./vendor/parallel_coordinates/d3.parcoords.css:7,0]
Condition always true [./~/topojson/build/topojson.js:2,0]

WARNING in sql.entry.js from UglifyJs
Side effects in initialization of unused variable jQuery [./javascripts/sql.js:2,4]
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always true [./~/d3/d3.js:9553,0]
Dropping unreachable code [./~/d3/d3.js:9553,75]
Condition always true [./~/jquery/dist/jquery.js:9778,0]
Condition always true [./~/datatables.net-bs/js/dataTables.bootstrap.js:14,0]
Dropping unreachable code [./~/datatables.net-bs/js/dataTables.bootstrap.js:20,0]
Condition always false [./~/style-loader!./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css:7,0]
Condition always true [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:30,0]
Dropping unreachable code [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:36,0]
Dropping unused variable cell [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2227,0]
Dropping unused variable nTd [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2385,0]
Dropping unused variable sThisType [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2385,0]
Dropping unused variable o [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2952,0]
Dropping unused variable kLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3268,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3374,0]
Dropping unused variable iLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3374,0]
Dropping unused variable n [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3374,0]
Side effects in initialization of unused variable iOpenRows [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3379,0]
Dropping unused variable jLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3703,0]
Side effects in initialization of unused variable n [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:4178,0]
Dropping unused variable width [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5500,0]
Dropping unused variable outerWidth [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5500,0]
Dropping unused variable iLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5816,0]
Dropping unused variable aiOrig [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5818,0]
Dropping unused variable l [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5981,0]
Dropping unused variable j [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable jLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable k [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable kLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable sDataType [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5889,0]
Dropping unused variable nTh [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5889,0]
Side effects in initialization of unused variable aoColumns [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5893,0]
Dropping unused variable aDataSort [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable data [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable iCol [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable sType [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable oSort [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:14448,0]
Dropping unused variable j [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable jLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable k [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable kLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable j [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7137,0]
Dropping unused variable jen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7137,0]
Dropping unused variable inner [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7138,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7809,0]
Dropping unused variable ien [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7809,0]
Dropping unused variable row [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:8454,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:9223,0]
Dropping unused variable selected [./~/select2/select2.js:2288,0]
Dropping unused variable showSearchInput [./~/select2/select2.js:2382,0]
Dropping unused variable data [./~/select2/select2.js:2855,0]
Condition always false [./~/style-loader!./~/css-loader!./~/jquery-ui/themes/base/jquery-ui.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/jquery-ui/themes/base/jquery-ui.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/jquery-ui/themes/base/jquery-ui.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/select2-bootstrap-css/select2-bootstrap.min.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/select2-bootstrap-css/select2-bootstrap.min.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/select2-bootstrap-css/select2-bootstrap.min.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./~/select2/select2.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/select2/select2.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/select2/select2.css:7,0]
Dropping unused function isPrimitive [./~/brace/index.js:905,0]
Dropping unused function toPrimitive [./~/brace/index.js:916,0]
Side effects in initialization of unused variable dom [./~/brace/index.js:2387,0]
Side effects in initialization of unused variable event [./~/brace/index.js:2388,0]
Side effects in initialization of unused variable useragent [./~/brace/index.js:2389,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:2645,0]
Side effects in initialization of unused variable old [./~/brace/index.js:3433,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:3604,0]
Non-strict equality against boolean: != true [./~/brace/index.js:4094,0]
Non-strict equality against boolean: != true [./~/brace/index.js:4094,0]
Dropping unreachable code [./~/brace/index.js:5803,0]
Side effects in initialization of unused variable sel [./~/brace/index.js:5848,0]
Dropping unused function throwDeltaError [./~/brace/index.js:6027,0]
Dropping unused function positionInDocument [./~/brace/index.js:6032,0]
Dropping unused function validateDelta [./~/brace/index.js:6037,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:6718,0]
Side effects in initialization of unused variable afterEnd [./~/brace/index.js:7257,0]
Side effects in initialization of unused variable consumedFolds [./~/brace/index.js:7262,0]
Side effects in initialization of unused variable Range [./~/brace/index.js:7194,0]
Non-strict equality against boolean: != false [./~/brace/index.js:9994,0]
Non-strict equality against boolean: == true [./~/brace/index.js:10206,0]
Non-strict equality against boolean: != false [./~/brace/index.js:10207,0]
Non-strict equality against boolean: == false [./~/brace/index.js:10231,0]
Non-strict equality against boolean: == false [./~/brace/index.js:10248,0]
Dropping unused function last [./~/brace/index.js:11349,0]
Side effects in initialization of unused variable end [./~/brace/index.js:12017,0]
Non-strict equality against boolean: != false [./~/brace/index.js:14087,0]
Side effects in initialization of unused variable useragent [./~/brace/index.js:13676,0]
Non-strict equality against boolean: == true [./~/brace/index.js:17373,0]
Side effects in initialization of unused variable oop [./~/brace/index.js:18045,0]
Side effects in initialization of unused variable Range [./~/brace/index.js:18047,0]
Side effects in initialization of unused variable Range [./~/brace/mode/sql.js:84,0]
Condition always false [./~/style-loader!./~/css-loader!./stylesheets/sql.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./stylesheets/sql.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./stylesheets/sql.css:7,0]

WARNING in welcome.entry.js from UglifyJs
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always true [./~/d3/d3.js:9553,0]
Dropping unreachable code [./~/d3/d3.js:9553,75]
Condition always true [./~/jquery/dist/jquery.js:9778,0]
Condition always true [./~/datatables.net-bs/js/dataTables.bootstrap.js:14,0]
Dropping unreachable code [./~/datatables.net-bs/js/dataTables.bootstrap.js:20,0]
Condition always false [./~/style-loader!./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/datatables-bootstrap3-plugin/media/css/datatables-bootstrap3.css:7,0]
Condition always true [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:30,0]
Dropping unreachable code [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:36,0]
Dropping unused variable cell [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2227,0]
Dropping unused variable nTd [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2385,0]
Dropping unused variable sThisType [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2385,0]
Dropping unused variable o [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:2952,0]
Dropping unused variable kLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3268,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3374,0]
Dropping unused variable iLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3374,0]
Dropping unused variable n [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3374,0]
Side effects in initialization of unused variable iOpenRows [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3379,0]
Dropping unused variable jLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:3703,0]
Side effects in initialization of unused variable n [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:4178,0]
Dropping unused variable width [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5500,0]
Dropping unused variable outerWidth [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5500,0]
Dropping unused variable iLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5816,0]
Dropping unused variable aiOrig [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5818,0]
Dropping unused variable l [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5981,0]
Dropping unused variable j [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable jLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable k [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable kLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5888,0]
Dropping unused variable sDataType [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5889,0]
Dropping unused variable nTh [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5889,0]
Side effects in initialization of unused variable aoColumns [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5893,0]
Dropping unused variable aDataSort [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable data [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable iCol [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable sType [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable oSort [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:5894,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:14448,0]
Dropping unused variable j [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable jLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable k [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable kLen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:878,0]
Dropping unused variable j [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7137,0]
Dropping unused variable jen [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7137,0]
Dropping unused variable inner [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7138,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7809,0]
Dropping unused variable ien [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:7809,0]
Dropping unused variable row [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:8454,0]
Dropping unused variable i [./~/datatables.net-bs/~/datatables.net/js/jquery.dataTables.js:9223,0]
Condition always true [./~/cal-heatmap/cal-heatmap.min.js:8,389]
Condition always true [./~/cal-heatmap/cal-heatmap.min.js:9,13609]
Condition always false [./~/style-loader!./~/css-loader!./~/cal-heatmap/cal-heatmap.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/cal-heatmap/cal-heatmap.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/cal-heatmap/cal-heatmap.css:7,0]
Condition always false [./~/style-loader!./~/css-loader!./stylesheets/welcome.css:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./stylesheets/welcome.css:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./stylesheets/welcome.css:7,0]

WARNING in css-theme.entry.js from UglifyJs
Condition always false [./~/style-loader/addStyles.js:24,0]
Dropping unreachable code [./~/style-loader/addStyles.js:25,0]
Condition always false [./~/style-loader!./~/css-loader!./~/less-loader!./stylesheets/less/index.less:10,0]
Dropping unreachable code [./~/style-loader!./~/css-loader!./~/less-loader!./stylesheets/less/index.less:12,0]
Side effects in initialization of unused variable update [./~/style-loader!./~/css-loader!./~/less-loader!./stylesheets/less/index.less:7,0]
root@data:/usr/local/lib/python2.7/dist-packages/caravel/static/assets#

**Comment by lihemin** [comment]
my version is   0.9.1

**Comment by mistercrunch** [comment]
Why are you building 0.9.1?

**Comment by lihemin** [comment]
work  need

**Comment by lihemin** [comment]
job demand

**Comment by lihemin** [comment]
ERROR in ./javascripts/caravel-select2.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/jquery-ui/themes/base/jquery-ui.css in /home/data/space/caravel-0.10.0/caravel/assets/javascripts
 @ ./javascripts/caravel-select2.js 5:0-62

**Comment by lihemin** [comment]
same log and error  in building v0.10.1

**Comment by PickLiDan** [comment]
@lihemin 
You can it like this : npm run prod ERROR: #937
 #937

**Comment by xrmx** [comment]
So closing as dup of #937
