### ISSUE TITLE
Make histogram viz look more like the others

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#989]
The axis look way different. We may want to use common CSS across viz for that purpose.

**Comment by ascott** [comment]
we are moving towards common css for charts, but for now it would be great to make this one look more like this

<img width="863" alt="screenshot 2016-08-23 20 28 00" src="https://cloud.githubusercontent.com/assets/130878/17917300/ef859584-696f-11e6-89df-ed2cdc04940a.png">

**Comment by mistercrunch** [comment]
Seems like we could re-use nvd3's bar chart here too somehow.

**Comment by mike-grayhat** [comment]
#3777
