### ISSUE TITLE
Since/Until time attributes generated incorrectly when using custom DATETIME column

### ISSUE THREAD

**Issue by dugjason** [airbnb/caravel#998]
I have a `received_at` DB column which is stored as a VARCHAR, the value of which will be a unixtimestamp with miliseconds; one example is : "1471965808.267". 
I've created a custom table column, using `FROM_UNIXTIME(received_at)` in the "Expression" and "Database Expression" fields for this custom column.

When I try to use this custom column for time attribute filters, I'm seeing the following SQL generated;

```
SELECT COUNT(*) AS count
FROM table_name
WHERE FROM_UNIXTIME(received_at) >= FROM_UNIXTIME(received_at)
  AND FROM_UNIXTIME(received_at) <= FROM_UNIXTIME(received_at)
  AND source_id IN ('e3872c5c705e4236b067fce1946f027b') LIMIT 50000
```

When I switch back to the default temporal column for this table, I have the following SQL generated;

```
SELECT COUNT(*) AS count
FROM table_name
WHERE created_at >= '2016-08-23 15:25:37.000000'
  AND created_at <= '2016-08-23 16:25:37.000000'
  AND source_id IN ('e3872c5c705e4236b067fce1946f027b') LIMIT 50000  
```

The comparison being made is against the field itself, rather than against "1 hour ago". 

My setup is:
* MySQL 5.6.31
* Ubuntu 14.04.5
* Hosted on EC2
* Caravel from Master branch; latest commit 30ef8eb

**Comment by xrmx** [comment]
In 0.10 is broken too on postgresql but differently:
```
SELECT COUNT(*) AS count
FROM utilizzo
WHERE date_trunc('month', data) >= '2016-08-16 19:08:45.000000'
  AND date_trunc('month', data) <= '2016-08-23 19:08:45.000000' LIMIT 5000
```
So i'm wondering if expressions are simply not supposed to be used as time column or we have already the machinery to parse the expression and cast the interval to the same type.

**Comment by dugjason** [comment]
So it looks like adding a custom column in the following way allows us to plot a timeseries chart based on a double type unix timestamp;

![screen shot 2016-08-31 at 10 41 09](https://cloud.githubusercontent.com/assets/273718/18123818/92f24652-6f67-11e6-98f0-708bb15c2098.png)

Grouping by hour generates the following SQL:

```
SELECT DATE_ADD(DATE(FROM_UNIXTIME(received_at)), INTERVAL HOUR(FROM_UNIXTIME(received_at)) HOUR) AS timestamp,
       COUNT(*) AS count
FROM interaction
WHERE FROM_UNIXTIME(received_at) >= '2016-08-24 10:40:28.000000'
  AND FROM_UNIXTIME(received_at) <= '2016-08-31 10:40:28.000000'
GROUP BY DATE_ADD(DATE(FROM_UNIXTIME(received_at)), INTERVAL HOUR(FROM_UNIXTIME(received_at)) HOUR) LIMIT 50000
```

and a meaningful chart

![screen shot 2016-08-31 at 10 43 09](https://cloud.githubusercontent.com/assets/273718/18123879/c95eca9e-6f67-11e6-977b-62c9ca630910.png)

The problem seemed to come from adding a SQL expression to the 'Database Expression' field.
To me, it's not entirely obvious what these fields should be used for. This was  a simply fix, but the descriptive text for the 'Database Expression' field suggested I needed to add something if I was looking to convert my float unix timestamp to a DateTime object

**Comment by xrmx** [comment]
Good, closing then. Feel free to open a pull request with a clearer message. Thanks!
